### ISSUE TITLE
IAM authentication fails, partial 403 error response in Cloud SQL logs

### ISSUE THREAD

**Issue by mbrancato** [GoogleCloudPlatform/cloudsql-proxy#1013]
## Bug Description

I have a Postgres Cloud SQL instance that is configured with IAM authentication. When using the cloud proxy (I have not attempted to connect directly as that requires mTLS setup), both IAM and manual auth with an OAuth2 token fail with the same error. Part of the error includes a partial 403 error response in the Cloud SQL server logs. I'm trying to identify if this is a Cloud SQL proxy issue, or something on the Cloud SQL instance that is broken.

We're using the GKE workload identity, and that appears to be working. I've gone thru all the troubleshooting steps for the workload identity, and manually verified with the metadata service and gcloud that it works.

```
% gcloud container clusters describe my-database-instance --project my-project-id --region europe-west3  --format="value(workloadIdentityConfig.workloadPool)"                            
my-project-id.svc.id.goog

% gcloud container node-pools describe detection --project my-project-id --cluster my-database-instance --project my-project-id --region europe-west3 --format="value(config.workloadMetadataConfig.mode)"
GKE_METADATA

% kubectl describe serviceaccount --namespace detection my-k8s-service-acct                                                
Name:                my-k8s-service-acct
Namespace:           detection
Labels:              kustomize.toolkit.fluxcd.io/name=eu
                     kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:         iam.gke.io/gcp-service-account: my-service-acct@my-project-id.iam.gserviceaccount.com
                     kustomize.toolkit.fluxcd.io/checksum: 6eb1d5f6d3e32b17228e842b4321da4928888e2c
Image pull secrets:  <none>
Mountable secrets:   my-k8s-service-acct-token-mr4dx
Tokens:              my-k8s-service-acct-token-mr4dx
Events:              <none>

% gcloud iam service-accounts get-iam-policy my-service-acct@my-project-id.iam.gserviceaccount.com                                                                                        
bindings:
- members:
  - serviceAccount:my-project-id.svc.id.goog[detection/my-k8s-service-acct]
  role: roles/iam.workloadIdentityUser
etag: BwXPcE8b9Ow=
version: 1
```

## Example code (or command)

Trying with IAM authentication on the cloudsql proxy results in a failed auth. The DB has the `cloudsql.iam_authentication` flag enabled and the service account "my-service-acct@my-project-id.iam" has been granted access to connect and login to the DB instance.

```
% ./cloud_sql_proxy -instances=my-project-id:europe-west3:my-database-instance=tcp:5432 -ip_address_types=PRIVATE -enable_iam_login -verbose &
[1] 3970
% 2021/11/10 01:32:54 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2021/11/10 01:32:54 Listening on 127.0.0.1:5432 for my-project-id:europe-west3:my-database-instance
2021/11/10 01:32:54 Ready for new connections
2021/11/10 01:32:54 Generated RSA key in 206.256802ms

% psql "postgres://my-service-acct%40my-project-id.iam@127.0.0.1:5432/my-database"
2021/11/10 01:33:39 New connection for "my-project-id:europe-west3:my-database-instance"
2021/11/10 01:33:39 refreshing ephemeral certificate for instance my-project-id:europe-west3:my-database-instance
2021/11/10 01:33:39 Scheduling refresh of ephemeral certificate in 58m8.889958318s
psql: error: FATAL:  Cloud SQL IAM user authentication failed for user "my-service-acct@my-project-id.iam"
2021/11/10 01:33:39 Client closed local connection on 127.0.0.1:5432
```

After this attempt, on the Cloud SQL server side, we see this in the logs. Some of which is a partial, truncated 403 response from the IAM credentials API.

```
2021-11-10 01:33:39.570 UTC [1225102]: [1-1] db=my-database,user=my-service-acct@my-project-id.iam FATAL: Cloud SQL IAM user authentication failed for user "my-service-acct@my-project-id.iam"
2021-11-10 01:33:39.570 UTC [1225102]: [2-1] db=my-database,user=my-service-acct@my-project-id.iam DETAIL: The caller does not have permission Connection matched pg_hba.conf line 20: "local all +cloudsqliamuser cloudsql-iam-user"
```

I also tried the manual auth mode using cloudsql-proxy without IAM auth enabled (without `-enable_iam_login`). Documented here: https://cloud.google.com/sql/docs/postgres/iam-logins#logging-in-as-a-user

```
% ./cloud_sql_proxy -instances=my-project-id:europe-west3:my-database-instance=tcp:5434 -ip_address_types=PRIVATE &
[1] 4974
% 2021/11/10 03:21:29 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2021/11/10 03:21:31 Listening on 127.0.0.1:5434 for my-project-id:europe-west3:my-database-instance
2021/11/10 03:21:31 Ready for new connections
2021/11/10 03:21:31 Generated RSA key in 267.285782ms

% PGPASSWORD=$(gcloud auth print-access-token) psql --host=127.0.0.1 --username="my-service-acct@my-project-id.iam" --dbname=my-database --port=5434
2021/11/10 03:21:41 New connection for "my-project-id:europe-west3:my-database-instance"
2021/11/10 03:21:41 refreshing ephemeral certificate for instance my-project-id:europe-west3:my-database-instance
2021/11/10 03:21:42 Scheduling refresh of ephemeral certificate in 23h54m58.96475507s
psql: error: FATAL:  Cloud SQL IAM user authentication failed for user "my-service-acct@my-project-id.iam"
2021/11/10 03:21:42 Client closed local connection on 127.0.0.1:5434
```

The same errors are seen in the CloudSQL server logs:

```
2021-11-10 03:21:42.121 UTC [1232338]: [1-1] db=my-database,user=my-service-acct@my-project-id.iam FATAL: Cloud SQL IAM user authentication failed for user "my-service-acct@my-project-id.iam"
2021-11-10 03:21:42.121 UTC [1232338]: [2-1] db=my-database,user=my-service-acct@my-project-id.iam DETAIL: The caller does not have permission Connection matched pg_hba.conf line 20: "local all +cloudsqliamuser cloudsql-iam-user"
```

The string `The caller does not have permission` is from a 403 response to the IAM credentials API, but the client doesn't see that.

## Environment

1. OS type and version: Linux, cloudsql-proxy container
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.27.0
using  `gcr.io/cloudsql-docker/gce-proxy:1.27.0`

**Comment by mbrancato** [comment]
We have solved this - there appears to be a bug in the Cloud Console or something in the API. 

Google's docs say - https://cloud.google.com/sql/docs/postgres/add-manage-iam-users
```
Service accounts use the format service-account-name@project-id.iam.gserviceaccount.com. 
When you add an IAM service account to the database, you leave off the .gserviceaccount.com domain.
```

However, something about leaving the `.gserviceaccount.com` causes it to be seen as a User and not a Service Account.

In the cloud console, the user showed as this type:
![image](https://user-images.githubusercontent.com/8493275/141133228-8eaeb509-6a2d-424e-bc6e-b878e860180d.png)

And the API returned this on listing users:

```
host: ""
iamEmail: ""
instance: "my-database-instance"
name: "my-service-acct@my-project-id.iam"
project: "my-project-id"
type: "CLOUD_IAM_USER"
```

It should show as `CLOUD_IAM_SERVICE_ACCOUNT`. I removed the grants and user, then re-added the account and DID NOT leave off the `.gserviceaccount.com` and now the user is seen as a Service Account and works. I've reported via our support, so hopefully Google will fix this.

**Comment by enocom** [comment]
Thanks @mbrancato. Glad you found a working solution.

> However, something about leaving the .gserviceaccount.com causes it to be seen as a User and not a Service Account.

I see the same issue. I think the docs are just wrong in this case. The Cloud Console does the right thing when the full service account is provided as you note. The docs should call out the need to drop `.gserviceaccount.com` for only REST API calls. Looks like they already do for the `gcloud` tab.

I'll open an internal bug to update the docs.
