### ISSUE TITLE
bad CPU type in executable

### ISSUE THREAD

**Issue by rafiahmad16** [GoogleCloudPlatform/cloudsql-proxy#1024]
Hi,
I have MacBook Pro (16-inch, 2021) with Apple M1 Pro chips
i followed the instruction as per google [docs](https://cloud.google.com/sql/docs/mysql/sql-proxy) but when i try to excecute 
`./cloud_sql_proxy --help` 
it throw me an error 
`zsh: bad CPU type in executable: ./cloud_sql_proxy`

**Comment by enocom** [comment]
@rafiahmad16 Did you get the proxy to run on your machine? We do have an M1 binary available here: https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases/tag/v1.27.0.

**Comment by rafiahmad16** [comment]
yes i try to install from source by using go lang now i am able to connect with cloud proxy
