### ISSUE TITLE
FR: Support multiple --instances flag

### ISSUE THREAD

**Issue by tsawada** [GoogleCloudPlatform/cloudsql-proxy#1030]
It'd be nice if clousd_sql_proxy accepts multiple --instances flags combined.
In k8s Deployment config, let's say if you need to specify 10 instances

```
command:
  - "/cloud_sql_proxy"
  - "--instances=some-project:some-zone:instance-name-1=tcp:3366"
  - "--instances=some-project:some-zone:instance-name-2=tcp:3367"
  - ...
```

is much easier to read than everything jammed together in one line.
If this sounds good please let me know and I'm happy to send a PR.

**Comment by enocom** [comment]
We're working on almost exactly the same thing as part of the [v2 release](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/872).

The invocation will look like this:

```
cloud_sql_proxy <INSTANCE_CONNECTION_NAME1> <INSTANCE_CONNECTION_NAME2>
```

We're actively working on getting a beta version of v2 out of the door. Until that's available, I'm going to leave this open.

**Comment by tsawada** [comment]
Thanks! Does that mean it doesn't hurt to have this feature in v1 as well ...? ;)

**Comment by enocom** [comment]
Thanks for the PR. I need to verify that this won't be a breaking change, and will leave a review soon.
