### ISSUE TITLE
Panic in liveness endpoint

### ISSUE THREAD

**Issue by vikstrous2** [GoogleCloudPlatform/cloudsql-proxy#1065]
## Bug Description

When this google cloud incident started https://status.cloud.google.com/incidents/NMcnk6aE8xMHHwRGmyry, our cloudsql proxy started being killed by liveness probes. They are configured according to this recommendation https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/main/examples/k8s-health-check#cloud-sql-proxy-health-checks. That's fine and expected, but the error message was very confusing:

```
[Health Check] Liveness failed: %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
```

There seems to be a panic somewhere in cloudsql proxy, but no more information was printed.

## Environment

1. OS type and version: GKE
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): gcr.io/cloudsql-docker/gce-proxy:1.27.0-buster@sha256:5d3d9bb25542b5f786cdb983d052b5f9145c9abd0b7128688f545ae9ce060fca

**Comment by enocom** [comment]
Thanks for the report @vikstrous2. I'll take a closer look and report back here.

**Comment by enocom** [comment]
@vikstrous2 out of curiosity, what logging do you see immediately before this line?
