### ISSUE TITLE
cloud_sql_proxy doesn't use output of standard unix streams

### ISSUE THREAD

**Issue by iamkarlson** [GoogleCloudPlatform/cloudsql-proxy#1079]
## Bug Description
this doesn't work:
```
cloud_sql_proxy --help | less
```

## Environment

1. any linux
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 
``` 
> cloud_sql_proxy --version
Cloud SQL Auth proxy: 1.27.0+linux.amd64
```

**Comment by enocom** [comment]
Thanks for the report. This has bugged me for quite some time. I'll get a fix out.

**Comment by enocom** [comment]
Looking at this again, now I remember what's going on. The output is going to standard error, as many Go commands do.

Try this:

```
cloud_sql_proxy --help 2>&1 | less
```

**Comment by enocom** [comment]
For what it's worth, when the [upcoming v2](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/872) is available, the redirect to stdout will be unnecessary and help messages will go straight to stdout.
