### ISSUE TITLE
Connection reset by peer errors 

### ISSUE THREAD

**Issue by gbinow** [GoogleCloudPlatform/cloudsql-proxy#1095]
Hello.

We have a k8s installation on GKE to run our application (basically a Nginx+PHP+Mysql setup). We have a PHP-FPM service (version 7.4) and a cloudsql-proxy service (version 1.28.1). It is worth mentioning that I use Docrine as ORM for DB connections.

We've been using GKE since early 2018 with no issues.

We started to notice sporadic error logs with the message SQLSTATE[HY000] [2002] Connection reset by peer. We checked the Logs and the errors started on January 11, 2022 (we couldn't find any records before this date). We don't have a precise number, but analysing the logs, we do believe less then 1% of the connections are being terminated due to this error. 

Both our GKE cluster (k8s version 1.20.12) and our Cloud SQL instance (MySQL 5.7) have resources to spare, even at peak times they are well underutilized. In addition, the error also occurs at times when the environment is practically without load and without requests being handled (during dawn). So I don't think it has anything to do with high CPU usage or any other kind of resource limits (https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/343#issuecomment-780769779).

We've tried restarting the services, but the error is still going on.

We didn't make any updates to our environment on this date or in the days before the error first occurred. I believe something has been updated/changed in the GCP infrastructure and is generating some kind of incompatibility with the proxy since the error simply just appeared out of the blue. Does it make sense?

Could you please help us? We're really lost here :(

**Comment by enocom** [comment]
Hi @gbinow. Some more information would help here.

What are the exact error messages in the proxy logs (if any)? Are the errors you're seeing in the application only? Have you figured out how to reproduce this issue?

**Comment by gbinow** [comment]
Hello @enocom.

_What are the exact error messages in the proxy logs (if any)?_ 

There are no error messages in the proxy logs. The only kind of proxy logs I was able to find are the "New connection..", "Client closed local connection.." and "Instance <instance_name> closed connection".

_Are the errors you're seeing in the application only?_

The errors are spawning only in the application (PHP-FPM). They are like this: 

Uncaught PHP Exception Doctrine\\DBAL\\Exception\\ConnectionException: \"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection reset by peer\" at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93

_Have you figured out how to reproduce this issue?_

No I haven't.  I'll try to setup a test environment and reproduce the problem.

**Comment by enocom** [comment]
So my first impression is that this is an application-level problem. Nonetheless, here are some things to try:

1. Downgrade (or upgrade) Docrine to see if it's somehow a library problem.
2. Try building a minimal app that just connects to the database and reads the time (`SELECT NOW()`) or similar, to see if a smaller app has this problem.
3. Try pointing your app at a separate database to see if it's somehow the database that's causing the problem.

If there's some kind of problem in the proxy, I'd expect you would see some logs there.

Side note: the logs about "scheduling refresh.." and "refreshing..." are totally normal and working as intended.

**Comment by gbinow** [comment]
Thanks for the guidance. I'll try the steps you wrote. But I'll maybe need a few days to do it. 

I'll get back here as soon as possible.

**Comment by gbinow** [comment]
Hello, @enocom.

I was just able to reproduce the error on a minimal php script. It took some time as predicted because as I said before, the error rate is very low.

I basically created a CronJob and run a script that connects to the proxy, performs a `SELECT NOW()` query, sleeps for 4 seconds and closes the connection. The error appeared only after around 3k successful connections.

Any other thoughts?
Thanks in advance 

`try {
    for($i = 0 ; $i < $totalRuns ; $i++){
        $conn = new PDO("mysql:host=$servername;dbname=$database", $username, $password);
        // set the PDO error mode to exception
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        sleep($sleepTimeSeconds);

        $stmt = $conn->query('SELECT NOW() as n');
        
        $conn = null;
    }

    echo json_encode([
        'message' => 'OK'
    ]) . PHP_EOL;

} catch(PDOException $e) {
    echo json_encode([
        'message' => "Connection failed: " . $e->getMessage()
    ]) . PHP_EOL;
}

return 0;`

**Comment by enocom** [comment]
Thanks @gbinow. When you ran the latest experiment, did you see any errors in the proxy logs?

**Comment by gbinow** [comment]
Still no errors. 

App logs:
<img width="892" alt="Screen Shot 2022-02-11 at 15 42 33" src="https://user-images.githubusercontent.com/9823523/153651263-a7eecb98-cf2f-4449-a874-95263b8b8b72.png">

Proxy Logs
<img width="1023" alt="Screen Shot 2022-02-11 at 15 45 50" src="https://user-images.githubusercontent.com/9823523/153651278-44e3ff36-2234-42ef-ac36-f9177ad6c8f2.png">

**Comment by gbinow** [comment]
It uses Docker

**Comment by enocom** [comment]
From what I understand if you switch to containerd, it will fix this problem. Would you mind trying that and reporting back?

There's a guide here: https://cloud.google.com/kubernetes-engine/docs/how-to/migrate-containerd.

**Comment by gbinow** [comment]
As I'm not sure migrating to containerd will have any impacts on my application, I'll need some time to perform a few tests before migrating. As soon as I'm able to do it I'll let you know.
Thanks very much

**Comment by gbinow** [comment]
@enocom switching to containerd apparently solved the problem. 
Thank you very much!
