### ISSUE TITLE
PgBouncer cannot query pg_shadow in Cloud SQL to authenticate client

### ISSUE THREAD

**Issue by d3vesh-bo** [GoogleCloudPlatform/cloudsql-proxy#1099]
We intend to use the Postgres database of Cloud SQL for our application and connect it using cloud-sql-proxy. After reading documentation and other related articles (github issue: #88 ), we decided to run a single instance of pgbouncer and cloudsql-proxy, as a side-car, which proxies and pools connections to cloudsql postgres database.
Our Configuration:
App/service -> (PgBouncer + cloudsql-proxy) -> cloud sql database

Pgbouncer Authentication:
We want to authenticate the client by querying the database (auth_user and auth_query) using Postgres SECURITY DEFINER function which basically queries pg_shadow view
Example function:
```
CREATE OR REPLACE FUNCTION public.user_lookup(INOUT p_user     name, OUT   p_password text)
RETURNS record AS $$
BEGIN
SELECT usename, passwd FROM pg_catalog.pg_shadow 
WHERE usename = p_user;
RETURN;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
```
But as pg_shadow can only be read by the superuser and no user in cloud SQL is granted complete superuser privileges (not even postgres user). So no customer-created user/postgres user has access to read pg_shadow. This makes it impossible to setup pgbouncer with the SECURITY DEFINER function (preferred method in pgbouncer).

We've read through many articles where they have suggested using pgbouncer but have not acknowledged the above problem.

How can pgbouncer authenticate the client by querying the pg_shadow to pool connections for Cloud SQL (Postgres)?

Could you please help us?

**Comment by d3vesh-bo** [comment]
Thank you for your prompt reply.


From what I understood

![Pgbouncer-CloudSQL configuration](https://user-images.githubusercontent.com/63905355/153571184-3164a81e-18b3-4fcc-aa40-901a3f3c3095.PNG)


- user1 and pswd1 is the credential of user that will be used by the app to connect to database
- auth_file: users_list.txt using md5 auth
  `
"user1" "md5 password for pswd1"
 `
- cloud proxy: proxying connection for IAM principal (eg. service account) through automatic IAM authentication.

Additional info:

pgbouncer.ini

```
  [databases]
  cloud_sql_proxy = host=127.0.0.1 port=5431 dbname=postgres
  
  [pgbouncer]
  auth_type = md5
  auth_file = /etc/pgbouncer/userlist.txt
```

Please correct me if I am wrong!

**Comment by enocom** [comment]
Yep, that's the idea. Thanks for the nice diagram.

I'm going to close this (but we'll always have it for future reference).

**Comment by mgreenw** [comment]
@enocom This feature would be extremely helpful to have integrated directly Google Cloud SQL directly so there are no additional hoops to jump through, and I suspect that that many firms would pay extra to use it. Are there plans to integrate pgbouncer or similar directly with Google Cloud SQL? Thanks!

**Comment by enocom** [comment]
Completely agree on this being a useful feature for Cloud SQL to add. 

I can't comment on the upcoming Cloud SQL roadmap, but will update this issue if the pg_shadow support story changes. Meanwhile, I'll make sure the product team sees the interest in this.

**Comment by enocom** [comment]
This is now a supported flag. :wink: 

https://cloud.google.com/sql/docs/postgres/users#pg_shadow

**Comment by Shahor** [comment]
@enocom Thanks for that update! 

Do you know if supporting pgBouncer directly from Google Cloud SQL (ala Crunchy bridge) is something in the roadmap? That would surely make this whole thing much easier for customers.

**Comment by Shahor** [comment]
What's your threshold for considering customer demands and how many demands did you receive 😬 ?
(Technically not commenting on the upcoming roadmap 😬)

**Comment by enocom** [comment]
Off-loading the burden of running pgbouncer to Cloud SQL would be a big win, I agree, but I don't own the roadmap and so can only speak to what's already publicly known. :-)

**Comment by rushilsrivastava** [comment]
We run PGBouncer in a similar setup, but would really love to have it managed directly through CloudSQL. Is there a feature request already open where we can track this?

**Comment by enocom** [comment]
Watching the [Release Notes](https://cloud.google.com/sql/docs/release-notes) would be best.

**Comment by rushilsrivastava** [comment]
> Watching the [Release Notes](https://cloud.google.com/sql/docs/release-notes) would be best.

Don't think this was what I was looking for, but I found it myself and have created a new feature request [here](https://issuetracker.google.com/issues/240311501).

**Comment by AnatoliiPerfun** [comment]
Application -> pgbouncer + Cloud SQL Auth Proxy -> Cloud SQL instance is not a good idea... don't waste your time on PgBouncer for connection pooling with Cloud SQL in GCP. The docs (https://cloud.google.com/sql/docs/mysql/manage-connections) don't mention it for a reason - it's not supported! Cloud SQL Auth Proxy already handles secure connections and basic pooling. Keep it simple and manage pooling in your code.

**Comment by enocom** [comment]
FYI https://cloud.google.com/sql/docs/postgres/users#pg_shadow

pgbouncer + Cloud SQL Proxy does work, but it does require you to deploy and run pgbouncer yourself. We have an example of how to do that here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/tree/main/examples/k8s-service.

**Comment by AnatoliiPerfun** [comment]
Yes, you are right, but I assumed the original requirement was to set up pgbouncer + cloud-auth-proxy on a VM instance and make it work with Cloud SQL. On Kubernetes, it can surely run.

**Comment by silvamerica** [comment]
> Application -> pgbouncer + Cloud SQL Auth Proxy -> Cloud SQL instance is not a good idea... don't waste your time on PgBouncer for connection pooling with Cloud SQL in GCP. The docs (https://cloud.google.com/sql/docs/mysql/manage-connections) don't mention it for a reason - it's not supported! Cloud SQL Auth Proxy already handles secure connections and basic pooling. Keep it simple and manage pooling in your code.

FYI: [The README recommends using pgbouncer](https://github.com/GoogleCloudPlatform/cloud-sql-proxy?tab=readme-ov-file#should-i-use-the-proxy-for-large-deployments).
