### ISSUE TITLE
CloudSQL Proxy not shutting down after a few hours despite setting `term_timeout=120s`

### ISSUE THREAD

**Issue by yehoshuadimarsky** [GoogleCloudPlatform/cloudsql-proxy#1115]
## Bug Description

I am running this as a sidecar in a pod that is acting as an Airflow worker. The Airflow docs state ([here](https://airflow.apache.org/docs/helm-chart/stable/using-additional-containers.html#sidecar-containers))

> If you use `workers.extraContainers` with `KubernetesExecutor`, you are responsible for signaling sidecars to exit when the main container finishes so Airflow can continue the worker shutdown process!

So I passed the following into the `values.yaml` of the official Airflow Helm chart (version 1.4):

```yaml
extraContainers:
  - name: cloud-sql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
    command:
      - "/cloud_sql_proxy"
      - "-instances=[MY_PROJECT]:us-east1:[DB_NAME]=tcp:5432"
      - "-structured_logs"
      - "-ip_address_types=PRIVATE"
      - "-term_timeout=120s"
      - "-enable_iam_login"
    securityContext:
      runAsNonRoot: true
    imagePullPolicy: IfNotPresent
```

So, I expect that because I am setting the `-term_timeout` flag to 120 seconds, it will automatically shut down after 120 seconds. But it doesn't. Here are the logs of the sidecar (redacted as `[PROJECT:REGION:DB_NAME]`):

```json
{"severity":"INFO","timestamp":"2022-02-24T18:06:44.945Z","caller":"limits/limits.go:50","message":"current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here."}
{"severity":"INFO","timestamp":"2022-02-24T18:06:45.280Z","caller":"cloud_sql_proxy/proxy.go:172","message":"Listening on 127.0.0.1:5432 for [PROJECT:REGION:DB_NAME]"}
{"severity":"INFO","timestamp":"2022-02-24T18:06:45.281Z","caller":"cloud_sql_proxy/cloud_sql_proxy.go:681","message":"Ready for new connections"}
{"severity":"INFO","timestamp":"2022-02-24T18:06:45.910Z","caller":"certs/certs.go:287","message":"Generated RSA key in 637.560474ms"}
{"severity":"INFO","timestamp":"2022-02-24T18:06:56.550Z","caller":"cloud_sql_proxy/proxy.go:160","message":"New connection for \"[PROJECT:REGION:DB_NAME]\""}
{"severity":"INFO","timestamp":"2022-02-24T18:06:56.551Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance [PROJECT:REGION:DB_NAME]"}
{"severity":"INFO","timestamp":"2022-02-24T18:06:56.668Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 58m52.885496613s"}
{"severity":"INFO","timestamp":"2022-02-24T18:06:56.778Z","caller":"proxy/common.go:72","message":"Client closed local connection on 127.0.0.1:5432"}
{"severity":"INFO","timestamp":"2022-02-24T19:05:49.555Z","caller":"proxy/client.go:239","message":"ephemeral certificate for instance [PROJECT:REGION:DB_NAME] will expire soon, refreshing now."}
{"severity":"INFO","timestamp":"2022-02-24T19:05:49.556Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance [PROJECT:REGION:DB_NAME]"}
{"severity":"INFO","timestamp":"2022-02-24T19:05:49.910Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 59m3.85121879s"}
{"severity":"INFO","timestamp":"2022-02-24T20:04:53.761Z","caller":"proxy/client.go:239","message":"ephemeral certificate for instance [PROJECT:REGION:DB_NAME] will expire soon, refreshing now."}
{"severity":"INFO","timestamp":"2022-02-24T20:04:53.762Z","caller":"proxy/client.go:203","message":"refreshing ephemeral certificate for instance [PROJECT:REGION:DB_NAME]"}
{"severity":"INFO","timestamp":"2022-02-24T20:04:54.011Z","caller":"proxy/client.go:320","message":"Scheduling refresh of ephemeral certificate in 59m3.853266034s"}
```

As you can see, at `2022-02-24T18:06:56.778Z` the message is `Client closed local connection on 127.0.0.1:5432`. But then it continues to stay up, refreshing certificates and just hanging around.

**Why didn't it shut down?**

As an aside, I thought the discussion here https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/828 would help me, but I don't see a clean solution here to automatically shut down the cloud sql proxy sidecar when the main container is finished.

## Environment

1. OS type and version: Kubernetes in GKE version 1.20.12-gke.1500
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.28.0

**Comment by enocom** [comment]
@yehoshuadimarsky The term timeout flag sets a fixed amount of time to wait after receiving a `SIGTERM`. All clients closing connections doesn't stop the proxy.

I'm not familiar with Airflow, but ideally you'd be able to send `SIGTERM` to the proxy once you're done with it.

> you are responsible for signaling sidecars to exit when the main container finishes 

Is there a way to signal to sidecars in Airflow?

**Comment by yehoshuadimarsky** [comment]
Ah I see, I thought it terminates after the clients close connections, didn't realize what that flag does. Got it.

Unfortunately I don't yet know a way to signal sidecars in Airflow. Thanks for clarifying though!

**Comment by enocom** [comment]
@yehoshuadimarsky there is an open request for something like this in #828, so feel free to add your use case there. It seems more and more people need something like this in the proxy.
