### ISSUE TITLE
Permissions error reading credentials with running docker container past 1.16

### ISSUE THREAD

**Issue by aebrahim** [GoogleCloudPlatform/cloudsql-proxy#1124]
## Bug Description

I expect that the container will start, but instead it errors out with a permission denied error when attempting to read the credentials file.

## Example code (or command)

For example, this works:
```
>>> docker run -v ~/developer_creds.json:/config gcr.io/cloudsql-docker/gce-proxy:1.16 /cloud_sql_proxy -instances=myproject:us-central-1:db=tcp:0.0.0.0:5432 -credential_file=/config
2022/03/03 19:18:10 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2022/03/03 19:18:11 using credential file for authentication; email=developers@myproject.iam.gserviceaccount.com
2022/03/03 19:18:11 Listening on 0.0.0.0:5432 for myproject:us-central-1:db
2022/03/03 19:18:11 Ready for new connections
```

However, this fails:
```
docker run -v ~/developer_creds.json:/config gcr.io/cloudsql-docker/gce-proxy:1.17 /cloud_sql_proxy -instances=myproject:us-central-1:db=tcp:0.0.0.0:5432 -credential_file=/config
```

## Stacktrace
```
2022/03/03 19:19:32 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2022/03/03 19:19:33 invalid json file "/config": open /config: permission denied
```

## Environment

1. Ubuntu 20.04

**Comment by kurtisvg** [comment]
Hi @aebrahim -- the most likely cause is that the linux user in the container doesn't have permission to access your credential file. You need to make sure [uid 65532](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/7e0c7081ed129e12d7e682351a15930a294d8392/Dockerfile#L28) can read the file.

**Comment by enocom** [comment]
There are two ways to do this:

First, you can run your container as a user (and group) like so:

 ```
docker run 
  -v $PWD/key.json:/config/key.json \
  --user 65532:65532 \
  gcr.io/cloudsql-docker/gce-proxy:1.17 /cloud_sql_proxy \
  -instances=<INSTANCE_CONNECTION_NAME> \
  -credential_file=/config/key.json
```

Note, your `key.json` will need to be readable by 65532, e.g., `chmod o+r key.json` (not recommended).

Second, just switching to the alpine or buster container requires no special changes:

```
docker run \
  -v $PWD/key.json:/config/key.json \
  gcr.io/cloudsql-docker/gce-proxy:1.17-alpine /cloud_sql_proxy \
  -instances=<INSTANCE_CONNECTION_NAME> \
  -credential_file=/config/key.json
```

**Comment by aebrahim** [comment]
It seems like the second method still requires a `chmod o+r key.json` (or in my case a `chgrp 65532 key.json && chmod g+r key.json`)

While not ideal, this workaround works for me so closing this bug. Thanks for the quick update!

**Comment by enocom** [comment]
@aebrahim Exactly. The default container basically assumes a Kubernetes runtime, which makes it inconvenient for plain docker uses. But you've got the right idea about `chgrp` etc. It's a pain so using the Alpine container is probably easiest.

**Comment by enocom** [comment]
Actually, when I tested the alpine container I forgot that I'd modified group permissions for my `key.json` and the alpine container uses the same uid. Let me dig into this a bit more and figure out how to handle this.

**Comment by enocom** [comment]
So for anyone else who comes across this thread, all containers use the same non-root uid 65532. To get around this, you can do a couple of things:

1. Change the group of the `key.json` to match the uid with `chgrp 65532 key.json && chmod g+r key.json` as @aebrahim suggests. This at least lets your user still read the file and the conatiner user.
2. If you don't care about your user reading the file, you can also just pass ownership to 65532 with `chown 65532 key.json`. One less command, but also any reads of the file require `sudo`.
