### ISSUE TITLE
failed to setup file descriptor limits

### ISSUE THREAD

**Issue by thiago4int** [GoogleCloudPlatform/cloudsql-proxy#1133]
## Bug Description

Connection is stablished and ready. The client will timeout after throwing an invalid argument

## Example code (or command)

```
failed to setup file descriptor limits: failed to set rlimit {&{8500 4096}} for max file descriptors: invalid argument
```

## Stacktrace
```
Any relevant stacktrace here. Be sure to filter sensitive information.
```

## How to reproduce

  1. ?
  2. ?

## Environment

1. many different Linux OS
2.  Cloud SQL Proxy: NO_VERSION_SET

**Comment by enocom** [comment]
How are you invoking the proxy? The `invalid argument` makes me think the invocation has a problem.

Also, if you're not using a version, did you build from source? What SHA did you use?

**Comment by enocom** [comment]
I'm going to close this as stale. If you're still seeing this issue, feel free to re-open with some more information.
