### ISSUE TITLE
googleapi: Error 403: The client is not authorized to make this request., notAuthorized

### ISSUE THREAD

**Issue by wieger** [GoogleCloudPlatform/cloudsql-proxy#115]
Hi,

I try to connect to my cloudsql instance using the Proxy Docker Image, but it fails on authorisation issue, and could use some help in debugging the issue.

All seems to be configured right when pod is deployed, when i look in the logs it states:
```
2017/08/17 15:24:33 using credential file for authentication; email=service-account@project-id.iam.gserviceaccount.com
2017/08/17 15:24:33 Listening on 127.0.0.1:3306 for [project-id:region:instance-name]
2017/08/17 15:24:33 Ready for new connections
```
 but it keeps failing when I open a connection with the message
 
```
couldn't connect to "[project-id:region:instance-name]": ensure that the account has access to "[project-id:region:instance-name]" (and make sure there's no typo in that name). 
Error during createEphemeral for [project-id:region:instance-name]: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```

However if I use the cloud_sql_proxy from my local machine all works like a charm:

```
./cloud_sql_proxy -instances=project-id:region:instance-name=tcp:3307 -credential_file=keys/service-account-key.json
```

I have als tried resetting the roles on the service-account as suggested in issue #37 but that did not help, removing the roles made the ./cloud_sql_proxy also fail on notAuthorized, and adding them enabled it but the docker image proxy still is failing.

So, same service account, same project-id, same cloudsql instance, just the location differs. Any idea where to start debugging this?

**Comment by AthenaShi** [comment]
Hi,

Would you please send the name of your cloud sql instance to
cloud-sql@google.com (with a link to this page) so I may be able to help out
looking at some internal data.

Also, please paste the full command line you run both with and without Proxy Docker Image, and the logs when connection.

**Comment by Carrotman42** [comment]
Did you follow the URL in the error log to enable the API?

**Comment by DinaWork** [comment]
@Carrotman42 
actually I havn't.. .
I enabled it, recreated credentials - just incase.. 
now I get the following error:

```
couldn't connect to "work-capital:us-central1:bank": ensure that the account has access to "xxxx:us-central1:myinstance" (and make sure there's no typo in that name). Error during createEphemeral for xxxxx:us-central1:myinstance: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```

**Comment by grahamfw** [comment]
I'm seeing the same issue with my instances. What should be the next steps?

**Comment by AthenaShi** [comment]
Actually I found in some of the cases there's an additional square bracket around the instance name in the pod command ran.  Please remove the bracket and try again.  Especially for the ones work with cloud_sql_proxy but not from the container.

If yours is not the case, then:

Please send an email with following information to cloud-sql@google.com so I may be able to help out looking at some internal data.
- with a link to this page, particular if you have left a message here, link to the message.
- describe the issue you have if the link doesn't cover all the details.
- the full name of your cloud sql instance.
- the command your run 
- the full logs

**Comment by hrdymchl** [comment]
Yup, me too - same error but getting it from local machine

**Comment by wieger** [comment]
It was indeed the extra square brackets in my case, thanks alot for pointing that one out!

**Comment by dcortesf** [comment]
I have exactly the same issue.
