### ISSUE TITLE
Consistency between "Proxy Library" and "Companion Process"

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/cloudsql-proxy#116]
Following along here:
https://cloud.google.com/sql/docs/mysql/connect-external-app#go

The "Companion Process" works well (using TCP sockets) *and* permits specifying the database name (!) when opening the connection to the instance:

```
const (
	databaseName       = "springdb"
	user               = "henry"
	password           = "hoops"
	proxyConnection    = "127.0.0.1:3306"
)
```
```
dsn := fmt.Sprintf("%s:%s@tcp(%s)/%s", user, password, proxyConnection, databaseName)
db, err := sql.Open("mysql", dsn)
```
It seems as though it should be straightforward to switch to using the Proxy library directly but the Dialer does not (appear to) permit spec'ing the databaseName during connection. Is the intended behavior to dial and then `"USE databaseName"`?:

```
db, err := mysql.DialPassword(instanceConnection, user, password)

if err != nil {
	log.Fatal(err)
}
defer db.Close()

_, err = db.Exec(fmt.Sprintf("USE %s", databaseName))
if err != nil {
	log.Fatal(err)
}
```

**Comment by DazWilkin** [comment]
Ah... using the Dialer and a `"use databaseName"' creates a subsequent issue if connections are replaced:

```
	fullNames := []string{
		"John Woo",
		"Jeff Dean",
		"Josh Bloch",
		"Josh Long"}

	stmt, err := db.Prepare("INSERT INTO customers(first_name, last_name) VALUES (?,?)")
	if err != nil {
		log.Fatal(err)
	}

	for _, fullName := range fullNames {
		name := strings.Split(fullName, " ")
		_, err := stmt.Query(name[0], name[1])
		if err != nil {
			log.Fatal(err)
		}
	}
```
This tends to get through 2 inserts before creating a new connection and then:

```
API server listening at: 127.0.0.1:32173
2017/08/18 10:38:51 Name: John Woo
2017/08/18 10:38:51 Name: Jeff Dean
2017/08/18 10:38:51 Error 1046: No database selected
```


Without boring anyone with details, I'm create a simplistic repro of this Spring sample in order to educate myself on the Go way and to help identify issues with the Spring sample:
https://spring.io/guides/gs/relational-data-access/

**Comment by Carrotman42** [comment]
Yeah, using the `USE database_name` command doesn't work well; unfortunately this is a known issue (at least to me) of the database/sql library. I would suggest using mysql.Cfg [0] function and manually modifying the DBName field [1] of the returned config.

[0] https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/8092e8660c0153f40b8632d0339e6a0f8c11c93d/proxy/dialers/mysql/hook.go#L69
[1] http://godoc.org/github.com/go-sql-driver/mysql#Config

**Comment by hfwang** [comment]
It looks like there's a known workaround, and not something that we can easily fix on the proxy side, so I'm closing this for now. Feel free to reopen if Carrotman42's suggestion doesn't work for you...
