### ISSUE TITLE
Unable to configure PostgreSQL dialer as a 'companion process'

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/cloudsql-proxy#117]
https://cloud.google.com/sql/docs/postgres/connect-external-app#go

Google's documentation incorrectly duplicates the MySQL configuration for the instructions on using PostgreSQL dialer as a 'companion process'.

When this issue is resolved, I'll file a bug against the Google documentation :-)

The PostgreSQL dialer works as a library referenced within code:

```
	dsn := fmt.Sprintf("host=%s user=%s dbname=%s password=%s sslmode=disable",
		instanceConnection,
		user,
		databaseName,
		password)
	db, err := sql.Open("cloudsqlpostgres", dsn)
```

It's unclear to me how this should be configured as a companion process.

I've tried Unix|TCP sockets:

```
./cloud_sql_proxy -instances=$INSTANCE -dir=/cloudsql
./cloud_sql_proxy -instances=$INSTANCE=tcp:5432
./cloud_sql_proxy -instances=$INSTANCE=tcp:0.0.0.0:5432
```
And:
```
	dsn := fmt.Sprintf("%s:%s@unix(/cloudsql/%s)/%s",
		user,
		password,
		instanceConnection,
		databaseName)
```
But I get:

```
2017/08/18 16:21:51 missing "=" after "$USER:$PASS@unix(/cloudsql/$INSTANCE)/$DATABASE" in connection info string"
```
And, if I just add "=" after the connection string:

```
2017/08/18 16:24:38 failed to parse addr: "localhost:5432". It should conform to the regular expression "^\\[(.+)\\]:[0-9]+$"
```
And, the same error if I add something that conforms to the source's (!?) actual RegEx == `^\[(.+)\]:[0-9]+$` specifically just duplicate the $INSTANCE (project:region:instance):

Stumped.

https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/dialers/postgres/hook.go

**Comment by Carrotman42** [comment]
Your dsn looks like the dsn for the MySQL driver used in Go examples. Every
driver has different dsn formats. What postgres driver are you using?
Please check the documentation for that driver for the dsn format.

I'd appreciate any updates of documentation that is not correct.

**Comment by DazWilkin** [comment]
I'm trying to connect to a Cloud SQL PostreSQL instance using the Google-provided Cloud SQL Proxy.

Google's documentation for PostgreSQL incorrectly duplicates the MySQL instructions:
https://cloud.google.com/sql/docs/postgres/connect-external-app#go

The first dsn I provided is for when the cloudsql-proxy is used as a library in Go code. This works.

The second dsn I provided is the only example I have (from the Google documentation) for using the cloudsql-proxy as a "companion process" (sidecar-like). Because I don't have any other documentation to use, I'm stumped as to whether:

-- I can use the cloudsql-proxy as a companion process for PostreSQL as I can for MySQL
-- how to configure the dsn in this case

**Comment by DazWilkin** [comment]
Sorry! I got it (finally). This is not proxy-specific, I just need to craft the dsn to use localhost and the examples I have look generic but must be MySQL-specific. Apologies!

**Comment by DazWilkin** [comment]
Solution: The dialer is not needed for companion use of the Cloud SQL Proxy.

Will have the documentation folks update Google's documentation to make this use clearer:

```
import (
	_ "github.com/lib/pq"
)
```

And then:

UNIX sockets -- NB host value is prefixed with "/" to indicate UNIX socket:
```
	dsn := fmt.Sprintf("host=/%s user=%s dbname=%s password=%s sslmode=disable",
		instanceConnection,
		user,
		databaseName,
		password)
```
TCP sockets -- host defaults to `localhost` and port defaults to `5432` so not specified:
```
	dsn := fmt.Sprintf("user=%s dbname=%s password=%s sslmode=disable",
		user,
		databaseName,
		password)
```
