### ISSUE TITLE
iam_login still does work for MySQL, not only ProgresSQL only as documented

### ISSUE THREAD

**Issue by Ptenten** [GoogleCloudPlatform/cloudsql-proxy#1196]
## Description
 ```
 -enable_iam_login
    Enables database user authentication using Cloud SQL's IAM DB Authentication (Postgres only).
```
this changes was introduced in #822 , is the config really meant to only usable if I using Google Cloud SQL (ProgresSQL)?
But i tested it using Google Cloud SQL (MySQL) it still work.
So its a documentation wrong?

## Solution
Remove the "ProgresSQL" since it work for other MySQL db

## Additional Context
Please reference any other relevant issues, PRs, descriptions, or screenshots here.
#822

**Comment by enocom** [comment]
Currently, MySQL supports only manual IAM authentication. When it does support automatic authentication, we'll make sure the update the docs.

**Comment by Ptenten** [comment]
hmm, but i tested it with a MySQL database that host by Google.
and I am able to use IAM authentication.

I added the IAM account into the database (not the built-in generated user sql account)
then using startup cloud proxy with   `-enable_iam_login` parameter
then startup HeidiSQL as my client, and capable to login using `Window Authentication`.

or am I actually misunderstood the setup? and done wrong actually?

**Comment by kurtisvg** [comment]
@Ptenten That is using your windows name/password to authenticate, and is different than IAM DB AuthN login. 

If you take a look at the [docs](https://cloud.google.com/sql/docs/postgres/authentication#options), you'll see the IAM database authentication has two options - automatic and manual. Postgres supports both, but MySQL only supports manual (for now).

**Comment by Ptenten** [comment]
@kurtisvg hi, sorry , there are still some part i confused about, hope you dont mind if i continue ask.
> That is using your windows name/password to authenticate

but its actually login using the IAM account that I added in google cloud? or i understood wrongly?

1. I meant, i created an IAM account at Google Cloud using
`ptenten@email.com` with the role of `Cloud SQL Client, Cloud SQL Instance User, Cloud SQL Viewer`

2. then I went to the Google Cloud SQL Database.
Select add a users, but when adding a user, i select `Cloud IAM` account (it show Built-in Authentication or Cloud IAM)
Notes: built-in authentication aren't used because it create a new user and it give superuser privileges, which I would like to avoid.

3. then I connect the Google Cloud SQL Database using this Cloud Proxy
```
cloud_sql_proxy_x64_v1.30.1.exe -enable_iam_login -instances=<instance_name>:127.0.0.1:3306
```

4. then in my local HeidiSQL connection, i just set it 127.0.0.1 with port 3306, then tick the window authentication which also named `ptenten`, and voila, i am now connected to the database, as this `ptenten` user in my google cloud.
Notes: its not connecting to any localhosted MySQL Server,  I mean I dont have any MySQL server installed in my pc, its just a proxy to connect to cloud sql.


from the result it look to me that its actually using IAM account to connect into the database, arent ?
or perhaps i actually mistaken the whole thing here?

**Comment by enocom** [comment]
Thanks for the detailed report, @Ptenten. I'm a little surprised this works. Let me check my own setup and comment back here.

In short, though, the official word is that automatic IAM AuthN is not currently supported for MySQL.

**Comment by enocom** [comment]
Here's what I did:

1. Added a service account user to my MySQL instance (which has the `cloud_sql_iam_authentication` flag set to on).
2. Started the Cloud SQL proxy using that service accounts key and with IAM AuthN enabled
3. Tried to log in with that service account user
4. Got an access denied error.

Meanwhile, if I try logging in with another test user (and password), the connection works.

So I'd double check your settings and try a separate user to see if you can find the issue in your setup.

**Comment by Ptenten** [comment]
@enocom are you perhaps using MySQL workbench? previously when I try with MySQL workbench, it didnt seem to work, it wont let me pass, not sure how to setup the authenticate using window that work like the HeidiSQL client did.

and I am not sure what else to check, because the steps provided above, is exactly the each steps i used to connect to my google cloud mysql instance using the IAM account, and yes it seem to work on my case.

**Comment by enocom** [comment]
I was using the MySQL CLI actually. What happens if you launch the proxy without the `enable_iam_login` flag? Does it fail?

**Comment by Ptenten** [comment]
> I was using the MySQL CLI actually. What happens if you launch the proxy without the `enable_iam_login` flag? Does it fail?

yeah, i wont be able to login without this `enable_iam_login` flag, it will showing the `Access denied for user ptenten@cloudsqlproxy~ipaddress' (using password: NO)`

**Comment by enocom** [comment]
Sorry for the slow response here. I don't understand how your setup is working. Officially this feature hasn't been released and shouldn't work. Once MySQL gets automatic IAM AuthN, I will update the README to make that clear. In the meantime, at least you can enjoy what looks like a convenient setup.

**Comment by Ptenten** [comment]
alright, thank you for the update.

**Comment by Ptenten** [comment]
not sure if it help, but just noticed I actually added this flag to the db also.
![image](https://user-images.githubusercontent.com/92089233/176401491-4c0a2058-d037-472f-883c-cb53df862af5.png)
