### ISSUE TITLE
Certificate refresh cycle does not work with laptop sleep

### ISSUE THREAD

**Issue by honDhan** [GoogleCloudPlatform/cloudsql-proxy#1199]
## Question
What is the best way to set up Cloud SQL Proxy on MacOS for local access to databases? This is so that our engineering team can securely connected to our databases.

I currently have things set up using `launchd` and `launchctl`.

## Additional Context

As mentioned, I have things set up with `launchd` on MacOS.

The issue is that sometimes, the proxy does not refresh the certificate. This happens when laptops go to sleep and wake up after the refresh time:
```
2022/05/11 09:14:08 Scheduling refresh of ephemeral certificate in 59m3.548513709s
2022/05/11 09:14:15 ephemeral certificate for instance OUR_DATABASE will expire soon, refreshing now.
2022/05/11 09:14:15 refreshing ephemeral certificate for instance OUR_DATABASE
2022/05/11 09:14:15 Scheduling refresh of ephemeral certificate in 59m3.678916417s
2022/05/11 10:49:50 New connection for "OUR_DATABASE"
2022/05/11 10:49:51 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:49:51 New connection for "OUR_DATABASE"
2022/05/11 10:49:51 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:49:51 New connection for "OUR_DATABASE"
2022/05/11 10:49:51 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:49:55 New connection for "OUR_DATABASE"
2022/05/11 10:49:56 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:50:01 New connection for "OUR_DATABASE"
2022/05/11 10:50:01 Reading data from OUR_DATABASE had error: remote error: tls: bad certificate
2022/05/11 10:54:16 ephemeral certificate for instance athelas-staging:us-central1:athelas-staging will expire soon, refreshing now.
2022/05/11 10:54:16 refreshing ephemeral certificate for instance athelas-staging:us-central1:athelas-staging
2022/05/11 10:54:17 Scheduling refresh of ephemeral certificate in 59m3.524621084s
2022/05/11 10:54:23 ephemeral certificate for instance OUR_DATABASE will expire soon, refreshing now.
2022/05/11 10:54:23 refreshing ephemeral certificate for instance OUR_DATABASE
2022/05/11 10:54:23 Scheduling refresh of ephemeral certificate in 59m3.670461042s
2022/05/11 10:56:27 New connection for "OUR_DATABASE"
```
Notice how there was a refresh scheduled for 10:14, but it did not go through.

A possible solution is to have the launchd service restart on sleep/wake, but that isn't a feature of launchd and I'd prefer not to do that. Is this an issue with the proxy, Go, or MacOS?

**Comment by enocom** [comment]
I'm not sure what I'd expect from Go. In effect, the CPU is asleep when the refresh goroutine should run. So when the CPU awakes, does the refresh goroutine run immediately, or is it dropped?

Here's the code in question:

https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/main/proxy/proxy/client.go#L238-L242

I'll need to test this out myself.

**Comment by enocom** [comment]
After playing around with this, I see the problem is that `time.After` will only run once the goroutine has observed so much time passing. When the computer goes to sleep, the clock also stops in effect. So this is probably a bug in our implementation.

**Comment by kurtisvg** [comment]
> After playing around with this, I see the problem is that `time.After` will only run once the goroutine has observed so much time passing. When the computer goes to sleep, the clock also stops in effect. So this is probably a bug in our implementation.

Is this is a bug with our implementation or in  Go?

**Comment by enocom** [comment]
When we say `time.After(duration)`, that duration only elapses if the computer is awake. So I assume we could alter our implementation such that we don't just wait a duration, but check if `now` is after the time we want to do a refresh. Based on my testing, though, Go is behaving in unusual ways. I'll update the thread here with more details.

**Comment by enocom** [comment]
But perhaps it is a bug in Go with time.After -- the question is does Go make any claims about an elapsed duration when the CPU is asleep for part of it?

**Comment by enocom** [comment]
From the [docs on time](https://pkg.go.dev/time):

> On some systems the monotonic clock will stop if the computer goes to sleep. On such a system, t.Sub(u) may not accurately reflect the actual time that passed between t and u.

This might just be a limitation of the hardware Go is running on. If the monotonic clock stops when the computer goes to sleep, I'm not sure what we could do here.

**Comment by honDhan** [comment]
> check if now is after the time we want to do a refresh

I think this would be a valid workaround.

Another solution I was thinking of was having a flag to lower the refresh time for certs. e.g. if a refresh is scheduled for every 20-30 minutes, the time between (laptop waking up)<->(needing to connect to db) is lower

**Comment by honDhan** [comment]
> This might just be a limitation of the hardware Go is running on. If the monotonic clock stops when the computer goes to sleep, I'm not sure what we could do here.

Probably the issue. Our eng team uses M1 macs, so I'm not surprised it's causing an issue.

**Comment by honDhan** [comment]
Right now, I'm telling folks to restart the service running the proxy every time they run into an issue. If you think this is the best solution, we can close this.

**Comment by honDhan** [comment]
Perhaps giving the refresh a `context` with a wall clock based deadline?
something like:
```go
func (c *Client) refreshCertAfter(instance string, timeToRefresh time.Duration, ctx Context) {

        select {
        case <-ctx.Done(): // potentially wall clock based?
	case <-time.After(timeToRefresh): // retain monotonic clock functionality
        }

```

**Comment by honDhan** [comment]
did some digging, seems like this is an accepted proposal for Go: https://github.com/golang/go/issues/36141

**Comment by enocom** [comment]
Nice find! I'm curious to explore what implementation options we have in the meantime.

**Comment by kurtisvg** [comment]
@honDhan Do you know what version of the proxy you are using?

Looking at head, I suspect this might already be fixed since we check the cert expiration here: https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/49d3003c018afdc0cde54340d5be808f9dcd5c84/proxy/proxy/client.go#L380

and here: 
https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/49d3003c018afdc0cde54340d5be808f9dcd5c84/proxy/proxy/client.go#L423-L426

**Comment by enocom** [comment]
I tested the latest version of the proxy, and see that this issue persists. In short, after waking from sleep, the proxy doesn't know to immediately refresh the certificate.

I have a possible fix and will send a PR for discussion.

**Comment by enocom** [comment]
@honDhan I did some testing with my patch and believe my PR fixes the issue. We'll be releasing this on the first Tuesday of next month as part of the usual release cadence, but if you'd like to try a dev build off of main, I'd be curious to hear if you see an improvement.

**Comment by enocom** [comment]
@honDhan Circling back to this -- I wonder if you've seen any improvement with this fix in [v1.13.1](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases/tag/v1.31.1)?

**Comment by honDhan** [comment]
Hey! Sorry for the lack of response. I am using .32.1 and it's been going well so far. No complaints from team members either. Thank you so much!

**Comment by enocom** [comment]
Fantastic. Thanks for the update!
