### ISSUE TITLE
Upgrade macOS Github Actions runner from macos-10.15 to macos-latest

### ISSUE THREAD

**Issue by jackwotherspoon** [GoogleCloudPlatform/cloudsql-proxy#1225]
`macos-10.15` runner is catalina and can install `osxfuse` without having to restart the kernel. Where as `macos-latest` is Big Sur and can't  install `osxfuse` without requiring restart of the kernel.

Need to look into ways of using `osxfuse` or `macfuse` within github action builds that use `macos-latest` runner.

**Comment by enocom** [comment]
Related:
- https://github.com/actions/virtual-environments/issues/598
- https://github.com/actions/virtual-environments/issues/4731

**Comment by jackwotherspoon** [comment]
Seems like macOS-11 has tightened its ability around using [kernel extensions](https://support.apple.com/en-ca/guide/deployment/depa5fb8376f/web), making it currently not possible to install `macfuse` in the appropriate way on a github-hosted runner. (i.e. you can not restart the macOS runner in Reduced Security mode)
