### ISSUE TITLE
Latest is 1.09?

### ISSUE THREAD

**Issue by danqing** [GoogleCloudPlatform/cloudsql-proxy#125]
Hello,

Latest docker image is pinned at 1.09. Are 1.10/1.11 not stable, or is it that we shouldn't use the latest tag?

https://console.cloud.google.com/gcr/images/cloudsql-docker/GLOBAL/gce-proxy?gcrImageListquery=%255B%255D&gcrImageListpage=%257B%2522t%2522%253A%2522%2522%252C%2522i%2522%253A0%257D&gcrImageListsize=50&gcrImageListsort=%255B%257B%2522p%2522%253A%2522uploaded%2522%252C%2522s%2522%253Afalse%257D%255D

Thanks!

**Comment by Carrotman42** [comment]
You shouldn't use the "latest" tag, at least not in production. (You should
instead upgrade the version explicitly with your own rollout procedure to
ensure any potential bugs in the new version don't break you.) But people
use "latest" in production anyway. To prevent us from breaking people's
production when a new version is released, we only update "latest"
periodically when we are sure there aren't breaking changes with the
version.

1.10 is probably fine to be set to latest. 1.11 is too new (imo).

**Comment by danqing** [comment]
Fair enough.
