### ISSUE TITLE
Connection to CloudSQL works in all scenarios except via socket in Docker container

### ISSUE THREAD

**Issue by wesnolte** [GoogleCloudPlatform/cloudsql-proxy#129]
Hopefully I'm doing something wrong, I've read all documentation and scoured forums but can't seem to get to the bottom of an issue I'm experiencing. I'm using OSX btw.

Things that are working:

1. Connect to cloud SQL from local OS using proxy via either TCP or Socket
2. Connect to cloud SQL from local OS using proxy in container via TCP
3. Connect to cloud SQL from GKE using proxy in the same pod via TCP

Things that are not working:

1. Connect to cloud SQL from local OS using proxy in contain via sockets
2. Connect to cloud SQL from GKE using proxy in the same pod via socket

I suspect both of these problems are actually the same problem. I'm using this command to run the proxy inside of the container:

`docker run -v [PATH]:/cloudsql \
  gcr.io/cloudsql-docker/gce-proxy /cloud_sql_proxy -dir=/cloudsql \
  -instances=[INSTANCE_CONNECTION_NAME] -credential_file=/cloudsql/[FILE].json`

And the associated socket is being generated with the directory. However when I attempt to connect I get the following error:

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/cloudsql/node-sql:us-central1:nodedb' (61)`

The proxy doesn't generate a new line  when I try to connect which makes me think that it's not receiving the request, it simply says "Ready for new connections" and waits.

Any idea what's going wrong, or how I could troubleshoot this further?

**Comment by AthenaShi** [comment]
Please follow this instruction:
https://cloud.google.com/sql/docs/mysql/connect-docker ("9. Start the proxy.")
for the command to connection in container via unix sockets.  Particularly:
```
docker run -d -v /cloudsql:/cloudsql \
  -v [PATH_TO_KEY_FILE]:/config \
  gcr.io/cloudsql-docker/gce-proxy /cloud_sql_proxy -dir=/cloudsql \
  -instances=[INSTANCE_CONNECTION_NAME] -credential_file=/config
```

**Comment by AthenaShi** [comment]
Closing due to lack of updates.  Feel free to reopen this if there's still an issue.

**Comment by bborysenko** [comment]
I have encountered with the same  issue. But it's more likely linked to https://github.com/docker/for-mac/issues/483. 

Inside docker container connection through socket is working:

```
➜  ~ docker exec -it cloud-sql sh
/ # apk add --no-cache mysql-client
/ # mysql -u root -p -S /cloudsql/xxx\:europe-west3\:xxx
Server version: 5.6.36-google (Google)
MySQL [(none)]>
```
