### ISSUE TITLE
Update download_proxy.sh to download correct architecture for the target system.

### ISSUE THREAD

**Issue by davidn** [GoogleCloudPlatform/cloudsql-proxy#130]
download_proxy.sh is hard-coded to fetch an amd64 binary. If users attempt to use this script from other architectures, they will get a binary they cannot use. This happened for [this ARM user](https://stackoverflow.com/q/46916674).

Can we add 32bit x86 and ARM builds, and have download_proxy.sh fetch the correct one for the local system?

**Comment by hfwang** [comment]
@davidn I know it's a bit late... but I think you linked to the wrong stackoverflow post?

**Comment by davidn** [comment]
I think I meant https://stackoverflow.com/q/47267097.

**Comment by kurtisvg** [comment]
We remove download_proxy.sh, so this is no longer an issue.
