### ISSUE TITLE
GKE unable to connect to Cloud SQL using SQL Proxy via sidecar pod pattern

### ISSUE THREAD

**Issue by sursani** [GoogleCloudPlatform/cloudsql-proxy#132]
Hello,
I am using this guide to connect GKE to Cloud SQL (postgres) using the sidecar pod pattern:
https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine

I have not had any success thus far. Whenever my app does try to connect from GKE to Cloud SQL, I see this in the Cloud SQL logs:

> LOG: could not receive data from client: Connection reset by peer 

My application (.NET Core 2.0 webapi) running inside a GKE pod shows the following exception in its logs:

> System.IO.IOException: Unable to transfer data on the transport connection:
Connection reset by peer.

I made sure that all the database credentials are correct in my K8s deployment manifest yml file.

Any clues to what the issue could be?

Thanks

**Comment by bbhoss** [comment]
I'm seeing this as well from Python. I believe it's related to the SSL certificates instructions being wrong, or Google changing something on the `cos` image.  I am seeing many lines of this in the logs:
```
2018/01/05 19:21:04 couldn't connect to "mydb": Post https://www.googleapis.com/sql/v1beta4/projects//instances/myinstance/createEphemeral?alt=json: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: x509: failed to load system roots and no roots provided
```

**Comment by bbhoss** [comment]
I figured this out, it looks like the guide tells you to mount /etc/ssl from the host into /etc/ssl/certs, which is wrong, as certs is already in /etc/ssl

**Comment by ahmetb** [comment]
Thanks for reporting. Unfortunately many things could go wrong in Cloud SQL setup with GKE, and .NET Core is probably adding a bit more to that complexity. I'll recommend the following troubleshoot steps:

Have you been able to run the sample mysql+wordpress example at https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine ? 

If you can get it to work, from there you can perhaps change PostgreSQL with MySQL, and then swap wordpress with an image that has postgres CLI, verify postgres CLI can connect to the sidecar, and then finally you can swap the main container with the main .NET Core application you're using.
