### ISSUE TITLE
cannot fetch token: Post https://accounts.google.com/o/oauth2/token:  dial tcp: lookup accounts.google.com

### ISSUE THREAD

**Issue by adawolfs** [GoogleCloudPlatform/cloudsql-proxy#136]
Hello I'm configuring an Openshift Cluster but I had this error, I cant connect my instance to the cloudsql database, the same configuration is used for GKE and its working, and if mount the instance over minishift it worked, can you please help me to know what is happening here? 

  | 2017/12/21 20:44:45 Listening on 127.0.0.1:3306 for myinstance:europe-west1:cloudsql-dev-1
  | 2017/12/21 20:44:45 Ready for new connections
  | 2017/12/21 20:44:47 New connection for "myinstance:europe-west1:cloudsql-dev-1"
  | 2017/12/21 20:44:47 couldn't connect to "myinstance:europe-west1:cloudsql-dev-1": Post https://www.googleapis.com/sql/v1beta4/projects/myinstance/instances/cloudsql-dev-1/createEphemeral?alt=json:  oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token:  dial tcp: lookup accounts.google.com on 138.201.198.48:53: server misbehaving

**Comment by AthenaShi** [comment]
This means the DNS-server can't resolve "accounts.google.com". (Port 53 is the DNS.)  Normally the fix would be check your local DNS-server or replace it for a public server, example, 8.8.8.8 or 8.8.4.4, etc.

I'm not familiar with Openshift and how to fix this. I found this link: https://docs.openshift.org/latest/install_config/install/prerequisites.html (search for "/etc/resolv.conf") and hope it's useful.

**Comment by adawolfs** [comment]
Thanks for your reply! I'll test the networking...

**Comment by hfwang** [comment]
I hope your problem was resolved. Closing for now, but re-open if you continue to have issues.
