### ISSUE TITLE
Raspbian cloudsql-proxy cannot execute binary file : format error

### ISSUE THREAD

**Issue by reno184** [GoogleCloudPlatform/cloudsql-proxy#140]
Hi,

when I try ./cloud_sql_proxy -instances=<XXX>=tcp:3306  on my raspberry pi3 with raspbian, I get this error ?

./cloud_sql_proxy cannot execute binary file : format error

I try with download with 64and32 version and same problem

wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 -O cloud_sql_proxy
or
wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
chmod +x cloud_sql_proxy

I don't understand because It's work fine on my mac...

many thanks

**Comment by Carrotman42** [comment]
The raspberry pi uses a different CPU than your mac (arm vs x86). There's
no pre-compiled version for arm right now unfortunately but you should be
able to compile it yourself using the "go get" command on the README.

**Comment by reno184** [comment]
ok many thanks !!!
