### ISSUE TITLE
'cloud_sql_proxy.exe' is not recognized as an internal command

### ISSUE THREAD

**Issue by edivaldodelgado** [GoogleCloudPlatform/cloudsql-proxy#141]
Hey Guys,

I've installed the 'cloud_sql_proxy.exe' using the .exe install method, not worked.

I tried the the "GO Method" - [cmd go install](https://github.com/GoogleCloudPlatform/cloudsql-proxy), not worked

Everytime I receive this message, in fact, once it worked using "GO Method", I was able to upload a sample to Google App Engine. Then I tried to do for a real project and got the message: 'cloud_sql_proxy.exe' is not recognized as an internal command.

Need some help.

**Comment by hfwang** [comment]
Are you trying to access Cloud SQL via GAE? There is special support, see the docs:

https://cloud.google.com/sql/docs/mysql/connect-app-engine

**Comment by mingfengwan** [comment]
I am having the same error, and the guide does not help :(

**Comment by manzanofab** [comment]
yeah, the guide is the worst of the worst!
