### ISSUE TITLE
Cloudsql-Proxy in Kubernetes for cluster PostgreSQL

### ISSUE THREAD

**Issue by Tedezed** [GoogleCloudPlatform/cloudsql-proxy#144]
Hi!

I need to configure the proxy to attack to Postgres cluster, this has read and read-write nodes. Would the proxy support this configuration? Or you should deploy a proxy that manages this, such as [crunchy-proxy](https://github.com/CrunchyData/crunchy-proxy)

Example diagrams:

**Cloudsql-Proxy managing read and read-write**

![Cloudsql-Proxy managing read and read-write](https://image.ibb.co/dtHJGw/Diagram1.png)

**Crunchy-Poxy managing read and read-write and use Cloudsql-Proxy to connect with Google SQL**

![Crunchy-Poxy managing read and read-write and use Cloudsql-Proxy to connect with Google SQL](https://image.ibb.co/kEsUOb/Diagram2.png)

THX!

**Comment by AthenaShi** [comment]
For graph one, do you need a LB that will automatic route to the master or the replica?

If yes, then current proxy doesn't support this, go for graph two.

If you just want one proxy to be able to setup the connection to both of the master and replica, and have the "Web Application" control which one to talk to, then graph one is supported.

**Comment by Tedezed** [comment]
Hi,

The solution that I take in my case is, deploy pgpool for sql management and set as master node and slave two cloudsql-proxy pointing to different set of servers.

Pgpool managing read and read-write and use Cloudsql-Proxy to connect with Google SQL.

THX!

**Comment by Tedezed** [comment]
https://issuetracker.google.com/issues/37271935
