### ISSUE TITLE
Cleanup Logging Levels

### ISSUE THREAD

**Issue by evmin** [GoogleCloudPlatform/cloudsql-proxy#149]
As a system administrator who runs SQL Proxy on GCE, I would like to be able to define the log level for the proxy explicitly - I am only interested in ERRORS and above.

I understand that at present there are only three options:

- Default   : Errors and Info
- Verbose : Debug
- Quiet : Nothing.

Would be great to have an "ERROR-only" option.

**Comment by Carrotman42** [comment]
Note that the default is verbose=true (https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/025b8c3/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L52)

If you set debug=false, the only log messages which will be printed out is:
   1) A small number of lines during proxy startup
   2) Any error-level logs which occur

So, is it OK for you to get logs from both 1 and 2 above? If so, I think you just want to set `--verbose=false` when starting the cloudsql-proxy. If you want just the error-level logs and can't handle any of the startup logs, then feel free to send in a PR for it.

**Comment by Carrotman42** [comment]
(or wait for PR #150 which might also help you)

**Comment by kurtisvg** [comment]
Closing this - PR #150 adds functionally to address this issue.
