### ISSUE TITLE
Cloudsql proxy error: too many open files

### ISSUE THREAD

**Issue by jordipolo87** [GoogleCloudPlatform/cloudsql-proxy#151]
Hi guys,

I'm running the cloudsql-proxy in a compute engine instance and I'm encountering an issue when I have a lot of traffic on the server. The proxy logs an error message and stop working.

Here you have the logs:
2018/03/06 18:49:07 Error in accept for {"my-project:europe-west1:my-project-mysql-server" "unix" "/cloudsql/my-project:europe-west1:my-project-mysql-server"} on /cloudsql/my-project:europe-west1:my-project-mysql-server: accept unix /cloudsql/my-project:europe-west1:my-project-mysql-server: accept4: too many open files
2018/03/06 18:49:07 couldn't connect to "my-project:europe-west1:my-project-mysql-server": Post https://www.googleapis.com/sql/v1beta4/projects/my-project/instances/my-project-mysql-server/createEphemeral?alt=json: dial tcp: lookup www.googleapis.com on 169.254.169.254:53: dial udp 169.254.169.254:53: socket: too many open files
2018/03/06 18:49:07 Throttling refreshCfg(my-project:europe-west1:my-project-mysql-server): it was only called 45.684µs ago
2018/03/06 18:49:07 couldn't connect to "my-project:europe-west1:my-project-mysql-server": Post https://www.googleapis.com/sql/v1beta4/projects/my-project/instances/my-project-mysql-server/createEphemeral?alt=json: dial tcp: lookup www.googleapis.com on 169.254.169.254:53: dial udp 169.254.169.254:53: socket: too many open files

This issue is quiet similar: https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/58

Thank you in advance! :)

**Comment by Carrotman42** [comment]
That error is just a Linux error saying that your process has too many fds
open. There are tutorials online about how to increase the limit for a
process.

I'm curious - what's your current fd limit? I'm kind of surprised about
this error, I'd guess that it requires a lot of concurrent connections.

**Comment by jordipolo87** [comment]
Thank you for your responses guys.

We had already changed the default file descriptors limit inside /etc/security/limits.conf but it seems that the sqlproxy process still had the 1024 default file descriptors limit.

In order to solve the problem we are currently changing the sqlproxy process file descriptor limit with the prlimit function on the startup script: 
pid=$(pidof cloud_sql_proxy)
prlimit --pid $pid --nofile=64000:64000  

@jiaweizhang we haven't tested your suggested solution of changing the  /etc/sysctl.conf file maybe it works too, we will test it in the future (I don't like very much our current solution).

Thank you again! :)
