### ISSUE TITLE
Connect app with the clousSQL Proxy Container, running in separate namespaces.

### ISSUE THREAD

**Issue by linux17kartik** [GoogleCloudPlatform/cloudsql-proxy#156]
Hello,

Please go through the scenario :

Aim : I want to "my-app" running in namespace "my-app", communicate with the CloudSQL instance  through , cloud proxy container running in name space "db".

1. name space=db : in this  proxy container is running for Cloud SQL instance

logs form mysql Proxy container :

2018/03/30 08:56:28 using credential file for authentication; email=mysql-service-account
2018/03/30 08:56:28 Listening on 0.0.0.0.1:3306 for jenkins-196609:us-central1:mysql-test1
2018/03/30 08:56:28 Ready for new connections

2. name space=my-app : in this app container is runnign.

Logs from the my-app container:
&gt; docker_web_app@1.0.0 start /usr/src/app
&gt; node server.js
Running on http://:80
{ Error: connect ETIMEDOUT
at Connection._handleConnectTimeout (/usr/src/app/node_modules/mysql/lib/Connection.js:419:13)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:106:13)
at Socket.emit (events.js:208:7)
at Socket._onTimeout (net.js:420:8)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)
--------------------
at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
at Protocol.handshake (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:52:23)
at Connection.connect (/usr/src/app/node_modules/mysql/lib/Connection.js:130:18)
at Object.&lt;anonymous&gt; (/usr/src/app/server.js:14:12)
at Module._compile (module.js:652:30)

Please help he how can I achieve this.

Regards
Kartik

**Comment by KrustyHack** [comment]
Ay,

Which MYSQL hostname do you use in your app config ?

Like that : SERVICE_NAME.NAMESPACE ?

Example : 

```
root@Unknown:~/# k exec -n test -it mysql-test-6d87459d9b-ddft6 -- mysql -h sqlproxy-gcloud-sqlproxy.sqlproxy -u USER -pPASSWORD
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.

[...]

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

Where `sqlproxy-gcloud-sqlproxy` is my service name and `sqlproxy` is my namespace for my gcloud sqlproxy deployment.

And `test` is my application's namespace.

And I don't think that `Listening on 0.0.0.0.1:3306` is a correct address for listening. On my side I got `0.0.0.0:3306`:

```
2018/04/04 13:55:47 using credential file for authentication; email=krusty@unkown.com
2018/04/04 13:55:48 Listening on 0.0.0.0:3306 for PROJECT:ZONE:INSTANCE
2018/04/04 13:55:48 Ready for new connections
```

**Comment by linux17kartik** [comment]
thank you for you response!!
issue has been resolved .
Through Google cloud resources..
