### ISSUE TITLE
Improve error message when gcloud path missing

### ISSUE THREAD

**Issue by chrisjensen** [GoogleCloudPlatform/cloudsql-proxy#157]
I had some trouble running the proxy in Grunt scripts and on CircleCI, eventually figured out that it was because the `PATH` environment variable was missing or didn't contain the google-cloud-sdk/bin directory.

The error is pretty cryptic, it would be helpful if it were more explicit.

**To reproduce**
1. Verify cloud_sql_proxy is working:

`./cloud_sql_proxy -dir=/cloudsql`

You should get output like

```
2018/04/14 20:38:48 Using gcloud's active project: your-project-12345
2018/04/14 20:38:53 Listening on /cloudsql/your-project-12345:us-central1:your-db/.s.PGSQL.5432 for your-project-12345:us-central1:your-db
2018/04/14 20:38:53 Ready for new connections
```

2. Rerun with google-cloud-sdk removed from path

`PATH=/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin ./cloud_sql_proxy -dir=/cloudsql`

Outputs
```
2018/04/14 20:38:31 must specify -projects, -fuse, or -instances
```

**Expected Behaviour**
When the google-cloud-sdk is missing from the path, it should give a friendlier message, like, say

```
2018/04/14 20:38:31 Cannot find google-cloud-sdk/bin, please ensure it is in the PATH
```

**Comment by Carrotman42** [comment]
I think the error you suggest inplies there's a problem that must be solved via installing gcloud. I would prefer to not point people towards that as the only solution, and to possibly include both messages.

Note, of course, that specifying instances vvia --instances is the supported and suggested configuration for production. Relying on the cloud sdk to be installed for production purposes should not be needed in general.

**Comment by chrisjensen** [comment]
then perhaps appending the message with `(-dir and -projects options are not recommended in production environments)`?

The documentation [here](https://cloud.google.com/sql/docs/mysql/sql-proxy#instances-options) also lists `-projects` as not recommended for production - which would imply to someone trying to debug that using that flag in a production environment is not the issue since the error message is recommending another flag also not recommended for production.

**Comment by Carrotman42** [comment]
IMO we should try to avoid making the error messages too specific - how
could we know someone is running in production as opposed to development?
What are the chances of confusing a new user with that information, which
is clearly geared toward users who know a bit more jargon? And, in my
experience, the longer errors/log messages are, the less likely people are
to read them. It's a tricky ballance.

**Comment by chrisjensen** [comment]
I was a new user at the time I received the existing error, and it was confusing.

I read the existing error and went "what's going on? those flags weren't needed in development, and -dir is supposed to be used in place of those. Is -dir not allowed in production? Well, it's not recommended, but then so is -projects, so surely the error isn't telling me to substitute one non-recommended flag for another."

Can you see how that error in that context is confusing?

After a good deal of googling I eventually found out that it was because it couldn't find gcloud.

How about this:
`google-cloud-sdk/bin must be installed to use the -dir option, please ensure it is in the PATH`

**Comment by Carrotman42** [comment]
If you are using Unix sockets as opposed to TCP on the local host, the -dir flag is required no matter what other flags you pass. Maybe I misunderstood your last post?

In any case, other than the use of global variables, I think the PR used to close this is good: it has both of what we want (I think), in that it tells you about flags you could use, and then also mentions than gcloud is missing.

If the PR doesn't address the concerns of this issue, please reopen and we'll all figure something out!

**Comment by chrisjensen** [comment]
Ah, I missed that there was a patch for this. Yes that's a helpful message. Thanks
