### ISSUE TITLE
Feature Request: Specifying external Credentials when using the proxy as a library (in Golang)

### ISSUE THREAD

**Issue by benfdking** [GoogleCloudPlatform/cloudsql-proxy#159]
When using this repository as a go-library, there is no way of specifying the credential file path. So struggling to integrate the library into a Golang Cobra CLI tool.

Just realised that the path can be set using `GOOGLE_APPLICATION_CREDENTIALS` but I still think it would be nice to have a way to do it in code. So one  can build a CLI tool

**Comment by hfwang** [comment]
Yes, `GOOGLE_APPLICATION_CREDENTIALS` is the way to go. I would prefer to guide users of the library to use the default credential method so that consumers of the CLI tool don't need to in turn ask for a different way to override the default credential source.

How do you intend users of a CLI tool to specify the credential path when they use the CLI? Is there a reason the env variable is unsuitable?

**Comment by Carrotman42** [comment]
The library just enables a hook with the mysql library (https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/8092e86/proxy/dialers/mysql/hook.go#L30) which calls `proxy.Dial` (https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/e4765da/proxy/proxy/dial.go#L39) which explicitly tells you:

   If one of the Init functions hasn't been called yet, InitDefault is called.

So, just call `proxy.Init` or the like: https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/e4765da/proxy/proxy/dial.go#L70

**Comment by enocom** [comment]
To summarize in code what @Carrotman42 suggested, here is one possible approach to using external credentials.

This code creates a custom HTTP client with external credentials, initializes a DB connection, and then queries for the current time.

``` go
package main

import (
    "context"
    "fmt"
    "log"

    "github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy"
    "google.golang.org/api/option"
    trhttp "google.golang.org/api/transport/http"

    "github.com/enocom/mycoolmodule/storage"
)

func main() {
    httpClient, _, err := trhttp.NewClient(
        context.Background(),
        option.WithCredentialsFile("key.json"), // <--- custom credentials here
        option.WithScopes("https://www.googleapis.com/auth/sqlservice.admin"), // <--- with a SQL Admin scope
    )
    if err != nil {
        log.Printf("Failed to create HTTP Client: %v", err)
    }
    proxy.Init(httpClient, nil, nil) // <--- using the custom client here

    db, err := storage.InitDB() // <--- initializing the DB in a separate package to register the SQL driver
    if err != nil {
        log.Fatal(err)
    }
    defer db.Close()

    rows, err := db.Query("select NOW()")
    if err != nil {
        log.Fatal(err)
    }
    defer rows.Close()

    var t string
    for rows.Next() {
        rows.Scan(&t)
        fmt.Println(t)
    }
}
```

The separate package to initialize the DB and register the driver looks like this:

``` go
package storage

import (
    "database/sql"
    "fmt"

    _ "github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/postgres"
)

func InitDB() (*sql.DB, error) {
    return sql.Open("cloudsqlpostgres",
        fmt.Sprintf(
            "host=%s dbname=%s user=%s password=%s sslmode=disable",
            "project:region:db-instance-name",
            "db-name",
            "db-user",
            "db-password",
        ),
    )
}
```
