### ISSUE TITLE
Connection refused to proxy

### ISSUE THREAD

**Issue by alexxxPopa** [GoogleCloudPlatform/cloudsql-proxy#162]
Hello, i am pretty new to gcloud and kubernetes.That being said i am trying to connect to a postgresql db using cloudsql-proxy.
I've been using the steps found here : 
https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine
When i am deploying to kubernetes, the cloudsql-proxy pod can't find the credential file used.
"2018/04/27 11:46:23 invalid json file "/secrets/cloudsql/credentials.json": open /secrets/cloudsql/credentials.json: no such file or directory".
Any help is more than welcomed, thank you.

**Comment by alexxxPopa** [comment]
I manage to figure it out, apparently the application was trying to access the proxy before it was ready to be accessed

**Comment by jimenezjrs** [comment]
@alexxxPopa can you give more details on how you solved it? 

If the issue is that the app is trying to access the proxy before it is ready. How do you tell it to access it when it is ready?

**Comment by alexxxPopa** [comment]
@jimenezjrs  hi, well right now i just used a wait in my backend application, and a 30 sec wait did the job.There are scripts that are used for this exact use case, there is also initContainers in Kubernetes that should initialize containers in order but so far i haven't been able to use them in the deployment config file; i am pretty newbie at kubernetes.If I manage to solve this from scripts i' ll post my configuration file.
