### ISSUE TITLE
An error in Accept() will cause the proxy to close the main socket and never reopen.

### ISSUE THREAD

**Issue by ibawt** [GoogleCloudPlatform/cloudsql-proxy#163]
## Bug
If you get an error returned form ln.Accept() here: 
https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/cmd/cloud_sql_proxy/proxy.go#L144

Something like ENOMEM returned from the syscall, the proxy will happily close the connection and never re-open it.

## Desired Behaviour
Either crash completley, so the system around it can restart it, or make the watch loop watch the static connections as well.

## Example
example of the error so you know I'm not crazy:

"018/05/02 13:13:13 Error in accept for {"*********************" "tcp" "0.0.0.0:3306"} on 0.0.0.0:3306: accept tcp [::]:3306: cannot allocate memory"

The actual container had lots of extra memory.

Kind of smells like somaxconn .  

## Our resolution

We fixed it by using a livenessProbe on the container to see if it's still listening.  I still think it's a pretty bad bug though.

I can fix it but it would require some large refactoring.

**Comment by easwars** [comment]
Does this pull request not address your issue?
https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/148
