### ISSUE TITLE
How to define multiple credential.json files?

### ISSUE THREAD

**Issue by redradrat** [GoogleCloudPlatform/cloudsql-proxy#167]
My use case:
I want to connect to multiple DBs running in different gcloud projects:
```
-instances=proj1:europe-west3:db=tcp:0.0.0.0:5432,proj2:europe-west3:db=tcp:0.0.0.0:5433
```
I'm only allowed to specify 1 credentials file (with -credential_file) and an array in the json throws a parsing error.
```
json: cannot unmarshal array into Go value of type google.credentialsFile
```
 Is there a possibility to define multiple service accounts or am I maybe thinking in the wrong direction? :)

**Comment by kurtisvg** [comment]
@redradrat You should be able to share a service account between multiple projects. Once you have the service account set up in one project, switch to the second project and on the IAM page add the service account via it's email.

**Comment by redradrat** [comment]
Thx.
