### ISSUE TITLE
Cloud SQL proxy causes significant additional latency

### ISSUE THREAD

**Issue by MrMage** [GoogleCloudPlatform/cloudsql-proxy#168]
(This may be a duplicate and/or related to #87.)

I've been experimenting with using Cloud SQL Proxy for my PostgreSQL database vs. connecting directly via TCP. To illustrate, here's my Stackdriver Trace latency graph:

<img width="823" alt="screen shot 2018-05-27 at 20 22 32" src="https://user-images.githubusercontent.com/117466/40589369-4b386c46-61ec-11e8-8518-95e17e23130c.png">

Around 18:15 I switched from directly connecting via TCP from GKE to Cloud SQL over to using a Cloud SQL proxy sidecar that my service connects to via a Unix socket (connecting to the proxy via TCP yields very similar results). As one can see, there are a few spikes in latency when the connection pools get warmed up, and then the latency distribution is significantly above the latency before, which was for direct connections.

My Stackdriver Trace spans also indicate that the increase in overall latency can be attributed to an increase in database call latency. Trivial database calls that normally take <=10ms via a direct connection take up to 100ms through the proxy.

Is this expected, can I do anything about it, and, if there is no remedy, what would be the best way to connect to the DB via TCP from GKE? I'm currently using a /16 netmask to allow connections grom GCE, but that's probably bad for production. Also, I'm not sure whether direct traffic to Cloud SQL is encrypted — if you could provide insights into that, that would be appreciated.

FYI, the GKE cluster and the Cloud SQL database are located in the same zone (europe-west3-a IIRC). The database is only ~500 MB right now (fits completely into memory and has appropriate indexes) and has low load. Also, as stated above, I am using connection pooling and have confirmed that that works.

**Comment by MrMage** [comment]
Hi, I checked again and it seems like removing my Pods‘ Kubernetes CPU Limits has indeed resolve die the issue. So the issue was not due to connection pooling, but not due to Cloud SWL Proxy, either.

**Comment by monotek** [comment]
might be related too: https://github.com/kubernetes/kubernetes/issues/67577

looking at the kernel version in the cos image the available fix should have been backported...
