### ISSUE TITLE
Unix sockets documentation for postgres is incorrect (with psql 9.6)

### ISSUE THREAD

**Issue by aawilson** [GoogleCloudPlatform/cloudsql-proxy#170]
In the documentation at https://cloud.google.com/sql/docs/postgres/connect-compute-engine, it lists the psql command for testing the proxy setup over Unix sockets as `psql "sslmode=disable host=/cloudsql/<INSTANCE_CONNECTION_NAME> user=<USERNAME>"`. However, the psql host command, when it is file-like rather than URL-like, is assumed to be a _directory_ of sockets, not an actual socket. The resulting error is something like

```
user@somehost:~$ psql "sslmode=disable host=/cloudsql/some-project:some-region:some-db user=someuser"
psql: could not connect to server: Not a directory
        Is the server running locally and accepting
        connections on Unix domain socket "/cloudsql/some-project:some-region:some-db/.s.PGSQL.5432"?
```

As far as I can tell, the only way to connect using cloudsql-proxy via psql is to force the AF_UNIX socket name to conform to the PGSQL format/extension with some hacky baloney on the cloudsql-proxy side, or use AF_INET sockets, unless I'm missing some option in the psql manpage that someone could smack me in the head with.

**Comment by kurtisvg** [comment]
@aawilson Can you confirm what command you are using to start the Cloud SQL Proxy? The Cloud SQL proxy does create a directory, and I have no problems connecting following the instructions listed in the documentation.

The command I'm using to start the Cloud SQL Proxy:
`./cloud_sql_proxy -instances=<INSTANCE_CONNECTION_NAME> -dir=/cloudsql -credential_file=service_account_key.json`

The command I'm using to connect with psql:
`psql "sslmode=disable host=/cloudsql/<INSTANCE_CONNECTION_NAME> user=<USERNAME>"`

**Comment by hfwang** [comment]
We have special handling for postgres sockets, see https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/679c7d53431e25e594f963dfb472f96320668d00/cmd/cloud_sql_proxy/proxy.go#L265

I think if you update your verison of the proxy client, the problem will go away...
