### ISSUE TITLE
constructors for *mysql.Config should call mysql.NewConfig() first for appropriate defaults

### ISSUE THREAD

**Issue by nhooyr** [GoogleCloudPlatform/cloudsql-proxy#177]
Otherwise, important defaults like `AllowNativePasswords` are not set and this causes issues connecting to mysql.

Without `AllowNativePasswords` set to true I could not connect directly to one of our cloud mysql databases.

**Comment by nhooyr** [comment]
1. https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/c9c6b753c7f39940fbc03929c7730dd65745fcb8/proxy/dialers/mysql/hook.go#L69
2. https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/c9c6b753c7f39940fbc03929c7730dd65745fcb8/proxy/dialers/mysql/hook.go#L56
3. https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/c9c6b753c7f39940fbc03929c7730dd65745fcb8/proxy/dialers/mysql/hook.go#L41

Will need to be changed to call `mysql.NewConfig` to get the config with defaults set first.

**Comment by Carrotman42** [comment]
Thanks for the issue; we have an open PR addressing this which just needs to be merged (https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/172).

**Comment by hfwang** [comment]
Merged now, closing this issue.
