### ISSUE TITLE
Error 1064 on valid SQL to create multiple tables

### ISSUE THREAD

**Issue by iancboswell** [GoogleCloudPlatform/cloudsql-proxy#180]
I'm experiencing a strange issue where a SQL script to create multiple tables executes successfully on my local machine and on my Google Cloud SQL instance when running the proxy manually, but gives an Error 1064 on any `CREATE TABLE` statement following the first `CREATE TABLE` when I use this proxy library from within a Go program. I get this issue both with and without wrapping the proxy in `sqlx`. This test code creates the issue I'm experiencing with my script:

```CREATE TABLE IF NOT EXISTS test1 (
    test VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS test2 (
    test VARCHAR(255)
) ENGINE=InnoDB;```

The error:

```Failed to execute schema SQL: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS test2 (
    test VARCHAR(255)
) ENGINE=InnoDB' at line 5```

I would like to think I'm just overlooking something obvious, but since this test SQL works fine on the same database using a different means of connection, I feel like there must be an issue with this library.

**Comment by Carrotman42** [comment]
You can only execute one SQL statement at a time when using Go's database/sql package. Are you attempting to execute more than one in the same Exec (or equivalent) call?

**Comment by iancboswell** [comment]
Aha, that's it! Thanks. Was trying to figure out if that was the issue but I guess I wasn't looking in the right places.
