### ISSUE TITLE
proxy works, but many strange error lines in log

### ISSUE THREAD

**Issue by olih10200** [GoogleCloudPlatform/cloudsql-proxy#185]
Jun 27 08:59:30 *_my_hostname_* cloud_sql_proxy: 2018/06/27 08:59:30 Writing data to local connection on 127.0.0.1:3306 had error: write tcp 127.0.0.1:3306->127.0.0.1:40756: write: broken pipe

^^^ these come per second

dosen't use "credentials", the command, which starts is:
<code>#!/bin/bash

/usr/local/bin/cloud_sql_proxy \
    -instances=_project_:_region_:_instance_=tcp:0.0.0.0:3306 \
    2>&1 | logger -t cloud_sql_proxy &
</code>

Is there any additional parameter to use?

**Comment by kurtisvg** [comment]
Hi @olih10200,

A broken pipe error occurs when a connection was terminated before the data could be completely written. This generally indicates an unstable network environment.
