### ISSUE TITLE
New connection for "myproject:region:db". Client closed local connection on 127.0.0.1:5432

### ISSUE THREAD

**Issue by kevin-jj** [GoogleCloudPlatform/cloudsql-proxy#190]
Our app was deployed at GKE according to [https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine). 

The deployment includes 2 containers myapp + cloudsql-proxy. As app server boots, myapp have no any errors but cloudsql-proxy.

**The following errors from cloudsql-proxy**:

New connection for "myproject:region:db". 
Client closed local connection on 127.0.0.1:5432

any idea? @Carrotman42 

Thanks.

**Comment by Carrotman42** [comment]
Those are not error messages, they are just informational. It comes out of
stderr because that's where Go standard logging logs end up. There are
command line flags to control/suppress these logs if you don't like them.

**Comment by kevin-jj** [comment]
@Carrotman42 However, the status of myapp pods showed "CrashLoopBackOff" & "Does not have minimum availability" in Dashboard Workload at GKE.

<img width="268" alt="screen shot 2018-07-07 at 3 34 39 pm" src="https://user-images.githubusercontent.com/120368/42408203-701eaf3c-81fb-11e8-9f76-8376c15b924a.png">

**The following errors from cloudsql-proxy:**

<img width="764" alt="c3dc6055-cec3-426b-bbbe-4df8ec08c728" src="https://user-images.githubusercontent.com/120368/42408244-0fba3336-81fc-11e8-9039-42e0a6df5a4f.png">

**Comment by Carrotman42** [comment]
Sorry, I am unable to interpret the image you posted, I am unfamiliar with GKE. But it seems you closed the issue so maybe you figured out what was wrong? Please reopen if there's anything we can do to help.

**Comment by kevin-jj** [comment]
Yes, I have figured out that the issue was caused by our K8S configuration file. Cloudsql-Proxy have no problems. Thanks @Carrotman42

**Comment by casoetan** [comment]
> Yes, I have figured out that the issue was caused by our K8S configuration file. Cloudsql-Proxy has no problems. Thanks @Carrotman42

What did you do that made it go away please?

**Comment by bshouse** [comment]
> What did you do that made it go away please?

If you are running 1.13, you can add the following to your startup:  -log_debug_stdout=true

**Comment by casoetan** [comment]
Getting this when I set the flag: `flag provided but not defined: -log_debug_stdout`

**Comment by bshouse** [comment]
> Getting this when I set the flag: `flag provided but not defined: -log_debug_stdout`

#150 was included in 1.13. Are you sure you are running 1.13?

**Comment by casoetan** [comment]
Oh.

Can I upgrade? How do I upgrade please.

**Comment by kurtisvg** [comment]
@casoetan You can download the latest version on the [Releases](https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases) page.

**Comment by vongohren** [comment]
@kevin-jj what kind of configuration was wrong?

**Comment by casoetan** [comment]
@kurtisvg, I mean upgrade my GKE to use the upgrade?

**Comment by kevin-jj** [comment]
> @kevin-jj what kind of configuration was wrong?

We was booting a daemon process of [PUMA](https://github.com/puma/puma) at app server so that K8S closed the process of PUMA and cloud-proxy. @vongohren

**Comment by mrdulin** [comment]
same issue. Don't know why? Any one can explain it ?

**Comment by vongohren** [comment]
@mrdulin I think you have to look at your client library and look at what might happen there. Because that can be the culprit, like this issue https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/243

**Comment by mothukuri** [comment]
We are facing the same problem. Proxy based connection is printing error log messages(connection open and close). Our log based metrics are getting effected. 
Why this cannot be fixed?

Ideally we would want to use proxy but we are falling back to private IP solution. 
We believe this is a fixable issue.

**Comment by Li-ReDBox** [comment]
@mothukuri any reason you prefer proxy but not private IP? Our experience with proxy is mixed. Sometimes the connection is quite unstable. Luckily our application can connect to db through private IP.
