### ISSUE TITLE
Which ports to have open on firewall?

### ISSUE THREAD

**Issue by Rob1080** [GoogleCloudPlatform/cloudsql-proxy#193]
Hi,
When installing cloudsql-proxy behind a firewall; is it only port 3307 that must be opened or port 3306 too? 

[Docs say keep port 3307 open](https://cloud.google.com/sql/docs/mysql/sql-proxy#troubleshooting) but do we need 3306 open too?
The confusion, for me, is when starting up the proxy and you specify port in the instances `-instances=myProject:us-central1:myInstance=tcp:3306`  is that '3306' for local connection or remote connection?

Thanks

**Comment by Carrotman42** [comment]
You only need to ensure outgoing TCP on remote port 3307 is allowed; 3306,
as described in your example argument list, is only used locally.

**Comment by Rob1080** [comment]
Great, thanks!
