### ISSUE TITLE
x509 hostname errors on Go HEAD

### ISSUE THREAD

**Issue by nhooyr** [GoogleCloudPlatform/cloudsql-proxy#194]
If you try to dial an instance say `project-dev:us-central1:main`, pinging will throw an error `x509: Common Name is not a valid hostname: project-dev:main`

Looks like the Go x509 package was updated to throw errors on invalid hostnames.

**Comment by hfwang** [comment]
I wonder if this is related: https://github.com/golang/go/issues/24151

Cloud SQL uses CNs but not SANs in its certificates, from my reading of that thread, it seems like its ok to not use a hostname in the CN?

**Comment by nhooyr** [comment]
Could be the error from https://github.com/golang/go/blob/740e589bd00e330ac38e5aa146961f0d49ff1871/src/crypto/x509/verify.go#L600 or https://github.com/golang/go/blob/740e589bd00e330ac38e5aa146961f0d49ff1871/src/crypto/x509/verify.go#L1013

**Comment by FiloSottile** [comment]
_o/ hi! This is https://tip.golang.org/doc/go1.11#crypto/x509. You need to either move that name to a SAN, or (not recommended) not verify the name with Verify/VerifyHostname, and write your own CN check.

Is this going to affect everyone using CloudSQL? Should I open a Google internal issue to switch to SANs?

**Comment by hfwang** [comment]
Thanks FiloSottile for the pointer.

We are testing a fix for this internally and will try to update this repository hopefully this evening or tomorrow.
