### ISSUE TITLE
Proxy works perfectly when using MacOS mysql client, but connection refused when using python

### ISSUE THREAD

**Issue by butlermd** [GoogleCloudPlatform/cloudsql-proxy#200]
I have a python program that I need to run on my local machine. One of the first things the program does to initialize itself is to connect to the database. The database in this case is a GCP Cloud SQL instance.

When I start up my proxy and connect via command line it works great.

```shell
../another-directory/cloud_sql_proxy -instances=my-project:us-east1:my-db=tcp:3306 &
mysql -P 3306 -h 127.0.0.1 -D mydatabase -u my_user -p
```

And it works great. I can do whatever I need to in the database. 

But when I try to run my program that uses PonyOrm (which under the covers is using `pymysql`), I get this error:

```
pony.orm.dbapiprovider.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 61] Connection refused)")
```

I'm baffled and can't tell what's going on. More oddly still, when I ran this same program in the cloud with kubernetes and a Cloud SQL proxy container, it all worked fine.

**Comment by kurtisvg** [comment]
There could be any number of small things that might be tripping you up:

1. Check that the proxy is still running. If you start it as a background process (with `&`) but close that shell, the proxy will terminate.

2. Check that you are connecting with PonyORM correctly. Looking at the docs, it looks like the following should be close to what you need:
```python
db.bind(provider="mysql", user="my_user", password="my_password",
        host="127.0.0.1", database="mydatabase", port="3306")
```
If you've doubled checked those two things and are still having problems, please post the output of the proxy along with the snippet you are using to connect with.

**Comment by butlermd** [comment]
I thought I'd double checked 2 well enough, but the problem ended up being my Environment variables not making it down the chain to python. Works perfect. Thanks!
