### ISSUE TITLE
New release on gcr.io ?

### ISSUE THREAD

**Issue by thijsterlouw** [GoogleCloudPlatform/cloudsql-proxy#201]
I noticed the last release is 1.11 from Oct 4, 2017 and 38 commits were made to master since this release. Are there any plans to release a new version to gcr.io? 

I also noticed the fixes related to "Automatically refresh SSL certs before they expire" ( https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/142 / https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/160 ) were reverted. Are there still plans to continue that? Last activity is 2 months ago and the fix looks quite important.

**Comment by kurtisvg** [comment]
Hi @thijsterlouw,

Regarding a new container version, @hfwang should hopefully be able to give us a timeline on the next release.

#160 had some feedback that haven't yet been addressed, and it doesn't look the the author has found time to implement them. I know that this is towards the top of the priority list internally, but unfortunately I don't have a timeline I can share with you. If you are interested in contributing to get this feature implemented, please feel free to take a look at the feedback for those PRs.

**Comment by ekimia** [comment]
+1. We are in a bad situation with the bug that was recently fixed that keeps connections open.

**Comment by kurtisvg** [comment]
v1.12 has been released. Thanks for being patient - we are working on a plan for more frequent rollouts in the future.
