### ISSUE TITLE
X509 error

### ISSUE THREAD

**Issue by coderigo** [GoogleCloudPlatform/cloudsql-proxy#203]
We use [github.com/jinzu/gorm](https://github.com/jinzhu/gorm) to connect to cloudsql instances. It itself uses cloudsql-proxy. Without changing anything, as of a day or so, our instance names that are fed into the cloudsql proxy package have remained of the format: `projectid:region:name`. However, when trying to connect we get an error of the form:

```
x509: Common Name is not a valid hostname: projectid:name"
```
(real connection values omitted)

Notice that the region part has been stripped somewhere and I've checked what we feed into it and what gorm passes to the cloudsql-proxy package and they both contain the region. 

Is anyone experiencing the same issue or can see what's wrong?

**Comment by arbarlow** [comment]
We're seeing that same and downgrading to Go 1.10 fixed the issue for us so it seems Go 1.11 is where the issue arrises

**Comment by forrestdix** [comment]
This was fixed; but, not yet released. We are downgrading to go 1.10 until the fix is released. Alternatively, you could try using master for cloudsql-proxy temporarily if you need to use go 1.11.

**Comment by forrestdix** [comment]
See #194 and #196.

**Comment by coderigo** [comment]
@arbarlow, @forrestdix 
Thanks for the info. I just set the docker image to use go 1.10 and as expected it works. I'll keep an eye out for the release. Given this is a kind of dupe of #194 and #196 I suppose this can be closed.
