### ISSUE TITLE
Release 1.12 is the same as 1.11

### ISSUE THREAD

**Issue by pdunnavant** [GoogleCloudPlatform/cloudsql-proxy#211]
I think the latest 1.12 release may be incorrect (on https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases). I have a copy of 1.11 on a server, and it has the same checksum and binary size as the linked download for 1.12 (specifically, the `linux.amd64` version).

My old copy of 1.11:
* sha256: `ea0000ed8a0d29e9fcb1e08635e2e772e0d3f68a7c918b8f6b2a616f1c22c17c`
* file size: `7505002`

A newly downloaded 1.12 (via https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64):
* sha256: `ea0000ed8a0d29e9fcb1e08635e2e772e0d3f68a7c918b8f6b2a616f1c22c17c`
* file size: `7505002`
* This binary also reports that it is version 1.11 when running with `--version`.

Was the 1.12 release possibly created incorrectly?

**Comment by hfwang** [comment]
I think you're right.

I can reproduce the same issue on the OSX version as well. I pushed the binary internally, and that correctly reports the correct version though, so it seems something went wrong when we were releasing to https://dl.google.com/...

**Comment by hfwang** [comment]
pdunnavant, thanks for catching this! I've repushed the binaries to the download site, and when I downloaded it just now and ran it, it correctly reported the same version string.

$ ./cloud_sql_proxy.darwin.amd64 --version
Cloud SQL Proxy: version 1.12; sha 123a90f520a1bbe61974c0439948da2b96fcbe85 built Sat Sep  8 00:06:00 UTC 2018

Please give it a shot.

**Comment by pdunnavant** [comment]
:+1: Everything looks good for me, now. Thanks for fixing this so quickly!
