### ISSUE TITLE
Failure to build version 1.12 for debian packaging

### ISSUE THREAD

**Issue by srivasta** [GoogleCloudPlatform/cloudsql-proxy#214]
Hi,

   While trying to build a Debian packager for cloudsql-proxy, we get an error:

# github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql
src/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql/hook.go:41:9: undefined: mysql.NewConfig
src/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql/hook.go:54:9: undefined: mysql.NewConfig
src/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql/hook.go:66:9: undefined: mysql.NewConfig

  Sure enough, a grep shows that:
rgrep -i NewConfig .
./proxy/dialers/mysql/hook.go:  cfg := mysql.NewConfig()
./proxy/dialers/mysql/hook.go:  cfg := mysql.NewConfig()
./proxy/dialers/mysql/hook.go:  cfg := mysql.NewConfig()
./obj-x86_64-linux-gnu/src/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql/hook.go:   cfg := mysql.NewConfig()
./obj-x86_64-linux-gnu/src/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql/hook.go:   cfg := mysql.NewConfig()
./obj-x86_64-linux-gnu/src/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql/hook.go:   cfg := mysql.NewConfig()
Binary file ./obj-x86_64-linux-gnu/bin/cloud_sql_proxy matches

  I can send in the full build log if clarification is needed.

   manoj

**Comment by hfwang** [comment]
srivasta, mysql.NewConfig was newly added to the mysql library. Is it possible for you to either update the go version or the mysql library?

**Comment by srivasta** [comment]
Hi,

  The most recently available version of mysql on Debian unstable is 1.3. Version 1.4 is not yet available. Is this a hard requirement? If so, I'll add a dependency for go-sql-driver-mysql-1.4

   Manoj

Package: golang-github-go-sql-driver-mysql-dev
Source: golang-github-go-sql-driver-mysql
Version: 1.3-1
Installed-Size: 221
Maintainer: Debian Go Packaging Team <pkg-go-maintainers@lists.alioth.debian.org>
Architecture: all
Description-en: MySQL-Driver for Go's database/sql package
 Features:
  - Lightweight and fast
  - Native Go implementation. No C-bindings, just pure Go
  - Connections over TCP/IPv4, TCP/IPv6 or Unix domain sockets
  - Automatic handling of broken connections
  - Automatic Connection Pooling (by database/sql package)
  - Supports queries larger than 16MB
  - Full sql.RawBytes support.
  - Intelligent LONG DATA handling in prepared statements
  - Secure LOAD DATA LOCAL INFILE support with file Whitelisting and io.Reader
    support
  - Optional time.Time parsing
  - Optional placeholder interpolation
Description-md5: fa08b137bb0317b88861910c6b6ac8ee
Homepage: https://github.com/go-sql-driver/mysql
Section: devel
Priority: optional
Filename: pool/main/g/golang-github-go-sql-driver-mysql/golang-github-go-sql-driver-mysql-dev_1.3-1_all.deb
Size: 48512
MD5sum: 30b99e81727b086d1e8c45e4c306d8af
SHA256: dc3d5667a593cc20b9b9181ed2b403a621cdf2882ffe48a9f04e7c79fa759b75

**Comment by srivasta** [comment]
In the case that we depend on the new features of mysql driver, this is not a bug, but should perhaps be noted in the documentation, and I'll just wait on the Debian packaging untilk the driver catches up.

   Manoj

**Comment by hfwang** [comment]
srivasta, is the mysql 1.4 package available now?

https://packages.debian.org/sid/devel/golang-github-go-sql-driver-mysql-dev

**Comment by hfwang** [comment]
https://tracker.debian.org/pkg/cloudsql-proxy has 1.13 released on 2019/01/13
