### ISSUE TITLE
Please version downloads

### ISSUE THREAD

**Issue by danielbprice** [GoogleCloudPlatform/cloudsql-proxy#215]
Cloud SQL Proxy broke for us in the upgrade from v1.11 and v1.12; one reason was because of the ulimit change (systemd, at least on debian, requires additional configuration to cope).  I deploy the proxy using Ansible throughout a multi-system development environment-- the Ansible recipe fetches the proxy software from `dl.google.com` and installs it.

Recently, we couldn't control when we started to wind up with systems running v1.12, because the download URL is always the same between versions-- e.g. `https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64`.

So it would really help if the download URLs could be versioned, e.g. 
`https://dl.google.com/cloudsql/v1.12/cloud_sql_proxy.linux.amd64`.  Ideally, please also publish SHA256 hashes for each version so that automation can check that the binaries are intact as expected.

Thanks!

**Comment by hfwang** [comment]
We have had an internally filed issue with the same request, thanks for filing the issue, I'll up the priority internally!

**Comment by hfwang** [comment]
As of 1.13, we've (finally) started versioning the download links. See https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
