### ISSUE TITLE
cloudsql-proxy can connect to cloudsql with a service account that used to have cloudsql.client role but not now

### ISSUE THREAD

**Issue by zwcn** [GoogleCloudPlatform/cloudsql-proxy#219]
Hi, 

I followed the instructions at https://cloud.google.com/sql/docs/postgres/connect-admin-proxy to use cloud sql proxy to access a cloud sql instance. I created a service account with the `cloudsql.client` role, downloaded a key file `key.json` for the service account, and passed `key.json` to the `-credential_file` parameter in `cloud_sql_proxy`. Everything worked fine: the proxy could establish a connection and I could log into the postgres database. 

But when i unassigned the `cloudsql.client` role from the service account, i was expecting that the proxy couldn't establish the connection because it didn't have the permission any more. However, that's not the case and i was still asked for my user's password. Is that a bug or an expected behavior?

How to reproduce?

- assume the role `cloudsql.client` role is assigned to the service account
- `cloud_sql_proxy -instances=<instance>=tcp:5432 -credential_file=key.json`
- `psql -h 127.0.0.1 -U postgres postgres`. A prompt appears to ask my password.
- now unassign the role `cloudsql.client` role from the service account
- keep `cloud_sql_proxy` running without restarting it. Restarting it did cause the `psql` command in the next step fail to connect.
- run `psql -h 127.0.0.1 -U postgres postgres` again and the prompt still appears.

**Comment by kurtisvg** [comment]
Hey @zwcn,

That behavior is expected. The Cloud SQL proxy creates an authentication certificate that lasts about 60 minutes. At the end of the 60 minute window, the proxy would have failed to establish a new certificate (which is what happened when you restarted the proxy).
