### ISSUE TITLE
Python Package instead of companion process

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/cloudsql-proxy#221]
Reading the docs there is support for the go language to use this as a library. We built a tool in python and currently run it as a companion process, but our codebase would really love to have this as a package. 

Wanted to put this issue up to see if this is could be possible and if other developers would be interested in it as well :)

**Comment by hfwang** [comment]
We wrote a java equivalent as well, but our experience is that if we start writing libraries, we would be on the hook for building and supporting N libraries, which would get hard.

That being said, if other customers would really benefit from this, please speak up, so we have the information :)

**Comment by kurtisvg** [comment]
For reference, the java equivalent is here: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory

@enriquejosepadilla I would be very interested in seeing your implementation in python - is it open sourced?

**Comment by enriquejosepadilla** [comment]
@kurtisvg https://github.com/GoogleCloudPlatform/django-cloud-deploy/blob/e2c6e85e05393373446f3e0f7fde9e9a56117ba4/django_cloud_deploy/cloudlib/database.py#L179

An example of it being used it:

https://github.com/GoogleCloudPlatform/django-cloud-deploy/blob/e2c6e85e05393373446f3e0f7fde9e9a56117ba4/django_cloud_deploy/cloudlib/database.py#L229

**Comment by kurtisvg** [comment]
Closing this for now because it out outside the scope of this github repo.
