### ISSUE TITLE
Credentials supplied by local environment not working

### ISSUE THREAD

**Issue by gthar** [GoogleCloudPlatform/cloudsql-proxy#227]
After updating from 1.11 to 1.13,

Authenticating with
./cloud_sql_proxy -instances=$INSTANCE_NAME -credential_file=/tmp/creds.json

Does work, but

GOOGLE_APPLICATION_CREDENTIALS=/tmp/creds.json ./cloud_sql_proxy -instances=$INSTANCE_NAME

Does not, even thought the [documentation](https://cloud.google.com/sql/docs/mysql/sql-proxy#invocation) states they are equivalent.

**Comment by markfermor** [comment]
due to this https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/198#discussion_r225649203

**Comment by hfwang** [comment]
Created PR #229 to start a discussion on this.

**Comment by hfwang** [comment]
Submitted #229
