### ISSUE TITLE
Feature Request / Investigation: proxy between DB types

### ISSUE THREAD

**Issue by unquietwiki** [GoogleCloudPlatform/cloudsql-proxy#228]
http://sqlrelay.sourceforge.net/ claims to be able to convert requests between different DBMS types. It'd also be nice to have some connection-pooling ability as well.

**Comment by kurtisvg** [comment]
Connection Pooling is discussed in #88.

**Comment by unquietwiki** [comment]
@kurtisvg Thanks! It looks like I had already started doing some of what @mykolasmith is doing; except ATM trying to switch to pgpool-II + read-replicas + multiple instances of this; instead of pgBouncer.

Also, having dug into SQLRelay some more, it's definitely more a library-oriented solution. I haven't seen a Go-equivalent yet, but https://github.com/taskrabbit/makara & https://github.com/joinhandshake/knockoff appear to be easy ways to do this in Ruby.

**Comment by kurtisvg** [comment]
Closing this issue - proxying between database types is outside the scope of the proxy at this time.
