### ISSUE TITLE
PostgreSQL LISTEN/NOTIFY is unstable

### ISSUE THREAD

**Issue by robsonpeixoto** [GoogleCloudPlatform/cloudsql-proxy#239]
For some unknown reason after some time the LISTEN/NOTIFY stops receive notifications from PostgreSQL. Anyone with this problem?

**Comment by kurtisvg** [comment]
@robsonpeixoto This repo is only for tracking development of the Cloud SQL proxy. There doesn't seem to be anything indicating that the proxy is causing this issue, so I'm going to close this.

I suggest looking for a form or repo that provides support for PostgreSQL itself.
