### ISSUE TITLE
Problem with credentials in my go app 

### ISSUE THREAD

**Issue by EgorkZe** [GoogleCloudPlatform/cloudsql-proxy#240]
I use this example 
```
dsn := fmt.Sprintf("host=%s dbname=%s user=%s password=%s sslmode=disable",
		"proj:loc:ident",
		"postgres",
		"postgres",
		"pass")
db, err := gorm.Open("cloudsqlpostgres", dsn)
	if err != nil {
		panic(err)
	}
	defer db.Close()
```

But it is not working and give me an error 

> "panic: default proxy initialization failed; consider calling proxy.Init explicitly: google: could not find default credentials."

If start proxy from terminal and use localhost as host all is working fine.
So, what I do wrong?

**Comment by kurtisvg** [comment]
The dialer portion of the library follows the [Application Default Credentials](https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application) strategy for retrieving credentials in which to connect with. Whatever environment you are running program in doesn't seem to have access to these credentials. 

The easiest way to provide authentication steps is set the `GOOGLE_APPLICATION_CREDENTIALS` to a filepath where a service account key is located.

**Comment by EgorkZe** [comment]
@kurtisvg So, I did it, but it didn't help (

**Comment by kurtisvg** [comment]
You mentioned "from terminal all is working fine" - how are you executing your program? Through an IDE?

**Comment by EgorkZe** [comment]
@kurtisvg thank you! You are right! I didn’t set environment variables in vscode
