### ISSUE TITLE
Feature Request: set socket name

### ISSUE THREAD

**Issue by wedi** [GoogleCloudPlatform/cloudsql-proxy#241]
It would be cool if the name of the socket file could be changed via command line.

Reasoning: Third parties rely (way too) often on hard coded, distribution depending values like `/tmp/mysql.sock`, `/var/run/mysqld/mysqld.sock` etc. By being able to change the socket name no changes to third party software are neccessary and a silent db change in the background becomes possible. It's no problem to change the socket name in a full fledged sql installation either(`my.cnf`). Of course one can add a symlink but this is not practical when running the cloudsql proxy docker image.

**Comment by Carrotman42** [comment]
I thought this was allowed already, but looking through the code I believe I am wrong. My suggestion would be to augment the existing ability to specify a TCP port to listen to, and instead handle 'unix' sockets as well. Something like:

    -instances=my-project:my-region:sql-inst=unix:/tmp/mysql.sock

For reference, this is the code that would need to be updated; it's not too complex, if you'd like to send in a PR: 

https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/2ec72f445aed645b40aeea03e73e6acff892d2e1/cmd/cloud_sql_proxy/proxy.go#L226-L245

**Comment by kurtisvg** [comment]
Fixed in #289
