### ISSUE TITLE
Add documentation for running cloudsql-proxy as a service in Kubernetes

### ISSUE THREAD

**Issue by naseemkullah** [GoogleCloudPlatform/cloudsql-proxy#242]
for cases such as cronJobs.

**Comment by naseemkullah** [comment]
Also please list pros and cons to both approaches (sidecar vs deployment)

It may be nice to refer to this helm chart as well https://github.com/rimusz/charts/tree/master/stable/gcloud-sqlproxy

**Comment by rlweb** [comment]
Yep, especially how to run cronjobs since now its on a distroless image, we're unavailable to do this:
```
        command: ["/bin/sh", "-c"]
        args:
          - |
            /cloud_sql_proxy -instances= ... & CHILD_PID=$!
            (while true; do if [[ -f "/tmp/pod/terminated" ]]; then kill $CHILD_PID; echo "Killed $CHILD_PID because the main container terminated."; fi; sleep 1; done) &
            wait $CHILD_PID
            if [[ -f "/tmp/pod/terminated" ]]; then exit 0; echo "Job completed. Exiting..."; fi
```

**Comment by arbourd** [comment]
There is [a Helm chart](https://github.com/rimusz/charts/tree/master/stable/gcloud-sqlproxy). Although not docs, but you should be able to interpolate how the deployment works from [the template](https://github.com/rimusz/charts/blob/master/stable/gcloud-sqlproxy/templates/deployment.yaml).
