### ISSUE TITLE
Timeout creating ephemeral certificate

### ISSUE THREAD

**Issue by seanhagen** [GoogleCloudPlatform/cloudsql-proxy#246]
We're using the [proxy dialer](https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/master/proxy/dialers/postgres) in Go, and occasionally we get this error:

`
Post https://www.googleapis.com/sql/v1beta4/projects/a-good-project-name/instances/our-db-instance/createEphemeral?alt=json&prettyPrint=false: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`

Is there anything we can do on our end to prevent seeing this? It happens randomly and will take anywhere from a few seconds to half an hour to resolve itself, which means that we're unable to process database queries while this is happening.

**Comment by torbjornvatn** [comment]
I got this problem too, it's mostly annoying because it logs as an Error in Stackdriver

**Comment by kurtisvg** [comment]
dup of #357
