### ISSUE TITLE
How thread safe is the library

### ISSUE THREAD

**Issue by patilpankaj212** [GoogleCloudPlatform/cloudsql-proxy#248]
Hi, 

I am using proxy library to connect to Google Cloud SQL Instances. I am using proxy.Init(...) to initialize the proxy. I wanted to know about thread safety of the library (two or more goroutines calling init and performing operations on different db's) ?

**Comment by hfwang** [comment]
proxy.Init() is guarded by locks, and we support multiple simultaneous connections to multiple databases.
