### ISSUE TITLE
Support socks

### ISSUE THREAD

**Issue by devops724** [GoogleCloudPlatform/cloudsql-proxy#249]
i try run 
./cloud_sql_proxy -instances="[instance name]"=tcp:5432 -credential_file=cloudsql-credentials.json
under socks proxy,
 i try multiple approach  
using proxychains :
proxychains4 ./cloud_sql_proxy -instances="[instance name]"=tcp:5432 -credential_file=cloudsql-credentials.json
use export
export http_proxy=http://localhost:8035/ https_proxy=http://localhost:8035/
i wonder how i can set proxy and pass throw proxies requests

**Comment by broady** [comment]
`HTTP_PROXY` should proxy the HTTP requests via your SOCKS proxy, however the actual database connections wouldn't go over the proxy.

I think we could pretty easily support this by using proxy.FromEnvironment() as the dialer.

https://godoc.org/golang.org/x/net/proxy#FromEnvironment

**Comment by MunGell** [comment]
Unfortunately, can't contribute much, but hoping someone could implement this feature request soon...

**Comment by Sherman-Chata** [comment]
proxychains4 cloud_sql_proxy 
works for us
