### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Sh4rK** [GoogleCloudPlatform/cloudsql-proxy#251]
Hi,
I've run into an annoyance while using the proxy (there's a 30s delay on startup) which is already fixed on master, but not in a release yet. Is it possible to get a release out? What's the policy on this?

Thanks!

**Comment by kurtisvg** [comment]
Hey @Sh4rK,

We currently don't have a fixed release schedule. It is on our agenda to automate the process so that features are available after being merged, but I'm unable to give a timeline for when we will have that accomplished.
