### ISSUE TITLE
Creating credentials with console strips specials characters making cloudsql secret invalid

### ISSUE THREAD

**Issue by josefkorbel** [GoogleCloudPlatform/cloudsql-proxy#254]
Hello, I've found out that If i create cloudsql secret in web console ( I was following [this](https://cloud.google.com/python/django/kubernetes-engine) tutorial the whole time), and I use special characters, the password is stripped before converting them to base64 encoded string in credentials json which makes it invalid.

I made a stackoverflow [question](https://stackoverflow.com/questions/54647972/problem-with-escaping-password-with-special-characters-in-kubernetes-cloudsql/54648225?noredirect=1#comment96088551_54648225) also as I was not sure If it was kubectl or gke or cloudsql related.

**Comment by josefkorbel** [comment]
Found out that was my error as I've typed it in kubectl without escaping. I am still getting django exception for credentials incorrent even though they are correct.

**Comment by kurtisvg** [comment]
Hey @josefkorbel - since your problem is related to escaping the password, it doesn't look like this is a problem related to the proxy. As such I'm going to close this issue, but I'll keep an eye on your SO post to see if you can resolve the issue.
