### ISSUE TITLE
Clarify documentation on expected value for `-instances_metadata`

### ISSUE THREAD

**Issue by matalo33** [GoogleCloudPlatform/cloudsql-proxy#259]
When using `-instances_metadata` README.md states that:

> The given GCE metadata key will be polled...

To me this implies only the name of the metadata key is required. For example 

`-instances_metadata my-sql-instances`

In actual fact a path must be specified relative to `http://metadata.google.internal/computeMetadata/v1/`. In this case the expected input should be 

`-instances_metadata instance/attributes/my-sql-instances`

Documentation should be updated to reflect this.

**Comment by Carrotman42** [comment]
Thanks for the issue. At some point in the evolution of the Proxy it was
actually just the key name, but in order to support project level keys we
changed the requirements a bit.

Thank you very much for the PR, and apologies for any time you wasted
figuring out the problem.
