### ISSUE TITLE
Unable to use -credential_file on GCE

### ISSUE THREAD

**Issue by petercm** [GoogleCloudPlatform/cloudsql-proxy#26]
This was working for me last week. I suspect it could be related to the scope check fix in #21 

The check for `onGCE` in `checkFlags` comes before anything would look at the tokenFile provided in `-credential_file` (or a `-token` or `GOOGLE_APPLICATION_CREDENTIALS` for that matter). So if the default service account does not have the `sqlservice.admin` scope those other auth methods will never be checked.

I'm running in Kubernetes and would prefer to only give access to the pods that need it.

**Comment by Carrotman42** [comment]
This has been pushed out in 1.05
