### ISSUE TITLE
1.13 not tagged latest

### ISSUE THREAD

**Issue by wedi** [GoogleCloudPlatform/cloudsql-proxy#261]
I just saw that there is a version 1.13. Is there a reason why the [latest tag hasn't been updated](https://console.cloud.google.com/gcr/images/cloudsql-docker/GLOBAL/gce-proxy)? To me this sounds like: "it's there but we're not confident it's production ready."

**Comment by nikitashalnov** [comment]
And I have also a question about releasing policy. When should we wait a new release (1.14)? :smiley:

**Comment by markvincze** [comment]
Hey all,
I've just noticed this too, and I'm also interested in whether we should use 1.12 or 1.13 if we want to get the latest stable release.
Thanks!

**Comment by wedi** [comment]
@nikitashalnov  I'd suggest as soon as any pending pull requests are reviewd and merged. 😋🤗

**Comment by kurtisvg** [comment]
Hey all,

1.13 should be ready for production use. The 'latest' tag mismatch is unintentional. 

We currently don't have a formal release schedule in place, but working on formalizing one.
