### ISSUE TITLE
Terminating Sidecar after Kubernetes Job

### ISSUE THREAD

**Issue by molenpad** [GoogleCloudPlatform/cloudsql-proxy#262]
I have a cron job running in kubernetes that will run a mysql query, so therefore I've deployed the cron with a cloudsql sidecar container.

This works fine, however I want to be able to gracefully shut the down proxy container when the job completes, otherwise the job itself does not clean itself up as desired.

I have `shareProcessNamespace:` set to `true` so I have tried doing a `pkill -15 cloud_sql_proxy` from the master container at the end of the cron job script but this causes the sidecar container to exit with `error` which doesn't allow the job to succeed and finish gracefully.

Is there any hacky way that I can force the proxy sidecar to exit when the job is finished, in such a way that the job succeeds in cleaning itself up?

**Comment by kurtisvg** [comment]
You might be interested in this article on the subject: https://medium.com/@cotton_ori/how-to-terminate-a-side-car-container-in-kubernetes-job-2468f435ca99

The gist of it is the main container creates a file at `/tmp/pod/terminated` during termination, which the sidecar watches for, and exits once it appears.

**Comment by dshetty312** [comment]
The article referenced above does not exist any more.Do we have a solution for this?

**Comment by kurtisvg** [comment]
@dshetty312 The article describe a situation where the sidecar ran a script that did the following:

1. Start the cloud sql proxy in the background `cloud_sql_proxy <your_args> &`
2. Wait for a file to appear (e.g. while loop until a file at `/tmp/pod/teminated` exists)
3. Exit the proxy

The from the main container, do the following:

1. Run your process
2. Create a file at `/tmp/pod/terminated`

This means the main container tells the sidecar when it's finished, and the side car exits the proxy and terminates.

**Comment by dshetty312** [comment]
Thanks.

**Comment by nicknovitski** [comment]
The newer versions of the container don't include `/bin/sh`, so this approach is no longer possible.

I haven't tried it, but https://github.com/karlkfi/kubexit seems like a promising possibility for now.

**Comment by kurtisvg** [comment]
@nicknovitski there are alpine and buster based distributions that both include shells if you still need this functionality

**Comment by adriangb** [comment]
I've gotten the following to work successfully:

```
command: [
  "timeout",
  "--preserve-status",
  "-s",
  "SIGTERM",
  "30s",
  "/cloud_sql_proxy",
  # other options
  "-term_timeout=3600s",
]
```

This only works on the `buster` image because the `alpine` image does not have GNU coreutil's timeout (which we need for the `--preserve-status` option).

Basically, after 30 seconds (more than long enough for the primary container to start running, unless something is wrong) a SIGTERM is sent, at which point CloudSQL Proxy will wait **up to** 3600s (in my case more than long enough but this is configurable) before exiting with a 0 status code _as long as there were no active connections_.

For my use case of running migrations, this works out great

**Comment by andreasvikke** [comment]
After using @adriangb's solution for a while, I noticed some random errors popping up from time to time. So, I decided to dive into the Google Cloud SQL Repo and discovered they've got a new Admin API to help you gracefully shut down the sidecar pod.

To add a cool shutdown feature, just throw this line at the end of your Cron Job:
```
curl http://localhost:9091/quitquitquit
```

And add these args to the SQL Proxy:
```
args:
  # Enable the admin api server on port 9091
  - "--admin-port=9091"
  # Enable the /quitquitquit admin api endpoint
  - "--quitquitquit"
  # Tell the proxy to exit gracefully if it receives a SIGTERM
  - "--exit-zero-on-sigterm"
```

You can find the Kubernetes shutdown hook example in the [K8s Shutdown Hook](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/examples/k8s-sidecar/job_with_shutdown_hook.yaml) in the Google Cloud SQL Proxy repo.

**Comment by aguynamedben** [comment]
Great find @andreasvikke, thank you so much!

**Comment by jackwotherspoon** [comment]
@aguynamedben 

As an FYI to you and anyone else looking into this issue, I would suggest taking a look at https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/128#issuecomment-2264787327 and recommend [Kubernetes native sidecars](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) (Kubernetes 1.28+). 

You will **not** need to use the `--quitquitquit` endpoint and still receive all the wanted benefits more easily and reliable 👍
