### ISSUE TITLE
-credential_file option does not seem to work

### ISSUE THREAD

**Issue by mhoran** [GoogleCloudPlatform/cloudsql-proxy#263]
I've been unable to get the `-credential_file` option to work as documented. When I set `GOOGLE_APPLICATION_CREDENTIALS` to the path of a JSON file containing credentials for a service account, `cloud_sql_proxy` works as expected. However, when I unset `GOOGLE_APPLICATION_CREDENTIALS` and use the `-credential_file` option, I get the following error:

```
2019/03/15 11:46:32 current FDs rlimit set to 28494, wanted limit is 8500. Nothing to do here.
2019/03/15 11:46:32 using credential file for authentication; email=orion-966@western-notch-111123.iam.gserviceaccount.com
2019/03/15 11:46:32 google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
exit status 1
```

Adding some print debugging shows that the two approaches make it to the same point in `authenticatedClientFromPath`. Things seem to go haywire `goauth.JWTConfigFromJSON`, where I gave up on debugging. While `goauth.JWTConfigFromJSON` does not return an error, it seems to rely on `GOOGLE_APPLICATION_CREDENTIALS` in some way, resulting in the `could not find default credentials` error above.

**Comment by kurtisvg** [comment]
Did you compile from the source yourself? I can't seem to replicate this using the release executable

**Comment by mhoran** [comment]
Yes; I had to because of #252, and the fact that there are no release executables for FreeBSD. However, I can also reproduce on Linux by running the binary produced by `go get github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy`. The Linux release binary does work for me.
