### ISSUE TITLE
Library usage

### ISSUE THREAD

**Issue by HazCod** [GoogleCloudPlatform/cloudsql-proxy#264]
Hi,

I recently setup an AppEngine Go 1.11 application that uses the cloudproxy library.
This allows me to access dev databases in gcloud without having to run a separate process.

Is the same possible for PHP? I don't see any reference of that.
Are there plans to bring that to every language?

**Comment by kurtisvg** [comment]
We currently have a similar library for Java ([Cloud SQL JDBC Socket Factory)](https://cloud.google.com/sql/docs/mysql/connect-external-app), but we don't have anything similar for PHP.
