### ISSUE TITLE
Intermittent packet corruption errors on Windows

### ISSUE THREAD

**Issue by lukeschlather** [GoogleCloudPlatform/cloudsql-proxy#270]
My team has intermittently noticed an issue where the SQL proxy refuses to connect. Sometimes it has been on flaky networks, however we've seen instances where an individual Windows machine gets stuck in a state where it simply will not connect and always returns an error like tls: bad record mac. e.g :

```
cloud_sql_proxy.exe -instances=my-project:us-central1:my-instance=tcp:5491
2019/04/03 15:53:03 Listening on 127.0.0.1:5491 for my-project:us-central1:my-instance
2019/04/03 15:53:03 Ready for new connections
2019/04/03 15:53:15 New connection for "my-project:us-central1:my-instance"
2019/04/03 15:53:21 Reading data from my-project:us-central1:my-instance had error: remote error: tls: bad record MAC
```

This log is from my laptop where I have managed to reproduce it consistently by trying to run a script that executes some queries to insert a substantial amount of data into the database. Oddly, I am able to run our migration tool and manually connect using psql without incident. This is unique: my teammates reported all traffic being blocked by this issue when they encountered it, and usually switching networks or rebooting solved it (I rebooted and went to a different network but still I am able to reproduce the issue.)

**Comment by kurtisvg** [comment]
This issue's been open for almost a year and we haven't had any other reports or been able to reproduce. Going to close for now.
