### ISSUE TITLE
App engine (python3 - standard environment) generate aborted connections when connecting to a cloud sql -2nd Gen Mysql instance

### ISSUE THREAD

**Issue by fumpe** [GoogleCloudPlatform/cloudsql-proxy#279]
I'm currently developing a project with python 3.7, Django 2.1, Mysql as database.

I'm deploying it in google cloud app engine standard environment and for the database I'm using a cloud SQL - MySql 2nd gen instance.

The application works well, however when I analyze the logs I see these errors:

> "**aborted connection - Got an error reading communication packets**"

In this case the connection is being closed by my app (django).If I configure my app to have persistent connections and I put wait_timeout (i.e 60) in the config of the cloud sql, the error is:

> "**aborted connection - Got timeout reading communication packets**".

I think maybe it's not a problem with sql cloud, or with the configuration of my application, but that it's an app engine problem. I came to this conclusion in the following way:

if I connect to the sql cloud instance through Mysql workbench, no connection is aborted. Similarly if I run my application on a local server, but connecting to cloud sql (through the cloud_sql_proxy), no error is generated and everything works perfect.

So my conclusion is that it is a problem of how the app engine connects to the cloud sql instance.

**Why does this happen? How could it be solved?**

**Comment by kurtisvg** [comment]
Hey Fumpe,

Unfortunately, issues on this repo are limited to tracking issues with the cloudsql_proxy itself, and not for any of the products. Google App Engine does have a public issue tracker, which you can submit issues to [here](https://b.corp.google.com/savedsearches/559750).

I can give a few suggestions for troubleshooting, based on my own experience:

1. Make sure you are using the unix socket provided at `/cloudsql/<INSTANCE_CONNECTION_NAME`. Instructions on how this works can be found on the [Connecting from App Engine](https://cloud.google.com/sql/docs/mysql/connect-app-engine) page. 

2. Make sure you are using a connection pool, and returning connections to the pool (via closing) as soon as you are finished with them. The [Managing database connection](https://cloud.google.com/sql/docs/mysql/manage-connections) page has some good examples of this. 

3. Try a different driver. Python has lots of drivers, and I'm not sure what kind of support App Engine has to each one. If you aren't already using `pymysql`, it's pure python so it shouldn't have any issues.

Hope that helps.

**Comment by fumpe** [comment]
Thanks a lot kurtisvg. I changed de Driver to pymysql and the aborted connection decreased significantly.
