### ISSUE TITLE
Include Dockerfile for cloudsql-docker

### ISSUE THREAD

**Issue by psamaan** [GoogleCloudPlatform/cloudsql-proxy#28]
I can't seem to find the Dockerfile or image components for the Docker image compiled from this repo and available at "b.gcr.io/cloudsql-docker/gce-proxy", so those of us using this on GCE as the only way to access Cloud SQL securely are unable to build an image from specific commits so we can for instance rollback to previous non-production breaking changes. Kindly share the Dockerfile or otherwise maintain a version system for the images corresponding to the commits on GitHub.

**Comment by Carrotman42** [comment]
Ah yes, I'm surprised I actually didn't do that already.

By the way, sorry for breaking your production with the latest release :/ If you have a test environment that you would be able to test the master branch please let me know. I could help set anything up if it meant that releases would be more stable.

**Comment by psamaan** [comment]
Thank you. It's okay about the latest release, I ended up hopping on a host running a working container, finding its orphaned image and tagging and pushing it to our own repo to use instead, so it worked out. I'll see what I can do about the testing environment. Thanks for the quick merge.

**Comment by Carrotman42** [comment]
PTAL at https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/29; I decided against publishing a standalone Dockerfile which was 'FROM golang' and compiled the proxy on its own, but that would force end users to download the container containing the compiler and standard library even though it's unnecessary.

Let me know if you know of another way to create a standalone Dockerfile which does not end up basing itself off of another container (other than 'scratch'). Also feel free to make any comments on that pull request if you have anything to add/request.

**Comment by Carrotman42** [comment]
Please reopen if https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/29 doesn't fully solve your problem or if you have more feature requests for building.

**Comment by Carrotman42** [comment]
For version 1.05 I did a docker push without updating the 'latest' tag. You can try out the new version by pulling b.gcr.io/cloudsql-docker/gce-proxy:1.05

I will update the latest tag after a bit of time.
