### ISSUE TITLE
Cannot authenticate second instance in the string

### ISSUE THREAD

**Issue by Bloodrxt** [GoogleCloudPlatform/cloudsql-proxy#284]
Hi all, 
I’m having an issue with connecting to 2 instances at the same time
I want to use service account key but its different for both of the instances as they are on different projects
Im calling :
cloud_sql_proxy.exe -instances=DB1=tcp:3306,DB2=tcp:3307 -credential_file=c:\KEy\db1.json & c:\KEy\db2.json
First instance connects fine but the second one is not authorised.
Can you help me with syntax to make it work please?
 
Cheers
Paulina

**Comment by Carrotman42** [comment]
There is currently no support for using a different credential file for different databases. Other than adding changes to the client to support it, you could start two proxy processes.

**Comment by kurtisvg** [comment]
Additionally, you can also add a single service account to both projects with the correct IAM roles. See [here](https://stackoverflow.com/a/35558464/9414803) for some instructions how.
