### ISSUE TITLE
Regional container registry hosts

### ISSUE THREAD

**Issue by paolomainardi** [GoogleCloudPlatform/cloudsql-proxy#292]
Hi everyone! 

Would be possible to push the image to the eu.gcr.io registry ? We are using it a lot in our CI/CD pipelines and we want to avoid to be charged from NA to EU.

**Comment by kurtisvg** [comment]
Actions for this issue
* Back fill for each region (us.gcr.io, eu.gcr.io, asia.gcr.io)
* Update release to push new version to additional regions
* Update README to reflect available regions

**Comment by kurtisvg** [comment]
The repos for `us.gcr.io`, `eu.gcr.io`, and `asia.gcr.io` are now up and public.

**Comment by paolomainardi** [comment]
Thanks a lot!
