### ISSUE TITLE
Ephemeral Certificate Refresh Rate

### ISSUE THREAD

**Issue by dwhoman** [GoogleCloudPlatform/cloudsql-proxy#298]
After using the cloud-sql-proxy for various applications, the time until the proxy's certificate is refreshed appears to be related to the total number of connections created and closed.  The proxy refreshes more often when used by applications that make more frequent connections.  Looking in the [source code](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/proxy/client.go), the refresh is only triggered after a certain amount of time has passed.  Perhaps I am missing something.  How does the proxy decide when to refresh the certificate?  Can frequent refreshes cause issues for the proxy?

**Comment by kurtisvg** [comment]
IIRC, the proxy should refresh the certificate when the previous cert expires or if an error occurs during the connection. 

Are you sure you are using an up to date version of the proxy?

**Comment by dwhoman** [comment]
I am using version 1.14.  I don't see any errors, just the message `ephemeral certificate for [db_name] will expire soon, refreshing now`.  Under heavy load, 3 connections/second, the certificate is refreshed 19.3 times per hour and under light load, 0.0001 connections/second, the certificate is refreshed 2 times per hour.  Curiously, under light load, the number of connections made is less than the number of refreshes over the time period, and the refreshes seem to be clustered in pairs, the two occurrences in the pair being one minute apart and each pair being an hour apart.  Under heavy load, the refreshes in the log are not paired, and the refreshes are about two to three minutes apart.  There aren't any logs about the certificate expiring too soon.

On another computer, running the proxy under the same configuration, but having even less load, 0.00004 connections per second, a certificate refresh has never been logged and it has been running continuously since June.

**Comment by terev** [comment]
@kurtisvg  https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/proxy/client.go#L216 it looks like there's a goroutine spawned that triggers around 30 seconds before **local** cert expiry. However it looks like there's no conditions around spawning a new goroutine to trigger the refresh. That means that any time the config is refreshed (which happens at a regular interval) a new gorountine can be spawned which causes these to pile up and eventually all try to refresh one after another. It looks like a flag is needed here to indicate whether a refresh is queued.

**Comment by terev** [comment]
The refreshcfg method is already thread safe since there's a mutex locked on entry so it should be safe to read/write a certRefreshQueued flag on the client object

**Comment by terev** [comment]
actually it corresponds with new connections here https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/proxy/client.go#L289

**Comment by terev** [comment]
@kurtisvg sorry i think i was wrong about it piling up goroutines. it looks like it avoids this by returning early with a cached result. it must assume that there's already a queued goroutine to refresh the cfg

**Comment by terev** [comment]
@dwhoman  So after all the refresh rate is based mostly on the expiry of the generated client certificate. There's not much transparency into what the expiry for generated certs via createEphemeral is. The docs basically just state that they're supposed to be very short lived. Since the googleapi makes this decision on behalf of the client this might mean the behavior reported in this issue is actually expected. This is all just conjecture but i have noticed similar pacing in my usage which leads me to believe this is expected.

**Comment by kurtisvg** [comment]
This issue has gone stale - marking as closed.
