### ISSUE TITLE
Cannot connect mysql through kubernetes pods 

### ISSUE THREAD

**Issue by limbuu** [GoogleCloudPlatform/cloudsql-proxy#308]
I am getting this issue while connecting mysql through my kubernetes pods. I have used cloudsql proxy. 

sqlalchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on '10.48.128.3' (110) (Background on this error at: http://sqlalche.me/e/4xp6)

It was working fine till yesterday. Suddenly it cannot be connected now.

**Comment by limbuu** [comment]
Sorry. We had deployed our application on default network mode. Changing newtork to VPC native fixed the problem. Same private IP 10.48.128.3 worked flawlessly.
But, i have a question, Since there is no any option to edit the network mode in already created cluster. How can one change or add the already created cluster running in default network mode to VPC native mode?

**Comment by kurtisvg** [comment]
Closing since this isn't related to the Proxy. 

According to the [GKE documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips):
> You cannot migrate a routes-based cluster to a VPC-native cluster.
