### ISSUE TITLE
Incorrect documentation for private-ip configuration

### ISSUE THREAD

**Issue by stevelowery** [GoogleCloudPlatform/cloudsql-proxy#309]
In the documentation on https://cloud.google.com/sql/docs/mysql/sql-proxy#private-ip, it mentions in order to use private networking first, you need to add the option: "--ip_address_types=PRIVATE".  That is actually incorrect.  The correct argument is -ip_address_types=PRIVATE (single slash, not double)

We ran into issues when upgrading our cloudsql-proxy instances because we followed the documentation as stated.

**Comment by kurtisvg** [comment]
Thanks for flagging this. 

Should be fixed now.
