### ISSUE TITLE
"Embeddable" mode for Go applications?

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/cloudsql-proxy#31]
I've written a bit of a hack that allows me to embed the Cloud SQL Proxy into my Go application, so I don't need to set up or run a separate service from my application. I'm planning on releasing this as an open source library, but then I realized: it would be better if the cloudsql-proxy project supported this natively.

Would the maintainers of this project be interested in working with me to merge some patches to make this easy/possible?

If so, I'll try to clean my patch up, sign the CLA, and submit a pull request. If not, I'll release it as my own open source library. Thanks!

**Comment by Carrotman42** [comment]
I may have already added what you're requesting. If you want an easy way to hook into Go's standard database/sql packagem take a look at https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/master/proxy/dialers/mysql, and the example usage at https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/tests/dialers_test.go

Basically, I expose a Dial function which you can use to connect to database instances. If you want to use a different database driver, then you can use the network-level Dial in package proxy and hook into whatever driver you want to. (If you do that, please feel free to send a pull request! I'm happy to support more drivers.)

**Comment by evanj** [comment]
Excellent! Looking at your commit, I think I pulled my version of this project just a few days before it was added. This is awesome! Maybe you should mention it in README.md? Thanks!

**Comment by Carrotman42** [comment]
Good idea!

**Comment by Carrotman42** [comment]
By the way, feel free to send a pull request if there's any functionality you had that wasn't added. Also feel free to file any sort of issue you find with using it as a library.
