### ISSUE TITLE
Use different hosts for different instances: save password

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/cloudsql-proxy#313]
Hi,
I have this case which I'm asking for help, maybe I can get a supporto or provide a feature request.

From my local machine I'm using mySQL workbench to connect to SQL instances of different projects, and as the proxy is working all connections are made on 127.0.0.1. Because the host is the same, workbench always stores the password and replace the previous even, even if with proxy I'm connecting to different projects. At the end I cannot store password of every instance because workbench is replacing the previous one every connection.

Is there a best-practice on how to handle this kind of problem?
Like starting SQL proxy on different host for different projects or something.

Thanks

**Comment by kurtisvg** [comment]
Unfortunately, I don't think there is anything we can do from the proxy side to support this. Looking at the [MySQL Workbench docs](https://dev.mysql.com/doc/workbench/en/wb-mysql-connections-vault.html), it looks it *only* uses the hostname (and not the port), but I think you have a couple different options:

- You can connect using unix sockets - each instance will have a different unix socket path, so it should save the passwords different.
- If you aren't able to connect using unix sockets, it looks like `localhost`, `127.0.0.1` or `::1` count as different hosts, even if they resolve to different locations. 
- If you need more than 3, you could create a local dns entry to direct everything for a certain domain (eg, `*.cloudsqlproxy`) to redirect it to localhost. This would let you do something like `instance1.cloudsqlproxy` and get localhost. (If you don't want to your local dns file, it looks like you can use localhost.tv in a similar way)

Hope this helps.

**Comment by NicolaSpreafico** [comment]
Ok thank you, I will try with a wildcard DNS
