### ISSUE TITLE
GKE Workload Identity Support

### ISSUE THREAD

**Issue by Freyert** [GoogleCloudPlatform/cloudsql-proxy#314]
I was imagining that since `cloudsql-proxy` supports GCE metadata auth it would support GKE Workload identity, but I'm not seeing this work together.

I've verified that my GKE Workload identity is set up and works for `gcloud auth list`.

I'm wondering if anyone has any pointers on how to rectify this as the GKE Workload Identity information is rather sparse.

Would love to make a PR if I can get some good direction and its agreeable!

**Comment by kurtisvg** [comment]
This was done in the Java JDBC SocketFactory [in this PR](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/151). It was done be replacing the auth library included with one that supported GKE Workload identity. 

Right now the auth flow is a bit atypical, but it [starts at this line](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/69852d3cd6a85e1a53617cee0737cc5978ca6db5/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L462). I have no idea if there is an alternative auth library for Go that supports GKE Workload identities, but that is where I would start.

**Comment by Freyert** [comment]
Taking some notes:

1. Main change is migrating auth libraries to [google-auth-library-oauth2-http](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/151/files#diff-357e4854869b2e21c38b1b437f11095aR31)

**Comment by Freyert** [comment]
Well it turns out everything was in order! This was all just some missing permissions and steps on my side. Good to know :)

**Comment by Carrotman42** [comment]
This is nice to know. Earlier I was going to send a snarky email
complaining that whatever GKE Workload identity is doing was different than
what we already supported; now I can just be happy that whatever they are
doing is compatible with what already worked :)

**Comment by Carrotman42** [comment]
Do you mind clarifying which permissions you needed to set up for future
people stumbling upon this issue, in case it's relevant somehow?

**Comment by naseemkullah** [comment]
I am trying to get Workload Identity to work with CloudSQL Proxy but keep getting:

```
error checking scopes: *url.Error Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/scopes: net/http: timeout awaiting response headers | Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/scopes: net/http: timeout awaiting response headers
```

Any help would be appreciated.

Required GSA + role binding for cloudsql.clietn + KSA and KSA annotation are all applied.

**Comment by ndass-sapient** [comment]
@Freyert - Can you please share an example where a cloudsql-proxy sidecar is authenticating using workload identity? I am wondering that goes as argument in container commands. Thanks in advance.

**Comment by kurtisvg** [comment]
@ndass-sapient You don't need to pass an argument - it picks it up as part of the application default credentials.

**Comment by ndass-sapient** [comment]
> @ndass-sapient You don't need to pass an argument - it picks it up as part of the application default credentials.

Thanks @kurtisvg - Yes, I was able to use workload identity, just provided the service account details as part of standard application deployment.
