### ISSUE TITLE
/bin/sh removed from gcr.io/cloudsql-docker/gce-proxy:latest

### ISSUE THREAD

**Issue by jfreeland** [GoogleCloudPlatform/cloudsql-proxy#318]
OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown

I've pinned 1.15 for now, but it's not clear to me if this was intentional.

**Comment by kurtisvg** [comment]
Duplicate of #317
