### ISSUE TITLE
cloudsql proxy disconnect when sql execution exceeds 10 seconds

### ISSUE THREAD

**Issue by chaoyangnz** [GoogleCloudPlatform/cloudsql-proxy#319]
I am using cloudsql proxy to connect to CloudSQL postgres.

I excute a SQL statement which is a bit slow, then I found once it exceeds almost 10 seconds, the connection disconnect. Then I got the error:

```
[Code: 0, SQL State: 08006]  An I/O error occurred while sending to the backend.
```

08006 means `connection_failure`. I suppose there is a timeout setting somewhere, but I don't know how to set.

**Comment by kurtisvg** [comment]
Hi @chaoyangnz - can you please provide some additional details to determine if this is an issue with the proxy or not? 

Did this happen once, or are you able to replicate it? Can you reproduce the same behavior with a `pg_sleep(15)`? 

Is there error you've provided from the proxy, or from your application?

**Comment by chaoyangnz** [comment]
sorry, that is my fault. I got an incorrect SQL making Cloud SQL crash.
close this.

**Comment by Carrotman42** [comment]
I'm kinda surprised that you were able to make the database crash with a
query. I'd be interested in what the query was, if you're able to share it.

**Comment by chaoyangnz** [comment]
not the SQL actually, it is my misuse of trigger.

In postgres trigger i update a column, which then trigger the trigger itself. It ends up a n infinite calls of the trigger and crash the process and connection is disconnected.

**Comment by Carrotman42** [comment]
Ah yes, makes sense. Glad to hear you found the problem, thanks for
updating the bug with your root cause.
