### ISSUE TITLE
cloud_sql_proxy --version returns NO_VERSION_SET

### ISSUE THREAD

**Issue by bseib** [GoogleCloudPlatform/cloudsql-proxy#325]
I have built cloud_sql_proxy on FreeBSD, and when I run `cloud_sql_proxy --version` it returns `NO_VERSION_SET`.

```
cloud_sql_proxy --version
Cloud SQL Proxy: NO_VERSION_SET
```

I was expecting a version number.

I haven't looked at the source yet to see what might be happening.

**Comment by Carrotman42** [comment]
The version is completely human defined at build time, it is not in the
source tree itself so compiling from the source tree will have the
functionality you mention. Searching the source for "NO_VERSION_SET" in the
source tree should reveal what is happening.

Note that the "go build" command (and similar "go" compiling commands) has
no native notion of git, so even having some SHA printed out of --version
would be impossible without a wrapper script.

You can write your own wrapper script, or use the one in the repo already
which probably does something similar to what you want:
https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/cmd/cloud_sql_proxy/build.sh

**Comment by bseib** [comment]
Great explanation. I think this is a non-issue and I'll close it.
