### ISSUE TITLE
Cannot connect to Postgres via Docker Image proxy

### ISSUE THREAD

**Issue by jckw** [GoogleCloudPlatform/cloudsql-proxy#328]
Whilst I can connect to the db using ./cloud_sql_proxy from my local machine, I cannot connect to the DB from inside a GKE pod. Instead, I'm met with the following error (from a Django server):

```
django.db.utils.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

My config file uses the standard cloud proxy docker image:

```
        # [START proxy_container]
        - image: gcr.io/cloudsql-docker/gce-proxy:1.05
          name: cloudsql-proxy
          command:
            [
              "/cloud_sql_proxy",
              "--dir=/cloudsql",
              "-instances=cardea-gcp:europe-west2:huxley-db=tcp:5432",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          volumeMounts:
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
        # [END proxy_container]
```

This is proving to be particularly difficult to debug as I can't reproduce it locally using the cloud proxy script -- everything works fine.

I assume that this is some networking issue between GKE and Cloud SQL, but I don't believe I changed any settings when this issue began occurring (note it worked well before then!).

There are no error/warning logs in Cloud SQL suggesting that GKE doesn't actually reach Cloud SQL at all.

Any help is hugely appreciated!

**Comment by bobsoppe** [comment]
If you update the proxy to the latest `1.16` version, does that work?
As far as I know, the old `1.05` version is not able to connect anymore as it uses old endpoints

**Comment by jckw** [comment]
Yes! That worked.

Thank you!!

**Comment by bobsoppe** [comment]
@jckw could you leave this one open? As I would like to know what the reason is why it is not working anymore

**Comment by jckw** [comment]
Sure! Reopening to look into why this is the case

**Comment by Carrotman42** [comment]
1.05 is so old it doesn't even have support for postgres. It came out before that feature was implemented.

1.07 is the first time Postgres is usable: https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases/tag/1.07

I don't think there's anything else to do here; using software that was compiled more than 2 years ago is not a good idea if there's a newer option anyway.

**Comment by kurtisvg** [comment]
I'm going to mark as closed since @Carrotman42's answer is likely correct. 

In general, it's more helpful if you provide logs or/and error messages to help determine a root cause.
