### ISSUE TITLE
Cloud Proxy 404s on SQL Admin API call - client base path has updated

### ISSUE THREAD

**Issue by nsf** [GoogleCloudPlatform/cloudsql-proxy#331]
https://github.com/googleapis/google-api-go-client/commit/8a410c21381766a810817fd6200fce8838ecb277#diff-fc3696d32750cf4e3f741d7d50fda5f4L79-R79
the diff is too big, but 5 days ago this happened:
```diff
- const basePath = "https://www.googleapis.com/sql/v1beta4/"
+ const basePath = "https://sqladmin.googleapis.com/"
```
And cloudsql proxy dialer ends up here:
https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/46c5533ff5bad7ea6a5e4966a670249d299f5880/proxy/proxy/dial.go#L75

Which creates the cert source with forced API path which is now wrong since google API version v0.14.0.

Note that you don't actually need to provide the path, empty string should work fine and it will use the default from the api:
https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/46c5533ff5bad7ea6a5e4966a670249d299f5880/proxy/certs/certs.go#L83-L89

As a consequence of that if using default dialer proxy with latest API, you'll get errors like so:
> The requested URL <code>/**sql/v1beta4/sql/v1beta4**/projects/{project_id}/instances/{instance}/createEphemeral?alt=json&amp;prettyPrint=false</code> was not found on this server.

**Comment by kurtisvg** [comment]
Also raised in https://github.com/googleapis/google-api-go-client/issues/427

**Comment by kurtisvg** [comment]
I was actually able to reproduce this by starting in a docker container as opposed to my local copy for some reason:
```sh
$ docker run --rm -it golang:1
$ go get github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy
```
I confirmed it cloned at 231cffdfe5a16e0f922416ceb095f2c28783ad2d, then built the proxy (`go build` from `/go/src/github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy`)  and saw the following:
```sh
$ go: extracting google.golang.org/api v0.15.0
```

Then running the proxy (`/go/bin/cloud_sql_proxy -instances=project:region:instance=tcp:3306`):
```
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/sql/v1beta4/sql/v1beta4/projects/project/instances/instance?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>
```

Not quite sure why it works locally - I'm going to reopen and dedup against #331.

**Comment by kurtisvg** [comment]
The issue turned out to be the default value for `-host` was still set, which was causing a problem with the binary as an executable (but not with the dialer).

This probably underscores our need for an e2e presubmit test to better prevent issues like this in the future.
