### ISSUE TITLE
The cloud proxy has suddenly started using host user to connect

### ISSUE THREAD

**Issue by vongohren** [GoogleCloudPlatform/cloudsql-proxy#333]
I have never had any problems with this before, but now it is struggeling to connect to my database because it doesnt find the role 'X'.

X is the username of my mac.

I tried making a role for this user just to get past it, but it requires a password as well, and I have no idea where it is fetching that from.

But the question is, why has it started doing this?
I need to be able to connect to the SQL for doing analasis, migrations and other things. But now im locked out of it :O

This is my command, obfuscated a bit:
`./cloud_sql_proxy_mac -instances="dev-instance:europe-west1:dev-postgres-instance"=tcp:5432 --credential_file="./dev-instance-f697f46f3a88.json"

**Comment by kurtisvg** [comment]
The proxy doesn't interact with the database user at all - can you provide more details on the error you are seeing and full list of steps needed to reproduce?

**Comment by Carrotman42** [comment]
Including what client you are using to connect to the database through the proxy.

**Comment by vongohren** [comment]
@kurtisvg @Carrotman42 yes of course. Im running now the newest mac client from this repo release. But it first happened with a version that was quite much older, 1.5 year maybe.
Im using this to just initiate a connection, so I can do migrations, or connect with my pg admin 4

This is how I run it. And there you can see it is retrying like crazy. If I let it stand for a minute it retries many many times.
<img width="1085" alt="Screenshot 2019-11-26 at 22 26 41" src="https://user-images.githubusercontent.com/1012055/69674432-c092a500-109c-11ea-90af-e8d40499fe75.png">

This is what the log provides me.
<img width="1424" alt="Screenshot 2019-11-26 at 22 27 27" src="https://user-images.githubusercontent.com/1012055/69674464-cbe5d080-109c-11ea-84bf-1bb0f472ef40.png">

You can see the user "snorre" there. This is nothing I have provided to google, or im providing to the config. But for some reason it picks this up. This username is only been used on my personal mac, nowhere else. So I have no idea why it is picking this up. The reason it says that the password is wrong, is because I created a role with this name in the DB to see if I got further. But dont know what password to put. Tried the local password, that did not work.

Does this help, or is it anything else I can provide?

**Comment by kurtisvg** [comment]
So this error is unrelated for the proxy - the proxy only wraps the incoming connection and forwards it to the database. 

If the connection isn't coming from you, something on your system is attempting to connect to `127.0.0.1:5432` repeatedly, using your machines username. Since `5432` is the default port for Postgres, you can probably avoid seeing the error by switching to a different port (like `5433`). However it's probably worth investigating what's trying to make the connection in the first place, on the off chance it's a malicious actor. 

I'm going to mark this as closed since it's unrelated the proxy - but feel free to keep commenting if there is something specific we can help with.

**Comment by vongohren** [comment]
Ok, thanks for info. The reason this started happening now is because I updated https://github.com/postgres/pgadmin4 server to a newer version. And I guess this new version did something different than the later version where this did not happen. So that was what confusing. Shutting down the server, makes the proxy work fine again.
 
So just need to see why this happened now, so I can get my workflow back.
