### ISSUE TITLE
unable to use IAP tunnel to GKE hosted cloud-proxy

### ISSUE THREAD

**Issue by scottwallred** [GoogleCloudPlatform/cloudsql-proxy#337]
Running cloud-proxy in a GKE private cluster, which is exposed through a nodePort.  When attempting to create an IAP tunnel from my local machine to the nodePort pointing to the port for cloud-proxy, the IAP tunnel does not seem able to connect to the cloud-proxy entry-point.  

I have verified that if I use a kubectl port forward to the exposed service that connectivity is available to the DB.  Have also verified that a tcpecho app running on the same GKE node can be connected too through an IAP tunnel.

**Comment by kurtisvg** [comment]
Sorry I'm not of more help, but I'm totally unfamiliar with the IAP tunnel for GKE (and this question is pretty unrelated to the proxy itself, so I'm going to mark as closed.)

It might be worth pointing out that there really isn't any advantage to using an IAP tunnel on top of the Cloud SQL proxy - the proxy only provides IAM authentication (so special connection paths), so it's somewhat redundant to stack them.
