### ISSUE TITLE
x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by thomasdereyck** [GoogleCloudPlatform/cloudsql-proxy#341]
Hello,

I am using the cloud_sql_proxy client (on macOS 10.15.2) to connect to a Postgresql instance in Google Cloud Platform. In the past, I was able to set up the proxy with the following command:

`cloud_sql_proxy -projects projectname -dir /path/to/socketdir`

However, this method has stopped working, and I get the following error:

```
2020/01/04 14:46:25 Error listing instances in projectname: Get https://www.googleapis.com/sql/v1beta4/projects/projectname/instances?alt=json&prettyPrint=false: x509: failed to load system roots and no roots provided; exit status 49
2020/01/04 14:46:25 no Cloud SQL Instances found in these projects: [projectname]
```

I tried updating cloud_sql_proxy to the latest version, but this doesn't resolve the issue.

"gcloud sql instances list" lists the instance without an issue.

I don't think I've made any significant changes to my system, so I'm wondering if this is a bug in the client itself?

**Comment by Carrotman42** [comment]
Clarification: some Cloud SQL Proxy client (version X) worked in the past,
and then that same version stopped working?

You later talk about double-checking the latest version, so for
completeness: what version is the "version X" you initially noticed the
problem on?

**Comment by thomasdereyck** [comment]
Dear Kevin,

Thanks for your swift reply. Apologies for the lack of information, please allow me the fill in the blanks:

I was using version 1.13 successfully for a long time. Indeed, that version then stopped working. I then updated to the current version 1.16, but this did not solve the issue.

I also updated the gcloud tools from version 238.0.0 to current version 274.0.1. This also did not have an effect.

**Comment by kurtisvg** [comment]
This error means that your local environment doesn't provide the ca-certificates needed for the x509 library. Are you using a docker container? Typically I've seen this when running in a container with no certs installed. Normally you can fix it with the following"
```
```

**Comment by thomasdereyck** [comment]
Hi Kurtis,

Yes, that's the strange thing. I'm not running this in a container, but directly on macOS to enable the development workflow for a web application I'm developing. Used to work just fine, and now suddenly it doesn't find those certificates anymore. I can't really imagine what triggered this, as I don't think my environment changed since the last time this worked. Then again, there may be so many factors...

I'm not compiling myself, just using the versions provided through the Google Cloud documentation and on this Github repo's releases page.

If I understand correctly, on macOS the Go standard library shouldn't be looking in the /etc/ssl/certs folder (which is, and has always been empty, on my device), but access the same database that Keychain Access is using. Is there a way I can debug this process or make it a bit more verbose?

**Comment by kurtisvg** [comment]
> If I understand correctly, on macOS the Go standard library shouldn't be looking in the /etc/ssl/certs folder (which is, and has always been empty, on my device), but access the same database that Keychain Access is using. Is there a way I can debug this process or make it a bit more verbose?

Unfortunately, since it's a dependency I don't think there is any easy way to do so. There is a similar thread [here](https://github.com/golang/go/issues/24147) which mentions setting `GODEBUG=x509roots=1`, but my guess is that is probably a compile time only flag. 

I'm unable to replicate this on my macbook, so it sounds like unfortunately it sounds like something in your local environment that isn't working correctly. I'd suggest reading through that thread, perhaps a setting in your local keychain has been changed that's preventing it from working correctly.

**Comment by Carrotman42** [comment]
GODEBUG is an environment variable, not a compile-time flag. The source for the latest Go stdlib shows that setting `GODEBUG=x509roots=1` does cause extra info to be printed out to stderr: https://golang.org/src/crypto/x509/root_darwin.go .

I do suggest setting that env variable before starting the cloud_sql_proxy process, and hopefully more information is printed out.

Given that this started to not work with no changes to the cloud_sql_proxy version, I agree with Kurtis that this is likely not a proxy-specific problem. But, hopefully the GODEBUG option that Kurtis found will be able to help you dig deeper.

**Comment by thomasdereyck** [comment]
Thanks for the suggestions. I tried running the proxy with GODEBUG set and it only resulted in the following additional line:

`crypto/x509: 5 certs have a trust policy`

I agree that it's probably something in my environment. Unfortunately it does not seem easy to debug. I'll keep digging and if I find something I'll document it here as a reference.

Many thanks!

**Comment by maxekman** [comment]
I have the same issue when running the proxy on MacOS 10.15.4:

`crypto/x509: 5 certs have a trust policy`

I can see some non-trusted Adobe certs in my login keychain which I'm unable to remove at the moment. Not sure if that is the cause here.

<img width="542" alt="Screen Shot 2020-04-15 at 09 14 52" src="https://user-images.githubusercontent.com/821518/79308815-92055180-7ef9-11ea-99c4-7c5f1cb493b5.png">

**Comment by thomasdereyck** [comment]
I recently picked up the project again where I encountered this issue, and managed to fix this. Similar to maxekman I had a few certificates in my login keychain that I could not delete. Perusing the Go source code I noticed that Go uses the macOS "security" command to dump and then process trust settings. Using "security" myself to try to delete the undeletable certificates always resulted in errors. "security dump-keychain" showed many items but ended with some indication that the keychain was invalid.

I thus suspected that the output required for Go was either malformed (because of error messages) or trimmed at the first error. I thus reluctantly resorted to resetting my login keychain via Keychain Access --> Preferences --> Reset My Default Keychains. After resetting, the undeletable certificates are gone (unfortunately so are all other passwords that you didn't export first) and cloud_sql_proxy works properly again.

**Comment by maxekman** [comment]
I’m currently hoping this will go away when Go 1.15 is used, check out the crypto/x509 section regarding macOS: https://golang.org/doc/go1.15#minor_library_changes

**Comment by maxekman** [comment]
I'm still not sure what caused all my problems, in the end I couldn't even fetch using `go get`! I solved it by creating a new keychain using Keychain Access and copying over all items that I could (some keys failed, which could've been the issue). After renaming the new keychain to `login.keychain-db` (and moving out the old one) it now works!
