### ISSUE TITLE
Usage with ProxySQL in Kubernetes

### ISSUE THREAD

**Issue by mralanlee** [GoogleCloudPlatform/cloudsql-proxy#349]
I currently have an application that uses a service which doesn't support separate read and read/write endpoints to leverage CloudSQL read replicas. I was wondering if I could use, (and curious if this would the most optimal solution), the cloudsql proxy as a sidecar container for ProxySQL and have it reach my pool of instances.

In the sidecar container, I could have it run something along the lines of:
```
./cloud_sql_proxy -dir=/cloudsql -instances=my-project:us-central1:<master-instance>,my-project:us-central1:<read-rep-1>,my-project:us-central1:<read-rep-2>
```

Thanks in advance.

**Comment by kurtisvg** [comment]
I can't say I've ever tried it, but this would be my suggested method for accomplishing this.  

Please feel free to update this issue if you run into any specific issues.
