### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by quinn** [GoogleCloudPlatform/cloudsql-proxy#350]
container is going into crash loop, but no log output of any kind. :(

**Comment by kurtisvg** [comment]
The crash loop is a kubernetes phenomenon, and unrelated to the proxy.

Check out this link that gives some tips around diagnosing errors causing `CrashLoopBackOff`: https://sysdig.com/blog/debug-kubernetes-crashloopbackoff/

**Comment by quinn** [comment]
thanks for googling "crash loop backoff" for me @kurtisvg. Here's a new ticket: https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/351
