### ISSUE TITLE
Connecting from a GKE container to a database in a different project

### ISSUE THREAD

**Issue by AeroNotix** [GoogleCloudPlatform/cloudsql-proxy#363]
Hi,

I'm trying to use cloudsql-proxy to connect from GKE cluster attached to project A, to a database in a different project B.

I am passing a service account  as a credentials file which has an IAM role enabled for cloudsql editor and cloudsql client in project B.

When I start the cloudsql_proxy I receive:

```
Error during createEphemeral for project-b:us-central1:database-name: googleapi: Error 403: Cloud SQL Admin API has not been used in project $PROJECT_A_ID before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=$PROJECT_A_ID then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

What's weird is that if I look through the code for where the `createEphemeral` is called:

https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/887a30e53f599db6cec6a781fd99960d76cc0ae0/proxy/certs/certs.go#L172-L177

It's strange that it's not able to connect and that the Project ID it is complaining about is for project A, not project B. The code just splits the instance string I pass to on the cli to get the project ID.

Project A does not have CloudSQL Admin API enabled. If I enable it, then everything works as expected. I do not want CloudSQL Admin API enabled on Project A.

**Comment by Carrotman42** [comment]
In my experience if you have some resource in PROJECT_A which tries to access API_X, then you must have API_X enabled in PROJECT_A. As far as I know, it does not matter /how/ you are using this API: "enabling" an API means "resources in this project are allowed to talk to this API"; there's no "deeper look" into what the API is trying to do before this "enable" bit is checked. This happens on the backend, which is probably why you mentioned it was strange that the Proxy code does not imply this could happen.

Is there a specific reason you don't want to enable the Cloud SQL API in Project A? From my perspective, what you described does indeed show Project A using that API even if it is using that API to access resources from a different project, so if you could spell out your concerns a bit we may be able to help.

**Comment by kurtisvg** [comment]
This is a Cloud SQL Admin API issue and outside the scope of the Cloud SQL proxy itself. 

You can use the [Cloud SQL issue tracker](https://cloud.google.com/support/docs/issue-trackers) to open an issue if you think this behavior is unwanted. Feel free to cross post the ID here if you choose to do so.
