### ISSUE TITLE
Cloud SQL Private IP through Cloud Proxy fails

### ISSUE THREAD

**Issue by hussainak** [GoogleCloudPlatform/cloudsql-proxy#365]
Hi there,

I am trying to connect MySQL 5.7 instance that has a private IP only using my OSX terminal. The Cloud SQL Proxy starts fine using the command with PRIVATE flag. I have tried connecting 3 different clients but I am getting the following error:

`Creating a session to 'root@127.0.0.1:3306'
ArgumentError: X protocol error: MySQL server has gone away
Classic protocol error: MySQL Error 2013 (HY000): Lost connection to MySQL server at 'waiting for initial communication packet', system error: 60`

**Comment by hussainak** [comment]
My understanding is that I should not require an Interconnect or VPN for this to work, if I do then there is no need for a Cloud SQL Proxy as the private IP Cloud SQL would then be local to my network.

I am relying on this diagram for my connection to remain private only:
![image](https://user-images.githubusercontent.com/1008911/77398055-da4dba00-6dfa-11ea-9993-5ffa7c79cbc0.png)
As described here: https://cloud.google.com/sql/docs/mysql/sql-proxy

I am using the -ip_address_types=PRIVATE flag when starting the proxy.

**Comment by Carrotman42** [comment]
What logs are printed from the Cloud SQL Proxy?

**Comment by kurtisvg** [comment]
> My understanding is that I should not require an Interconnect or VPN for this to work, if I do then there is no need for a Cloud SQL Proxy as the private IP Cloud SQL would then be local to my network.

The Cloud SQL proxy only provides authentication to allow you to create connections. It doesn't let you connect unless you have access to the IP. In this case, you can't connect to a private IP unless you have access to the VPC. See the [Requirements for Private IP](https://cloud.google.com/sql/docs/mysql/private-ip#requirements_for_private_ip) section in our docs.
