### ISSUE TITLE
.Net Nuget Package

### ISSUE THREAD

**Issue by elachlan** [GoogleCloudPlatform/cloudsql-proxy#368]
We have been working on a .Net Core/Framework wrapper of the proxy. The cloudsql-proxy code was changed to compile it into a shared library, which we then use p/invoke to interact with. It is still a work in progress, but we believe it will be useful to the community.

We have made this code available via: https://github.com/expert1-pty-ltd/cloudsql-proxy
The nuget package can be found at: https://www.nuget.org/packages/cloudsql-proxy-cs/1.0.1

**Comment by kurtisvg** [comment]
This looks pretty interesting - could you update the README to include info instructions for using it and what advantageous there might be over running the proxy? If you want we can list this as a third party repo in the README. 

FYI @dmahugh - you may find this interesting

**Comment by elachlan** [comment]
@kurtisvg Thanks for having a look. The advantage is that the .net app can directly manage the proxy. We basically wanted to use it in our winforms application to provide database access. With a nuget package it makes it really easy to add to our application and program to it. 

We wanted a way to easily open/close the proxy with the lifecycle of our application. If the application crashes, we didn't want the proxy to remain open. Since the users aren't tech savy, packaging the proxy inside the app has it "just work". We can have our application login to our API and pull down the auth details for the proxy, then launch the proxy.

This probably could have been done with a shell execute, but then we would have had a floating command window. A windows service would have worked as well, but I am unsure if you can pass the connection information directly to the service and then start it as an average user.

I have updated the README and pointed back to this repo. We will probably restructure it this week and make the example more obvious as well as add it to the README.

**Comment by kurtisvg** [comment]
Feel free to add it to our "[Third Party](https://github.com/GoogleCloudPlatform/cloudsql-proxy#third-party)" section if you want to open a PR

**Comment by elachlan** [comment]
Hi Kurtis, we have been busy the last two weeks on it. The proxy can now be created with a using statement and allocate a port at runtime. This effectively allows a developer to connect to any number of proxy endpoints from within their dot net program.

I'll get around to the PR hopefully soon.
