### ISSUE TITLE
Question about using a password

### ISSUE THREAD

**Issue by gregmsanderson** [GoogleCloudPlatform/cloudsql-proxy#373]
Hello,

Quick question which I wasn't clear about:

On https://cloud.google.com/sql/docs/mysql/sql-proxy#requirements it says 

> "You must provide the proxy with a valid database user account and password"

 but on https://cloud.google.com/sql/docs/mysql/sql-proxy#user it says 

> "you can create a user account that can be used only by the proxy. The advantage of doing this is that you can specify this account without a password without compromising the security of your instance or your data"

... so is a password required? I would assume adding a password adds an extra layer of protection so it's a good idea to have one. Am II right in thinking if the user the proxy is connecting as has a password, you do need to provide it else it won't connect?

**Comment by kurtisvg** [comment]
Currently, the proxy doesn't do any interference with the DB protocol. This means that if you database user doesn't have a password, you won't need one to log in. Personally, I would recommend using one. 

The doc should properly say "a valid database user account (and password if required)". I've filed an internal issue to correct this on this page. Thanks!
