### ISSUE TITLE
cloud_sql_proxy running in docker container halts after a few days, stays in "stuck" state until restart

### ISSUE THREAD

**Issue by yuzeh** [GoogleCloudPlatform/cloudsql-proxy#379]
## Bug Description

I'm running `cloud_sql_proxy` in a container as part of a docker-compose deploy.
I'm experiencing an issue where the docker container ends up in a "stuck" state every couple of days. It doesn't respond to `docker stop`, `docker kill`, etc.
The only thing I can seem to do is to is to restart the whole docker-compose deploy.

Honestly at a loss for what to do to debug further.

I've compiled a debug version of the `cloud_sql_proxy` binary that includes all of the debug symbols and also includes a copy of delve.... but I have no experience with Go (and relatively low experience with docker), so I'm not sure what I should be looking for in terms of debugging.

Any help would be excellent!

## Stacktrace

No actual trace, but here is a log of me trying to dig around into the "stuck" container with delve. "Thread 7" seems to have blocked on a logging call?

![cloudsqlproxy-delve](https://user-images.githubusercontent.com/351023/79707522-9d49db80-8271-11ea-8180-bd32d2b63cc1.png)

## How to reproduce

  1. (... yeah. beats me.)

## Environment

1. OS type and version: Docker runtime, Ubuntu host.
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.17-dev (Docker image built from https://github.com/north-beam/cloudsql-proxy/tree/nb-debug-mode)

**Comment by Carrotman42** [comment]
Can you verify that detaching/reattaching with delve shows that the
relevant goroutines in the Proxy are indeed consistently stuck at the same
point?

Can you describe the logging configuration of the container/docker?

In my experience, if a program is indefinitely blocked on logging, some log
buffer (e.g. in memory, or on disk, etc) is full and it is waiting for
space before the write returns. For example, if the system is configured to
write logs to disk but the disk is full, writes may block until there is
available disk space.

If this blocking is the cause, disabling verbose logging in the Proxy (with
-verbose=false iirc) could help confirm it: setting that flag would reduce
the number of logs emitted, and if my theory is correct then the Proxy
should stay up longer before getting stuck. This is a bandage, not a good
solution though; it would be good to figure out the root cause of why the
logging blocks in the first place.

**Comment by yuzeh** [comment]
Hi, thanks for responding!

> Can you verify that detaching/reattaching with delve shows that the
> relevant goroutines in the Proxy are indeed consistently stuck at the same
> point?

I did confirm this while debugging yesterday, both by 1) hitting `c` while in delve and then `^c` after a few seconds, and 2) detatching and reattaching delve as you mentioned. I can't be 100% sure for the other threads, but "Thread 7" was definitely stuck in the same place.

> Can you describe the logging configuration of the container/docker?

It's directly logging to the container logs (accessible via `docker logs`). I'm running docker 18.09.9 (installed via snap), with no special configuration for logging in `daemon.json`.

After this last incident, I set these logging parameters in `daemon.json`:

```
    "log-driver":       "json-file",
    "log-opts": {
            "max-size": "1m",
            "max-file": "3"
    },
```

I got these after doing a few searches for "docker log rotation" and I expect this configuration to do some sort of log rotation.

> If this blocking is the cause, disabling verbose logging in the Proxy (with
> -verbose=false iirc) could help confirm it: setting that flag would reduce
> the number of logs emitted, and if my theory is correct then the Proxy
> should stay up longer before getting stuck. This is a bandage, not a good
> solution though; it would be good to figure out the root cause of why the
> logging blocks in the first place.

I was hoping to not have to do this; by removing the logs I would not be able to determine when exactly the incident occurred. I'd have to rely on `psql` clients, which is a bit hairy in my case.

Right now I have to reboot my entire docker-compose deploy every 3-5 days; if I were to disable logs, I'd expect the deploy to stay running smoothly for over a week to have confidence that logging is the real issue.

In any case, my Proxy is not running with `-verbose=false` right now (I'm hoping the docker log rotation fixes my immediate issue). I'll update this ticket if anything interesting comes up.

**Comment by kurtisvg** [comment]
Just to clarify - the behavior existed in `1.16` as well before you moved to `1.17-dev`?

**Comment by yuzeh** [comment]
Yep.

**Comment by yuzeh** [comment]
Incident happened again. Was not in a position to be able to live debug, so I've turned logging off and restarted the docker-compose deploy.

Will update if anything interesting happens.

**Comment by yuzeh** [comment]
Following up on this ticket: After turning verbose mode off in the container, things have been stable for a bit over 2 weeks.

I think it's clear the issue has something to do with writing to disk, but it's not clear whether it's `cloudsql-proxy`'s fault, or if the issue lies with my docker setup.

One way I could test this is to have my docker-compose deploy connect to a `cloudsql-proxy` that's running on the host (as opposed to running on a docker container), but this unfortunately is not worth my time; I'm just moving forward without logging for the time being.

Happy to close this one out.

**Comment by Carrotman42** [comment]
I think the best way to narrow down what the "real problem" is is to launch
a docker container configured almost exactly the same as the Proxy, but
instead have it execute "echo foobar-$(date)" in a tight bash loop. If it
starts blocking in the same way the Proxy did, that would imply the problem
is in how your logs are setup and that it doesn't really relate to the
Proxy directly. In addition, if it does show the issue, that
logspam-container should also reproduce the blocking problem much faster,
giving you an easier/faster way to iterate on the solution while also
avoiding affecting your production service.

**Comment by enocom** [comment]
Closing this as stale. Feel free to re-open if the issue pops up again.
