### ISSUE TITLE
"fusermount": executable not found in $PATH

### ISSUE THREAD

**Issue by itaigev** [GoogleCloudPlatform/cloudsql-proxy#38]
Hello,

I am trying to start a docker container using the -fuse switch as follows:
`docker run -it -v $(pwd)/cred.json:/secret/cred.json -v /cloudsql -v /etc/ssl/certs b.gcr.io/cloudsql-docker/gce-proxy /cloud_sql_proxy -dir=/cloudsql -fuse -credential_file=/secret/cred.json`
And I get the following error:
`2016/07/11 16:24:48 Mounting /cloudsql...
2016/07/11 16:24:48 Could not start fuse directory at "/cloudsql": cannot mount "/cloudsql": fusermount: exec: "fusermount": executable file not found in $PATH`

Could be missing dependencies in the docker image?
Thanks in advance.

**Comment by Carrotman42** [comment]
The docker image provided does not include support for FUSE. In fact, at least of docker 1.09, FUSE doesn't work through docker anyway. You can specify instances you want to connect to using -instances, or project -projects to have the proxy look for instances in those projects.

**Comment by itaigev** [comment]
Got it.  -instances worked great. Thanks.

**Comment by Carrotman42** [comment]
Let me know if there's anything else I can do!

**Comment by porridge** [comment]
Can you please reconsider this issue? FUSE works fine inside kubernetes pods. You just need to specify:
```
securityContext:
  privileged: true
```
in your container spec. We use GCSFuse in a k8s deployment just fine.

It would be great not to have to build one's own cloudsql-proxy image just for this. We have plenty of Cloud SQL instances coming and going, and their list differs between the various GCE projects we run, so -fuse is a perfect fit for us.

**Comment by porridge** [comment]
So it turns out that while FUSE works on docker and k8s these days, accessing a FUSE filesystem in a neighboring container does not. So ``-fuse`` is not currently usable on k8s. But maybe it will be at some point: https://github.com/kubernetes/kubernetes/pull/20698#issuecomment-234720829
