### ISSUE TITLE
Enforce using proxy with private IP

### ISSUE THREAD

**Issue by snuggie12** [GoogleCloudPlatform/cloudsql-proxy#381]
## Question
Is there any way to enforce a client to use the proxy to connect to a cloud sql instance? I created a new cloud sql instance and was able to psql to the private IP and no GCP user was required.

## Additional Context
If there is no way to enforce it on the cloud sql/proxy side, is there a document with best practices to lock down with some other mechanism like firewall rules?

**Comment by kurtisvg** [comment]
You can require a specific user to use the proxy by setting their hostname in the DB engine as the following:

```
'[USER_NAME]'@'cloudsqlproxy~%'
```

**Comment by kurtisvg** [comment]
Additionally, you could set up a [VPC egress firewall rule](https://cloud.google.com/vpc/docs/firewalls) to only allow connections to your instances private IP on port `3307` (this is the port used by the proxy, regardless of database type).

**Comment by snuggie12** [comment]
> Additionally, you could set up a [VPC egress firewall rule](https://cloud.google.com/vpc/docs/firewalls) to only allow connections to your instances private IP on port `3307` (this is the port used by the proxy, regardless of database type).

Thanks so much! This is really helpful information. I had found the user stuff, but for networking I had tried the postgres port +1 and that did not work. Good to know the proxy always uses 3307.

**Comment by ejose19** [comment]
> Additionally, you could set up a [VPC egress firewall rule](https://cloud.google.com/vpc/docs/firewalls) to only allow connections to your instances private IP on port `3307` (this is the port used by the proxy, regardless of database type).

This should be in the documentation, as I was looking for more reasons to use the proxy when the DB is already using private ip, leaving only encryption the only factor over direct ip (which on private ip may not be sufficient). But if we also add that we can allow connections to ONLY come from the proxy and not direct ip, then it may worth it. Here's the 2 rules I had to create in order to enforce it:

```
Name                        Type      Targets              Filters        Protocols/ports         Action       Priority     Network
proxied-cloudsql           Egress   Apply to All            *1                tcp:3307            Allow          999           *2
unproxied-cloudsql         Egress   Apply to All            *1                  all               Deny          1000           *2

*1 = Your cloud sql ip range
*2 = Your cloud sql network
```

After that, you can verify that trying to connect over direct ip timeouts, but using the proxy works correctly.
