### ISSUE TITLE
v1.17 not verified and not go get'able

### ISSUE THREAD

**Issue by torbjornvatn** [GoogleCloudPlatform/cloudsql-proxy#397]
## Bug Description

I try to use the newest version (v1.17) of cloudsql as library in my Go code, but `go get` can't find it.
I see from the [tags page](https://github.com/GoogleCloudPlatform/cloudsql-proxy/tags) that `v1.17` isn't marked as Verified. Could that be the problem?

## Example code (or command)
```
go get github.com/GoogleCloudPlatform/cloudsql-proxy@v1.17   
```

## Stacktrace
```
go get github.com/GoogleCloudPlatform/cloudsql-proxy@v1.17: no matching versions for query "v1.17"
```

## How to reproduce
Run `go get github.com/GoogleCloudPlatform/cloudsql-proxy@v1.17 `

## Environment

1. OS type and version: macOS 10.15.4
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): v1.17

**Comment by torbjornvatn** [comment]
And I'm also curious why the go.mod entry becomes `github.com/GoogleCloudPlatform/cloudsql-proxy v0.0.0-20200513164142-a9864b03c326`.
Is it because the tags aren't on the form `v1.2.3`?

**Comment by kurtisvg** [comment]
Yes, apparently `go get` expects _full_ semantic versioning and ignores the tag if not. We will need to add new tags for the previous versions and make sure going forward we are using the new tags.

**Comment by kurtisvg** [comment]
I'm not sure if this is a recent change to something in the Go environment (seems unlikely we've had it wrong all this time and no one else has raised an issue), but I've retagged all the existing issues into the correct format. 

So now `go get github.com/GoogleCloudPlatform/cloudsql-proxy@v1.17` works correctly.
