### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by thecodeassassin** [GoogleCloudPlatform/cloudsql-proxy#40]
i start the sql proxy using the following command:

> exec cloud_sql_proxy -dir=/cloudsql -instances=project:database

When the website is loaded the CPU usage of the proxy rises exponentially. Is there any way around this?

**Comment by thecodeassassin** [comment]
does anybody know anything about this? The high cpu usage causes this to be unable in production.

**Comment by Carrotman42** [comment]
What sort of qps are you achieving? Is your app continually opening and
closing database connections? Try out using connection pooling, it is
significantly more efficient all the way down the stack.

One thing you can try, since I noticed from another issue you are compiling
the proxy: you can try to link in pprof and find the hotspots you're
hitting in the code. I'd be happy to look into the bottleneck you're
hitting if you can provide me with data to help track it down.

**Comment by Carrotman42** [comment]
If you're willing to do the legwork to identify the hotspots of your code, you can read through this post about adding pprof to any Go program to automatically profile CPU (and memory) usage. The post is relatively long, but the part you're interested in are adding these lines to func main:

        f, err := os.Create("some-path-to-a-file-you-own.prof")
        if err != nil {
            log.Fatal(err)
        }
        pprof.StartCPUProfile(f)
        defer pprof.StopCPUProfile()

After recompiling the proxy and running it in a scenario where it has encountered the high CPU, kill the proxy process and look through data given by the pprof tool:

go   tool   pprof   the-locally-compiled-proxy-executable   some-path-to-a-file-you-own.prof

There's a few simple commands to look through the data (`top10` or `web` for example), but if you don't have time to look through the data, feel free to email the profile output (`some-path-to-a-file-you-own.prof`) to cloud-sql@google.com and I'll try to interpret what's going on.

**Comment by Carrotman42** [comment]
Please let me know if there's anything you've found related to this problem. I've not heard about this being a problem so I'm going to optimistically close this. Please reopen it if you are still having a problem.

**Comment by Carrotman42** [comment]
Can you please answer the questions I asked in the previous posts? It is
not possible to help you with the info you have provided.
