### ISSUE TITLE
Bind address option not documented

### ISSUE THREAD

**Issue by palimarium** [GoogleCloudPlatform/cloudsql-proxy#401]
## Description

In order to allow  multiple instances or to make the port accessible from outside of the Docker container you have to bind cloud sql proxy to tcp:0.0.0.0:<PORT_NUMBER>, but this setting is not documented in the help of the script or in the documentation page.

---

❯ ./cloud_sql_proxy --version
Cloud SQL Proxy: version 1.16; sha e802c2cb94aec939bfe7497637c5685d3dddd6af built Wed Oct  9 22:22:13 UTC 2019
❯ ./cloud_sql_proxy --help

The Cloud SQL Proxy allows simple, secure connectivity to Google Cloud SQL. It
is a long-running process that opens local sockets (either TCP or Unix sockets)
according to the parameters passed to it. A local application connects to a
Cloud SQL instance by using the corresponding socket.

Connection:
  -instances
    To connect to a specific list of instances, set the instances parameter
    to a comma-separated list of instance connection strings. For example:

           -instances=my-project:my-region:my-instance

    For connectivity over TCP, you must specify a tcp port as part of the
    instance string. For example, the following example opens a loopback TCP
    socket on port 3306, which will be proxied to connect to the instance
    'my-instance' in project 'my-project':

            -instances=my-project:my-region:my-instance=tcp:3306

     When connecting over TCP, the -instances parameter is required.

## Solution

In this Google documentation page, there is an example[1] which is exactly the use case that I'm describing,  this example should be taken as a reference and included in the documentation.

[1]: https://cloud.google.com/sql/docs/mysql/connect-docker#tcp-sockets

By default I'm assuming that the bind is done on 127.0.0.1 so the help section should be probably changed in something similar to this :

---
   ❯ ./cloud_sql_proxy --help

The Cloud SQL Proxy allows simple, secure connectivity to Google Cloud SQL. It
is a long-running process that opens local sockets (either TCP or Unix sockets)
according to the parameters passed to it. A local application connects to a
Cloud SQL instance by using the corresponding socket.

Connection:
  -instances
    To connect to a specific list of instances, set the instances parameter
    to a comma-separated list of instance connection strings. For example:

           -instances=my-project:my-region:my-instance

    For connectivity over TCP, you must specify a tcp port as part of the
    instance string. For example, the following example opens a loopback TCP
    socket on port 3306, which will be proxied to connect to the instance
    'my-instance' in project 'my-project'. For scenarios where you have to make
    the socket open from outside you can change the <custom_bind_address> to 0.0.0.0
       

            -instances=my-project:my-region:my-instance=tcp:<custom_bind_address>:3306

     When connecting over TCP, the -instances parameter is required.
---

**Comment by kurtisvg** [comment]
This is documented in our [Authorization with the Cloud SQL Proxy](https://cloud.google.com/sql/docs/mysql/authorize-proxy#configuring_tcp) page as well, but I agree it should be mentioned in the readme and help flag.

**Comment by mousetree** [comment]
> This is documented in our [Authorization with the Cloud SQL Proxy](https://cloud.google.com/sql/docs/mysql/authorize-proxy#configuring_tcp) page as well, but I agree it should be mentioned in the readme and help flag.

No it isn't. Please show where.

**Comment by enocom** [comment]
v1: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/tree/v1#tcp-socket-example

v2: https://github.com/GoogleCloudPlatform/cloud-sql-proxy#configuring-listening-address
