### ISSUE TITLE
cloud_sql_proxy should provide a mode that only logs errors

### ISSUE THREAD

**Issue by ConradIrwin** [GoogleCloudPlatform/cloudsql-proxy#406]
## Feature Description

I would like cloud_sql_proxy to output nothing except for errors.It is very chatty – it logs a lot on startup, and continually for certificate renewals etc.

This causes problems because it prints to the terminal that I am trying to use to do other work (usually with a script like this:).

```
cloud_sql_proxy <...> &
psql <...>
kill %1
```

I would like this to be the default mode, and but I'd also be happy if the `-quiet` flag did this, or if there was another flag that did.

## Alternatives Considered
I tried using `cloud_sql_proxy --quiet` but it both outputs too much (it prints a line `2020/06/12 13:44:02 Cloud SQL Proxy logging has been disabled by the -quiet flag. All messages (including errors) will be suppressed.`) and, by the sound of it, logs too little – I do still want to see errors.

I tried using `cloud_sql_proxy -verbose=false`, but it still outputs too much (it prints a line `2020/06/12 13:56:08 Using gcloud's active project: [xxx-project-id]`)

I tried using `cloud_sql_proxy >/dev/null`, but it seems all the output is already on stderr, and I would still like to see any errors.

**Comment by kurtisvg** [comment]
Hi @ConradIrwin,

Thanks for opening an issue.

Is using the `-log_debug_stdout` flag and redirect stdout to `/dev/null` quiet enough for you?

`cloud_sql_proxy -log_debug_stdout > /dev/null &`

**Comment by ConradIrwin** [comment]
Seems perfect! Sorry for missing that, I have to confess I got frustrated after my first three attempts and stopped looking.
