### ISSUE TITLE
Update cloud_sql_proxy version installed by `gcloud components`

### ISSUE THREAD

**Issue by arbourd** [GoogleCloudPlatform/cloudsql-proxy#408]
The current version of cloudsql-proxy being installed by `gcloud components` is 1.13. Anyway we can get return to that release channel? 😁

**Comment by arbourd** [comment]
Oh another quick thing! By default the bin `cloud_sql_proxy` is not symlinked to `/usr/local/bin` like other products (`gcloud`, `gsutils`). Would be awesome to have that automated as well.

**Comment by kurtisvg** [comment]
I've opened an internal bug against the team that manages the gcloud to make sure this is on their radar.

**Comment by kurtisvg** [comment]
The current version is gcloud should be v1.17 or higher at the moment. There is work being done to automate the process.

**Comment by 2m** [comment]
Just tried to install it and it is still 1.13:
```
~ ─╼ gcloud components install cloud_sql_proxy                                                                              


Your current Cloud SDK version is: 315.0.0
Installing components from version: 315.0.0

┌─────────────────────────────────────────────────────────────────────────┐
│                   These components will be installed.                   │
├─────────────────────────────┬─────────────────────┬─────────────────────┤
│             Name            │       Version       │         Size        │
├─────────────────────────────┼─────────────────────┼─────────────────────┤
│ Cloud SQL Proxy             │              1.13.0 │             7.3 MiB │
│ Cloud SQL Proxy             │              1.13.0 │                     │
└─────────────────────────────┴─────────────────────┴─────────────────────┘
```

**Comment by arbourd** [comment]
I just got updated to 1.18.0 today, so maybe that issue is resolved @2m. Although, it still doesn't appear on my path by default (like other `gcloud components`)

**Comment by kurtisvg** [comment]
Just a quick update here - the proxy version gcloud installs has been updated to at least `1.18.0` and the version string is now listed correctly. I've filed a separate internal bug for updating the installation to add itself to the PATH, but I'm going to mark this as closed since it's not related to the repo.

**Comment by ScubaDrew** [comment]
Doesn't appear on my path by default either.

**Comment by enocom** [comment]
I just double checked on Linux and after installing a fresh instance of gcloud, the proxy does appear on the path. Try running through the installation again to make sure you've got your environment properly configured: https://cloud.google.com/sdk/docs/install.

If you still have problems, please open a new issue describing what you did and what you're seeing.
