### ISSUE TITLE
example deployment with Cloud SQL private IP not accurate

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/cloudsql-proxy#409]
[The example](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#private-ip) is about **not** using the Cloud SQL proxy. Why does [the code line](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/54573d521428a322f8049b117854987830fa082a/examples/kubernetes/no_proxy_private_ip.yaml#L43) contain gcr.io/cloudsql-docker/gce-proxy as the 2nd container? Can I delete the 2nd container section and expect the GKE deployment to connect via private IP?

**Comment by kurtisvg** [comment]
That's my mistake. You can safely remove the cloud-sql-proxy container, as it's not actually being used in that example.
