### ISSUE TITLE
Listening on 0.0.0.0 doesn't work

### ISSUE THREAD

**Issue by thecodeassassin** [GoogleCloudPlatform/cloudsql-proxy#41]
I am simply using the sample configuration in the readme:

> stephen@test-asyncjobs-001:/cloudsql$ sudo cloud_sql_proxy -dir=/cloudsql -instances=my-project:us-central1:sql-inst=tcp:0.0.0.0:3306
> 2016/07/22 11:46:11 listenInstance: "my-project:us-central1:sql-inst=tcp:0.0.0.0:3306"
> 2016/07/22 11:46:11 listen tcp: too many colons in address 127.0.0.1:0.0.0.0:3306

The address doesn't seem to be parsed correctly.

**Comment by Carrotman42** [comment]
Are you running the latest version? Try passing --version to see if it
prints out version 1.05.

**Comment by thecodeassassin** [comment]
```
stephen@async-jobs-acceptance-002:~/go_path/bin$ ./cloud_sql_proxy --version
Cloud SQL Proxy: NO_VERSION_SET
```

But when i build it from src it seems to work :) So must have been using an older version.
