### ISSUE TITLE
Wrong Docker Image Tags

### ISSUE THREAD

**Issue by mbyio** [GoogleCloudPlatform/cloudsql-proxy#418]
## Description
The docs say the following Docker image tags are available:

> - v$VERSION - default image (recommended)
> - v$VERSION-alpine - uses alpine:3 as a base image
> - v$VERSION-buster - uses debain:buster as a base image

If you check us.gcr.io/cloudsql-docker/gce-proxy, you're actually tagging images like `$VERSION`, `v$VERSION-alpine`, and `v$VERSION-buster`. Also, `v$VERSION-alpine` and `v$VERSION-buster` only exist for `v1.17`.

## Solution
Update the docs to match the actual docker image tags that are and will be available.

**Comment by shubha-rajan** [comment]
Thanks for catching this and opening the issue! We'll open a PR to update the docs.
