### ISSUE TITLE
cloud sql public ip authorized networks

### ISSUE THREAD

**Issue by slofurno** [GoogleCloudPlatform/cloudsql-proxy#420]
@kurtisvg i noticed you advocated for using public cloud sql instances with cloudsql-proxy in some other issues https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/342, https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/365.

We have been running cloud sql with only private ip addresses, peered to our vpc. We were then using cloudsql proxy to connect to our db, but I have noticed that's not even needed, so maybe we have been doing things wrong.

We are about to setup a bastion so cloudbuild can deploy migrations to our db, but after reading your comments, I feel like it would be simpler to just give our dbs public ips and connect over cloudsql-proxy.

So I have two quick questions:

1.) Is there any google cloud documentation that supports your suggestion as a recommended way of doing things? This would definitely help with getting buy in.

2.) What enforces authorized networks? Will traffic from unauthorized networks hit our db instance, or does google cloud have something in front of the database? Would our db be vulnerable to getting ddosed for example?

**Comment by kurtisvg** [comment]
Apologies for being slow to respond, I wanted to reach out to confirm a couple of things before following up:

> We have been running cloud sql with only private ip addresses, peered to our vpc. We were then using cloudsql proxy to connect to our db, but I have noticed that's not even needed, so maybe we have been doing things wrong.
> 
> We are about to setup a bastion so cloudbuild can deploy migrations to our db, but after reading your comments, I feel like it would be simpler to just give our dbs public ips and connect over cloudsql-proxy.
> 
> So I have two quick questions:
> 
> 1.) Is there any google cloud documentation that supports your suggestion as a recommended way of doing things? This would definitely help with getting buy in.

Our [Connecting Overview](https://cloud.google.com/sql/docs/mysql/connect-overview) does a good job hilighting both the connection path options (public, private) and the authorization options (proxy, Authorized networks, and self-managed SSL). A quick TL;DR is that public requires at least one authentication option (proxy or authorized networks), and while private IP doesn't require use of the proxy it can add an extra layer of security. 

> 2.) What enforces authorized networks? Will traffic from unauthorized networks hit our db instance, or does google cloud have something in front of the database? Would our db be vulnerable to getting ddosed for example?

While I can't provide specifics on implementation, connections from unauthorized networks are rejected at the instance. This means the traffic does reach the instance, but unauthorized clients will not receive a response.
