### ISSUE TITLE
OpenBSD build fails

### ISSUE THREAD

**Issue by since19861019** [GoogleCloudPlatform/cloudsql-proxy#43]
I am trying to build cloudproxy on OpenBSD 5.9 amd64.

On Ubuntu, "go get github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy" succeeds with go 1.63, but it fails on OpenBSD as:

```
go/src/bazil.org/fuse/error_std.go:27 undefined: errNoXattr
go/src/bazil.org/fuse/fuse.go:1345 undefined: attr
go/src/bazil.org/fuse/fuse_kernel.go:404 undefined: attr

```
I used go-1.5 (package) and go-1.6 (from source).
Is there any way to build without fuse support, as I do not need fuse on OpenBSD ?

**Comment by Carrotman42** [comment]
Can you try again after https://github.com/GoogleCloudPlatform/cloudsql-proxy/commit/2d769ed481555c82d0cebddc52ec29851e8fa43b? I believe that's the way to cause it to ignore that package.

**Comment by since19861019** [comment]
It builds and works now.
Thanks.

**Comment by Carrotman42** [comment]
Great! Let me know if there's any other troubles on OpenBSD.
