### ISSUE TITLE
Add Proxy.DialContext(..) method

### ISSUE THREAD

**Issue by colega** [GoogleCloudPlatform/cloudsql-proxy#431]
## Feature Description

Right now `proxy.Proxy` exposes a `func Dial(instance string) (net.Conn, error)` that is registered using [`mysql.RegisterDial(...)`](https://github.com/go-sql-driver/mysql/blob/46351a8892976898935f653f5333782579a96fa5/driver.go#L63) which is [deprecated](https://github.com/go-sql-driver/mysql/blob/46351a8892976898935f653f5333782579a96fa5/driver.go#L62) in favor of [`mysql.RegisterDialContext(...)`](https://github.com/go-sql-driver/mysql/blob/46351a8892976898935f653f5333782579a96fa5/driver.go#L49).

A context-unaware dialling in production has caused us uncontrollably long requests during the failover process of MySQL instances.

A clear and concise description of what feature you would like to see, and why it would be useful to have added.

## Alternatives Considered

We though about instantiating a `*proxy.Proxy{}` in each dial, providing as `Dialer` a `(*net.Dialer{}).DialContext(...)` function curried with the provided context, but since `proxy.Proxy` holds a cache of configs, that would lead to a config retrieval in each of the dials.

## Additional Context

I would be happy to help with this. 

As I can see, we could add a `ContextDialer func(ctx context.Context, net, addr string) (net.Conn, error)` field to `Proxy`, and keep falling back to `Dialer` if this one isn't set. We'd expose a new receiver `DialContext(ctx context.Context, instance string) (net.Conn, error)` on the `Proxy` and the same function at package-level, making the previous `Dial` functions call this one with `context.Background()`. This new functions would be the ones registered as default MySQL dialers for CloudSQL.

In order to support the context in the config retrieval mechanism, we can expose a `RemoteContext` function alternative to `Remote` on the `RemoteCertSource` and as adding that new method to the `CertSource` interface would be a breaking change (which we don't want, I guess) we can check in runtime whether the cert source provided implements the `interface { RemoteContext(...) }` and call it in this case, properly documenting that feature on the `CertSource` interface.

**Comment by kurtisvg** [comment]
Hi @colega,

Thanks for taking the time to open an issue. I agree that this is a change we should support. If you are interested in opening a PR I'm happy to provide feedback on it. 

I'm not sure that the context in the dial function should be passed onto the background refresh - ideally we should only have one refresh happening per instance (which we have some work to do to achieve #427), and several dials might be potentially block on that refresh from happening. It seems like the dial should be waiting on the result from the refresh and quit waiting if the context completes early.
