### ISSUE TITLE
Download from GCS url doesn't work: v1.18.0/linux.amd64

### ISSUE THREAD

**Issue by Stono** [GoogleCloudPlatform/cloudsql-proxy#463]
Just noticed on the latest release, the only one that isn't working is the one I need (amd64), it just 404's

https://storage.googleapis.com/cloudsql-proxy/1.18.0/cloud_sql_proxy.linux.amd64

**Comment by karatekaneen** [comment]
Ran in to the same issue and it fails silently when following the guide from the quickstart:

```
wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
chmod +x cloud_sql_proxy
```

And in the shell it looks like this:
```
Connecting to dl.google.com (172.217.20.46:443)
cloud_sql_proxy      100% |*********************************************************************| 15.6M  0:00:00 ETA
/app # chmod +x cloud_sql_proxy
/app # ls -l cloud_sql_proxy
-rwxr-xr-x    1 root     root      16444117 Sep  9 09:36 cloud_sql_proxy
/app # ./cloud_sql_proxy
/bin/sh: ./cloud_sql_proxy: not found
```

**Comment by kurtisvg** [comment]
Hi @Stono,

There as a mistake in the release notes, and that url was malformed. The correct URL seems to work as expected:

https://storage.googleapis.com/cloudsql-proxy/v1.18.0/cloud_sql_proxy.linux.amd64

**Comment by Stono** [comment]
Ahh nice one, ta @kurtisvg

**Comment by Stono** [comment]
Looks like I'm hitting https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/462 now, the download works but the binary is broken

**Comment by kurtisvg** [comment]
@Stono Would you mind commenting on that issue with more detail? I'm trying to replicate that one as well but it seems to work fine for me
