### ISSUE TITLE
Docker image tags without patch version no longer pull after 1.17

### ISSUE THREAD

**Issue by jacque006** [GoogleCloudPlatform/cloudsql-proxy#472]
## Bug Description

Prior to `1.18.0`, all `cloudsql-proxy` images had a both the full version tag and a tag without the patch version (i.e. `1.17`). Starting with `1.18.0` it appears the patchless tag is no longer included.

![Screen Shot 2020-09-21 at 10 54 42 AM](https://user-images.githubusercontent.com/10394161/93797193-26868500-fbf9-11ea-9629-ac1ac19b0869.png)

This change was not documented in the release notes https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases/tag/v1.18.0

## How to reproduce

`docker pull gcr.io/cloudsql-docker/gce-proxy:1.18`

## Environment

1. OS type and version
- macOS Catalina 10.15.6
- Latest version of Ubuntu VM image on GKE
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): `1.18.0`

## Thoughts 

Thinking about how most container systems such as kubernetes cache images, having the patchless version might not be a great idea as you would not get any new bug fixes until the image cache resets and the container restarts. That being said, had to spend time digging down to the registry to figure out what was going on versus just having a line item in the release notes, and writing up this issue in case others run into it.

**Comment by shubha-rajan** [comment]
Hi @jacque006, thanks for opening up this issue. As discussed in #467, we will no longer be releasing image tags without the patch version in order to follow stricter semantic versioning moving forward. 

We can edit the README and release notes to add a note documenting this change if that would be helpful.

**Comment by jacque006** [comment]
@shubha-rajan Apologies for missing the other issue, did not appear in my searches.

I would imagine adding the documentation would prevent confusion from others in the future, so that would be great. Feel free to close this issue as a dupe if you want to use https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/467 for that.
