### ISSUE TITLE
Add full raw URI example for connecting with unix socket 

### ISSUE THREAD

**Issue by zanona** [GoogleCloudPlatform/cloudsql-proxy#499]
## Description
I had a difficult time on finding how I could format the URI of Postgres URI to call Cloud SDK database correctly from an environment variable and had to take bits and pieces together from several sources, including Cloud SDK docs.

## Solution
Besides showing examples of how to connect to the database from different program languages (.i.e: Go, JavaScript, PHP), there should also have an environment variable example for programs accepting an env var in the format of `APP_DATABASE_DATASOURCE=postgres://root:password@1.2.3.4:5432/postgres?sslmode=disable`, helping users to get up and running quick as possible.

## Additional Context
I have added a response to [this SO question](https://stackoverflow.com/a/64315860/165750) trying to make easier for other users, but it would be great having this sort of information added to Cloud SDK docs. Basically listing:

```sh
# Breaking lines for improved readability

POSTGRESS_URI=postgresql:///dbname
  ?host=/cloudsql/myprojectid:region:myinstanceid
  &user=username
  &password=password
  &sslmode=disable
``

**Comment by shubha-rajan** [comment]
Hi @zanona, this is already an improvement to the samples that's in progress. We currently include connection string examples in the comments for some of our languages (like [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/cloud-sql/mysql/sqlalchemy/main.py#L78) for python) but our goal is to do this in samples for all languages.

**Comment by kurtisvg** [comment]
I'm not sure this is a proper fit for Cloud SDK docs - `gcloud` doesn't use the connection URI afaik. 

As @shubha-rajan mentioned, we are updating several of our connection samples to include a reference uri as well, but since that work is not specific to the proxy, I'm going to go ahead and close this.
