### ISSUE TITLE
Info messages saved into stderr

### ISSUE THREAD

**Issue by arkadyb** [GoogleCloudPlatform/cloudsql-proxy#510]
Hi! The sidecar logs seem to be going into sdrerr and therefore displayed as part of Errors pipe on GCP. Is that a know issue or are there known workaround? 

A tons of messages i am talking about are like:
```
New connection for "<sqlinstanceid>"
Client closed local connection on 127.0.0.1:5432
Instance <sqlinstanceid> closed connection
```

**Comment by shubha-rajan** [comment]
#150 implements a flag to override this and log non-error output to Stdout, but it is defaulted to false, as to not break users who are dependent on the existing error logging behavior. If you don't want connection-related messages to log as errors, you can run the proxy with the CLI flag `--log_debug_stdout`  set to true.

**Comment by arkadyb** [comment]
Thanks @shubha-rajan ! Is there any particular reason to not have that `true` by default?

**Comment by kurtisvg** [comment]
@arkadyb See the comments in the original PR: https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/150#issuecomment-369951933
