### ISSUE TITLE
netcat no longer included in docker image

### ISSUE THREAD

**Issue by katzj** [GoogleCloudPlatform/cloudsql-proxy#523]
In updating my cloudsql proxy to 1.18.0, I started having them terminate regularly. Digging in, the reason was that my liveness check was failing as netcat is no longer included in the official docker images.

Adding a liveness check was something recommended in #119 and #137 so removing netcat (especially without it being called out in the release notes!) was a big change. Is there a new recommended way to have a liveness check for the cloudsql proxy pods?

**Comment by kurtisvg** [comment]
Hi @katzj,

As of v1.16 of the Cloud SQL proxy container image is based on distroless. The release notes include this note:
```
Note: The GCR image from this version forward are built from Dockerfile included in this repo. If you are reliant on other tools outside of the cloud_sql_proxy you may encounter some issues. Please see #317 for more details.
```

We also host two alternative images as well (for debian and alpine), which is mentioned in the [README](https://github.com/GoogleCloudPlatform/cloudsql-proxy#container-images). Please note the explicit call out that these images are NOT semantically versioned - the tag indicates the version of the Cloud SQL proxy included in the image, and semantic versions are limited to the surface of the Cloud SQL proxy.
