### ISSUE TITLE
Connecting to a specific db

### ISSUE THREAD

**Issue by simonmorley** [GoogleCloudPlatform/cloudsql-proxy#53]
Not an issue, more of a recommendation.

I think it's worth updating the README to explain that the user must set the db manually when using from within a Go program.

Rather than the typical:

```
db, err = sql.Open("mysql", sqluser+":"+sqlpass+"@tcp("+sqlhost+":"+sqlport+")/"+sqldb+"?charset=utf8&parseTime=true&allowAllFiles=true")
```

It's required to connect to USE a db like this, after calling DialPassword:

```
_, err = e.Exec("USE " + sqldb)
if err != nil {
	panic(err)
}
```

Unless I've totally missed the point, in which case, can someone explain the correct way to dial.

**Comment by Carrotman42** [comment]
I think better docs are always a good thing. In the meantime, here's what I'd do:

Use the [mysql.Cfg](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/51661ce8decacbdbceb35f8b934809514385e25b/proxy/dialers/mysql/hook.go#L68) func, modify the [DBName field](https://godoc.org/github.com/go-sql-driver/mysql#Config), and then pass it to [mysql.DialCfg](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/51661ce8decacbdbceb35f8b934809514385e25b/proxy/dialers/mysql/hook.go#L82).
