### ISSUE TITLE
bug: v1.19.0 x86-32 binaries segmentation violate on first connection

### ISSUE THREAD

**Issue by Tim-Schwalbe** [GoogleCloudPlatform/cloudsql-proxy#543]
## Bug Description

I got the proxy with

`wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 -O cloud_sql_proxy && chmod +x cloud_sql_proxy`

for months now and after your release yesterday I got the following error when I am using it inside my Python Scripts.

I run it inside gitlab:

```
Transform Prod SQL:
  image: python:3.7.2-alpine
  stage: Transform SQL
  variables:
    MYSQL_PWD: $SQL_PASS_PROD
  script:
    - wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 -O cloud_sql_proxy && chmod +x cloud_sql_proxy
    - ./cloud_sql_proxy -instances=xxxx=tcp:0.0.0.0:3306 -credential_file=client.json &
```

Error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804a0ac]
goroutine 102 [running]:
runtime/internal/atomic.Xadd64(0xa4780b4, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy.(*Client).handleConn(0xa478060, 0xffe56b9a, 0x34, 0x868f080, 0xa8ba090)
	/workspace/proxy/proxy/client.go:129 +0x50
created by github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy.(*Client).Run
	/workspace/proxy/proxy/client.go:120 +0x99
ERROR 2013 (HY000): Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 11

```

**Comment by Tim-Schwalbe** [comment]
I just used it in another script with mysql dump and the same issue pops up.

Transform Prod SQL:
  image: python:3.7.2-alpine
  stage: Transform SQL
  variables:
    MYSQL_PWD: $SQL_PASS_PROD
  script:
    - wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 -O cloud_sql_proxy && chmod +x cloud_sql_proxy
    - ./cloud_sql_proxy -instances=xxxx=tcp:0.0.0.0:3306 -credential_file=client.json &
    - sleep 20
    - mysqldump -v -u  client-prod prod > prod-dump-$date_today.sql --host 127.0.0.1 --no-create-db
    - pkill cloud_sql_proxy

**Comment by Tim-Schwalbe** [comment]
okay as soon as I use version 1.18 its working again:
`https://storage.googleapis.com/cloudsql-proxy/v1.18.0/cloud_sql_proxy.linux.386`

**Comment by kurtisvg** [comment]
I'm able to replicate this on 64-bit linux with the 32-bit binary:
```sh
wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 -O cloud_sql_proxy && chmod +x cloud_sql_proxy
kvg@kvg:~$ ./start_proxy.sh $MYSQL_CONNECTION_NAME 
2020/11/20 08:50:01 current FDs rlimit set to 32768, wanted limit is 8500. Nothing to do here.
2020/11/20 08:50:03 Listening on 127.0.0.1:5432 for $MYSQL_CONNECTION_NAME 
2020/11/20 08:50:03 Ready for new connections
2020/11/20 08:52:35 New connection for "$MYSQL_CONNECTION_NAME "
panic: runtime error: invalid memory address or nil pointer dereference
```

But the 64-bit binary works just fine:
```
wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 -O cloud_sql_proxy && chmod +x cloud_sql_proxy
kvg@kvg:~$ ./start_proxy.sh $MYSQL_CONNECTION_NAME 
2020/11/20 08:59:04 current FDs rlimit set to 32768, wanted limit is 8500. Nothing to do here.
2020/11/20 08:59:05 Listening on 127.0.0.1:5432 for $MYSQL_CONNECTION_NAME 
2020/11/20 08:59:05 Ready for new connections
2020/11/20 08:59:07 New connection for "$MYSQL_CONNECTION_NAME "
2020/11/20 08:59:08 Instance $MYSQL_CONNECTION_NAME closed connection
```

Are you actually using an i386 arch? I'll have to see if I can find a compatible machine to test same architecture.

**Comment by kurtisvg** [comment]
Compiling at tag `v1.18.0` doesn't seem to have the same issue:

```
GOOS=linux GOARCH=386 go build -ldflags "-X main.versionString=1.18.0-dev -X main.metadataString=$$GOOS.$$GOARCH" -o cloud_sql_proxy ./cmd/cloud_sql_proxy
kvg@kvg:~/workspace/cloudsql-proxy$ ./cloud_sql_proxy -instances=$MYSQL_CONNECTION_NAME=tcp:33062020/11/20 10:05:18 current FDs rlimit set to 32768, wanted limit is 8500. Nothing to do here.
2020/11/20 10:05:20 Listening on 127.0.0.1:3306 for $MYSQL_CONNECTION_NAME
2020/11/20 10:05:20 Ready for new connections
2020/11/20 10:05:21 New connection for "$MYSQL_CONNECTION_NAME"
2020/11/20 10:05:21 Client closed local connection on 127.0.0.1:3306
```

**Comment by Carrotman42** [comment]
FWIW I can't reproduce the issue like @kurtisvg did in https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/543#issuecomment-731289405

Are there any special things about this instance that you can think about?

Taking a look at the code, it's quite weird to me that this is happening at all. The panic implies that the `Client` receiver is nil when [handleConn](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/proxy/client.go#L129) is called, and we can see from the stack trace that handleConn is in a goroutine created by [Run](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/proxy/proxy/client.go#L118). That Run method is called in [the main function](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L557) on a Client object that was *definitely* not nil, at least by my read, because it was [unconditionally initialized](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L492).

**Comment by kurtisvg** [comment]
The line the error is calling out: https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/5f0ed2f79bd484ea72328145df8c76f1c44d83db/proxy/proxy/client.go#L129

But specifically it's calling out one line down in the stack (`go/src/runtime/internal/atomic/asm_386.s:105`), which is weird because it's passing an int64 on the client - which means the client is means the is nil (which it can't be?)

**Comment by Carrotman42** [comment]
The Client can be nil, in Go receivers can be nil: https://play.golang.org/p/8shMiNz6DFc

But from my look (see my prior comment), I don't know how the Client got to be nil in the first place.

It's unclear to me whether the inclusion of the `AddUint64` function in the stack trace is just an artifact of inlining; I'd expect the nil pointer error to technically happen /before/ `AddUint64` was called as the `&c.ConnectionsCounter` argument is evaluated.

**Comment by Carrotman42** [comment]
I believe this is a Go compiler bug. This minimal reproducer causes a crash when compiling with `GOARCH=386` on my 64-bit linux machine: https://play.golang.org/p/CAgRZXIZMRu

I will file a new issue on the Go project.

**Comment by Carrotman42** [comment]
ooo, the plot thickens: with running on gotip give us `panic: unaligned 64-bit atomic operation` instead, which confirms the theory of what's going on here. I can't find docs in sync/atomic about this alignment requirement for x86, just MIPS (https://tip.golang.org/pkg/sync/atomic/#pkg-note-BUG), I wonder if this is our bug or Go's bug. I will say I never experienced this before on intel processors.

**Comment by Carrotman42** [comment]
Posted on golang-nuts instead of filing an issue, in case this is actually WAI (https://groups.google.com/g/golang-nuts/c/2BVboKRzDdo).

**Comment by Carrotman42** [comment]
Reporting a boring result (I'm glad I didn't file the issue ;] ) the sync/atomic docs **do** talk about i386, but it calls it x86-32 (which I'm embarrassed to have glossed over when reading it, my mistake).

So we have to just make sure all fields we are doing atomics on are aligned appropriately.

**Comment by kurtisvg** [comment]
Adding some of @Carrotman42's comments from chat as well for future me:
1. We should add a unit test (using [unsafe.Offsetof](https://golang.org/pkg/unsafe/#Offsetof))
2. Either of the following:
  a. Manually pad the struct
  b. allocate a dedicated uint64 value and store an `*int64` in the Client instead, since newly allocated objects are guarenteed to be 64-bit aligned

Leaning towards 2b since it seems more likely to stay fixed if other values in the struct change.

**Comment by kurtisvg** [comment]
I've also reverted the x86-32 links at `https://dl.google.com/cloudsql/` back to v1.18.0 for now.

**Comment by patcombe** [comment]
@kurtisvg @Carrotman42 Does this seem to be the same issue? Sorry I am not that well versed with this all. 

`root@raspberrypi:~/go/bin # ./cloud_sql_proxy -instances=*********:us-east4:algorithm-library=tcp:1234 -credential_file=./*********.json &
[1] 756
root@raspberrypi:~/go/bin # 2020/11/24 22:21:17 Rlimits for file descriptors set to {&{8500 1048576}}
2020/11/24 22:21:17 using credential file for authentication; email=devicetest2@sentinel-project-278421.iam.gserviceaccount.com
2020/11/24 22:21:43 Listening on 127.0.0.1:1234 for *********:us-east4:algorithm-library
2020/11/24 22:21:43 Ready fomysql -u sentinel_devices  -p --host 127.0.0.1 --port 1234
Enter password:
2020/11/24 22:22:01 New connection for "*********:us-east4:algorithm-library"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12aec]

goroutine 42 [running]:
runtime/internal/atomic.goXadd64(0x247a654, 0x1, 0x0, 0x241c058, 0x0)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy.(*Client).handleConn(0x247a600, 0xbed8f89b, 0x32, 0x669110, 0x24106e0)
	/home/pi/go/pkg/mod/github.com/!google!cloud!platform/cloudsql-proxy@v1.19.0/proxy/proxy/client.go:129 +0x4c
created by github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy.(*Client).Run
	/home/pi/go/pkg/mod/github.com/!google!cloud!platform/cloudsql-proxy@v1.19.0/proxy/proxy/client.go:120 +0x88
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0 "Internal error/check (Not system error)"`

**Comment by kurtisvg** [comment]
@patcombe Looks the same to me. If your pi is only 32-bit you'll need to revert to an earlier version until we release a fix.

**Comment by patcombe** [comment]
@kurtisvg sounds good! Do you know the easiest way of getting the earlier version?

**Comment by Jeskz0rd** [comment]
Should I consider that all these images were affected by this issue?
![image](https://user-images.githubusercontent.com/23460187/100184629-ef11ae80-2eaf-11eb-993f-cb69f439a895.png)

**Comment by patcombe** [comment]
@kurtisvg I saw this but I wasn't able to successfully get 1.18 installed
https://stackoverflow.com/questions/30188499/how-to-do-go-get-on-a-specific-tag-of-a-github-repository

**Comment by kurtisvg** [comment]
@patcombe - `GO111MODULE=on go get github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy@v1.18.0` (using Go 1.14).

@Jeskz0rd I think the images available are 64-bit flavored, so I don't believe they are impacted.

**Comment by kurtisvg** [comment]
A solution we might have missed is that the first field at the beginning of each struct is guaranteed to be 64bit aligned, so the easiest solution might be to just move it to the top of the struct. 

Also a quick check shows that the only place we are using sync/atomic on individual fields is the one, so we don't need to worry about padding for any other fields.
