### ISSUE TITLE
How to set SQL Proxy log severity (Log Viewer)

### ISSUE THREAD

**Issue by Emixam23-FCMS** [GoogleCloudPlatform/cloudsql-proxy#551]
## Question
I would like to know how to set the INFO output as INFO in the Log Viewer console on GCP instead of as ERROR output:

```
Error 2020-11-25 12:07:51.195 UTC+1 2020/11/25 11:07:51 Received TERM signal. Waiting up to 0s before terminating.
Error 2020-11-25 12:07:53.009 UTC+1 2020/11/25 11:07:53 using credential file for authentication; email=XXXXXXXXXXXXXXXXXX
Error 2020-11-25 12:07:53.153 UTC+1 2020/11/25 11:07:53 Listening on 127.0.0.1:5432 for XXXXXXXXX
Error 2020-11-25 12:07:53.154 UTC+1 2020/11/25 11:07:53 Ready for new connections
Error 2020-11-25 12:07:53.247 UTC+1 INFO:Fetching an access token from the metadata service
Error 2020-11-25 12:07:53.251 UTC+1 INFO:Fetching the service config ID from the rollouts service
Error 2020-11-25 12:07:53.917 UTC+1 INFO:Fetching the service configuration from the service management service
Error 2020-11-25 12:07:54.335 UTC+1 INFO Attribute zone: XXXXXXXXX
Error 2020-11-25 12:07:54.338 UTC+1 INFO:Attribute project_id: XXXXXXXXX
Error 2020-11-25 12:07:54.343 UTC+1 INFO:Attribute kube_env: XXXXXXXXX
```

## Additional Context
As you can see, even if it's logged with the annotation INFO, it still appears as ERROR in the GCP Log Viewer..

*deployment*
```
        - name: sqlproxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command: ["/cloud_sql_proxy",
                    "{{ .Values.pgDbInstance }}",
                    "-credential_file=/secrets/cloudsql/credentials.json",
                    "-verbose=false"]
```

## Note

I know that you already had opened issues such as https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/138 but as of today, I don't see any clear information about it, sorry :/

**Comment by shubha-rajan** [comment]
Hi @Emixam23-FCMS, if you don't want connection-related messages to log as errors, you can run the proxy with the CLI flag `--log_debug_stdout` set to true. This flag was added in #150 and as explained in the conversation on that PR, it defaults to false to not break users who rely on the default logging to Stderr.

Closing this for now, but feel free to reopen if you have questions.

**Comment by Emixam23-FCMS** [comment]
Hey!

I think I will let it closed for now :) I will then put the `log_debug_stdout ` option as stated in the other PR. I wasn't really sure to fully understand this approach so thanks for your message!

**Comment by Emixam23-FCMS** [comment]
Well just tried it and... Nothing :/ I do still have the issue...
Why this is logged as error but not info as annotated? 

```
- name: sqlproxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.17
    command: ["/cloud_sql_proxy",
        "{{ .Values.pgDbInstance }}",
        "-credential_file=/secrets/cloudsql/credentials.json",
        "-verbose=false",
        "-log_debug_stdout=true"]```

However, in your answer, you seem to mention `--log_debug_stdout=` instead of `-log_debug_stdout=`, which one is the right one? And so, is verbose well set as well?

**Comment by kurtisvg** [comment]
@Emixam23-FCMS In GKE, logs written to the standard output are on the INFO level and logs written to the standard error are on the ERROR level. The Cloud SQL proxy however, defaults to logging to stderr. 

The `-log_debug_stdout` flag that @shubha-rajan mentioned is how you change the Cloud SQL proxies default behavior. It's also listed in the README of the repo. 

It looks like you have a bunch of logs that aren't related to the Cloud SQL proxy:
```
Error 2020-11-25 12:07:53.247 UTC+1 INFO:Fetching an access token from the metadata service
Error 2020-11-25 12:07:53.251 UTC+1 INFO:Fetching the service config ID from the rollouts service
Error 2020-11-25 12:07:53.917 UTC+1 INFO:Fetching the service configuration from the service management service
Error 2020-11-25 12:07:54.335 UTC+1 INFO Attribute zone: XXXXXXXXX
Error 2020-11-25 12:07:54.338 UTC+1 INFO:Attribute project_id: XXXXXXXXX
Error 2020-11-25 12:07:54.343 UTC+1 INFO:Attribute kube_env: XXXXXXXXX
```

For these, you'll have to configure your application to output to the correct stream appropriately.
