### ISSUE TITLE
Google Cloud SQL API Quotas apply; may kill your application

### ISSUE THREAD

**Issue by fogs** [GoogleCloudPlatform/cloudsql-proxy#57]
Connecting to a Google Cloud SQL instance via tcp_3306 is not counting towards any API quotas. Connecting to a Google Cloud SQL instance via the cloudsql-proxy however IS counting towards the Google Cloud SQL API Quotas. Specifically, there is a limit of 10k queries per day and a limit of 100 queries per 100 seconds per user. Queries in this case refer to API queries, not SQL queries.

An API query is not just consumed for creating a connection, but also for other interactions, depending on ones configuration; e.g. getting a list of instances when you do not have configured fixed instances.

We are currently learning this the hard way, by having our GCE hosted application being down because of an exceeded API limit. I am very disappointed that this is hitting us completely unexpected. 

On the one hand the cloudsql-proxy is absolutely necessary when using autoscaling GCE instance groups (you cannot determine your GCE instance's IP addresses when machines are booted to meet a raising demand and thus cannot configure "Authorized networks" on the SQL instance. Or open ACLs to all IPs, which is no option either). On the other hand, switching from tcp_3306 connections to the cloudsql-proxy may silently kill your application if you don't closely monitor API usage.

The documentation of this project both here on Github as well as on the official Google sites should make this crystal clear. That is not the case today.

**Comment by fogs** [comment]
To add to my issue above, the API method sql.instances.list seems to be the problem here: it was called once every second, quickly saturating the 10k / day quota. 

I had my instance run as ```/usr/local/bin/google-cloud-sql-proxy -dir=/var/run/cloudsql -instances_metadata=instance/attributes/cloud-sql-proxy-instances``` and the metadata attribute contained ```projectname-redacted:europe-west1:instancename-redacted```. Since I can connect via 
```
mysql -u myusername -p -S /var/run/cloudsql/projectname-redacted:europe-west1:instancename-redacted mydbname
```

When checking the source code, I am unable to find the locate where the gcloud sql instances list method is called. Is that API methode queried by cloudsql-proxy at all? I know that my application on the GCE instance does not use this API method.

**Comment by Carrotman42** [comment]
The "list" API should only be called if -instances and -instances_metadata
are both unset. Let me take a look at the code to see if there's a bug
about it being called if just -instances_metadata is set.

**Comment by Carrotman42** [comment]
I don't quite understand how you could accidentally be calling the 'list' API once per second unless your google-cloud-sql-proxy is starting up once per second (and you set the --projects flag): the List API is called once per project in --projects [0]. Do you have code running somewhere which causes the Proxy to be started with the --projects flag often?

[0] https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/249c4560aac875c9c86769cfc79b005bd705f728/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L235

Note that the Proxy is meant to be a long-running process, being restarted only when necessary (e.g. OS updates, when scaling up servers). In the steady-state case, there will only be 2 API calls per hour per database instance from a specific invocation of the Proxy. This actually will allow you to scale up to a large number of VMs before hitting the default quota.

Let's say you have 2 databases you want to connect to (therefore 4 API calls/hour/Proxy).

* From a scaling point of view, with 100 queries in 100 seconds you could start 25 different Proxy invocations in the 100s timespan and not be rate limited [1].
* Assuming the invocations are actually staggered throughout the hour such that the above rate limit is not hit, you can run quite a bit of Proxies in a day. Given the default 10k daily quota and 2 database instances (say a master and a replica), that allows you to run 100 Proxy invocations constantly throughout a day [2].

[1] (100 API calls/100s) / (4 API calls/Proxy startup) = 25 Proxy startups in 100s
[2] (10000 API calls/day) / (4 API calls/hour/Proxy  * 24 hours/day) = ~104 Proxies

Either way, I agree that the issue of quotas should be better documented in the context of the Proxy. I've filed an internal bug to update our Proxy docs to include a section discussing quotas, and will use this issue to track adding information to the project's README.

**Comment by fogs** [comment]
Carrotman42, thanks for the quick reply!

I have the cloudsql-proxy running on approx 12 GCE instances; the actual number varies as GCE groups have autoscaling enabled. Since I am using the upstart script I submitted in https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/47/commits/8a246289f9f8b5a0afd4b9118e952b4fafe59b0c I can see in the Stackdriver Logging that in the 24h prior to the API quota exhaustion, 7 times the string "pre-start script completed" was logged by the upstart script on any of the GCE instances in the project. The cloudsql-proxy upstart job did not have to respawn on any machine. There is no cloudsql-proxy instance running outside of an upstart script, neither is there any other component in our architecture calling the Google Cloud SQL API.

After recovering from the incident yesterday, I have switched back from tcp_3306 to the cloudsql-proxy. The  Google Cloud SQL API stats are all fine and the outage cannot be reproduced. Good for the application, bad for me trying to get to the bottom of this.

Let me know if you need me to provide further details.

**Comment by Carrotman42** [comment]
It sounds like there was some rogue process running under credentials associated with your project which ate up your quota. Were you doing development and testing with the list API? If you don't already, I suggest testing/developing your code using a different GCP project to prevent any sort of non-production bug from causing this sort of problem.

Unfortunately, I can't think of anything to do to investigate this incident since it doesn't appear to be related to the Cloud SQL Proxy (since you don't pass --projects, and that's the only way the List API is called). I don't have access to the API logs containing the IPs which made the API calls, but I will request one-time access and see what I can come up with. Maybe it will help you track down from where the calls originated.

**Comment by fogs** [comment]
Thanks for coming back to me! As the process is now running fine since the initial incident (currently I see 300 API requests for the last 24h), I agree to you when you say there must have been a rogue process. Not sure if cloudsql-proxy or any other one. This happened in the project for prod; both dev and test are separate environments. I was unable to locate where I can see in the cloud console or stackdriver interface which resource requested the API calls.

If you are positive that the root cause for the incident has not been the cloudsql-proxy, feel free to close this issue. Don't want to waste your time when this should be on someone else's plate. I am leaving this open in case you have additional info. In any case, thanks a lot for your feedback as well as for the cloudsql-proxy itself; it is greatly appreciated.
