### ISSUE TITLE
Invalid JWT error when using Cloud SQL Proxy for the first time but successfully runs during second time etc

### ISSUE THREAD

**Issue by patcombe** [GoogleCloudPlatform/cloudsql-proxy#588]
## Bug Description

- Using Cloud SQL Proxy on RPi using a compiled version from GO. 
- Currently using bash script to open Cloud SQL Proxy upon device start. 
- I have noticed that the Cloud SQL Proxy does not connect on it's first attempt after the device has been off for a couple of hours. However, any subsequent device booting it will work. 
- I am not sure why it fails to connect just the first time after a long downtime period
- Error received: {"error": "invalid_grant", "error_description": "Invalid JWTL Token must be a short-lived token....
- Happy to provide any more info!

## Example code (or command)

```
./cloud_sql_proxy -instances=*****:us-east4:algorithm-library=tcp:1234 -credential_file=../../credentials/s****.json -term_timeout=30s  & 

```

## Stacktrace
```
Error received: {"error": "invalid_grant", "error_description": "Invalid JWTL Token must be a short-lived token....

```

## How to reproduce

  1. I am not entirely sure as it is a very specific case. 

## Environment

1. OS type and version: RPi Raspbian 
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): 1.18

**Comment by shubha-rajan** [comment]
I might be able to find out more with the full error message, but from a quick search, it looks like a common cause of this error is the computer's clock being out of sync with NTP: https://stackoverflow.com/questions/36189612/token-must-be-a-short-lived-token-and-in-a-reasonable-timeframe

It could be possible that shutting down or rebooting your RPI device throws the clock out of sync so the first request fails, but it's corrected before the second request.

**Comment by patcombe** [comment]
@shubha-rajan Oh very interesting, maybe there is a way to force the computer's clock before I try to connect to the Cloud SQL Proxy. I will run more tests and get back to you

**Comment by shubha-rajan** [comment]
Closing this stale issue. Feel free to reopen if you want to follow up.
