### ISSUE TITLE
Create official Helm chart

### ISSUE THREAD

**Issue by jayjun** [GoogleCloudPlatform/cloudsql-proxy#61]
The official [docs](https://cloud.google.com/sql/docs/container-engine-connect) recommend the "sidecar pattern" for deploying to Google Container Engine. It's painstaking to follow the instructions currently, having to hand wire secrets up and carefully splice lines of code together from the sample YAML.

It'll be nice to have an official `google/cloudsql-proxy` Helm chart.

Install with a single `helm install google/cloudsql-proxy -f values.yaml` command.

In addition, I would like to suggest instructions for a standalone pod/service hosting `cloud_sql_proxy` that listens on `tcp:0.0.0.0:3306`, also installed using a Helm chart. Yes, it's less secure than listening on localhost, but for those who have secured their cluster properly, decoupling Cloud SQL proxy from the application pod greatly simplifies deployment.

**Comment by Carrotman42** [comment]
I am unfamiliar with Helm entirely. Is there a chance you would be able to send a pull request?

**Comment by jayjun** [comment]
@Carrotman42 Honestly I'm a Helm beginner too. Though I doubt this is a suitable repo to host the chart?

Anyway, I took a shot and submitted a PR for further discussion.

**Comment by kevchentw** [comment]
There is a chart for it on https://github.com/kubernetes/charts/tree/master/stable/gcloud-sqlproxy

**Comment by kevchentw** [comment]
Maybe we can add it on readme?

**Comment by jayjun** [comment]
Oops, I closed the pull request (#67) already, but left this issue open.

I’m closing this issue now. Maybe @kevchentw can submit another pull request to adjust README.

**Comment by kevchentw** [comment]
ok. I will send a PR latter
