### ISSUE TITLE
PostgresQL support

### ISSUE THREAD

**Issue by bouk** [GoogleCloudPlatform/cloudsql-proxy#70]
Now that [there's a cloud sql for postgres](https://cloud.google.com/sql/docs/features#postgres) it would be handy if the cloudsql-proxy supported it too

**Comment by Carrotman42** [comment]
It does :) https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases/tag/1.07

If you're having trouble getting it to work, please reopen a more specific issue.

**Comment by bouk** [comment]
Ah I see. I was looking under proxy/dialers and assumed the lack of postgres driver meant it wasn't supported. Thanks!
