### ISSUE TITLE
Multiple instances over TCP socket?

### ISSUE THREAD

**Issue by hazcod** [GoogleCloudPlatform/cloudsql-proxy#739]
## Question
Hi, how are we supposed to connect to multiple instances when using a TCP socket to connect?
I've noticed that supplying e.g. `'-instances=xxx:europe-west1:db1=tcp:3126,xxx:europe-west1:db2=tcp:3127'` will result in the following log:

```
2021/04/19 15:21:54 Listening on 127.0.0.1:3126 for xxx:europe-west1:db1
2021/04/19 15:21:54 Listening on 127.0.0.1:3127 for xxx:europe-west1:db2
```

Notice the two TCP ports for the same database.

**Comment by kurtisvg** [comment]
Hi @hazcod - 

I'm not sure what you are asking. It looks like you've passed in two different instance names (`db1` and `db2`) and they are both listening on separate ports. Did you want a different behavior?

**Comment by hazcod** [comment]
I seem to be off this world today, I read that as the exact same ports.. :-(
