### ISSUE TITLE
unix-socket maximal path length exceeded when cloudsql-proxy tries to open a unix socket in the directory specified by `-dir` parameter

### ISSUE THREAD

**Issue by Manan007224** [GoogleCloudPlatform/cloudsql-proxy#747]
## Description
When we start cloudsql-proxy using unix sockets using this command 
```
./cloud_sql_proxy -dir=/cloudsql -instances=INSTANCE_CONNECTION_NAME
-credential_file=PATH_TO_KEY_FILE &
```

cloudsql-proxy opens a unix socket in the path `/cloudsql/INSTANCE_CONNECTION_NAME`. However unix-socket paths have a path lenght limit dependent on the platform it runs. If the unix socket path length exceeds the limit cloudsql-proxy throws the following error :- 
`bind: invalid argument`.

While this could be solved by overriding the `-dir` parameter and provinding an absolute path in the `-instance` parameter, the issue of unix socket path limit should be documented somewhere, so that the users are aware of this.

**Comment by enocom** [comment]
Thanks for the bug report @Manan007224. It seems like the proxy could return a better error, in addition to whatever documentation changes we make.

**Comment by enocom** [comment]
Here are some details about the unix socket path length. Adding this here for reference:

https://unix.stackexchange.com/a/367012/26069
