### ISSUE TITLE
How to set HTTP_PROXY when using cloud_sql_proxy on a company network?

### ISSUE THREAD

**Issue by eckara** [GoogleCloudPlatform/cloudsql-proxy#769]
## Question
How can I make sure the cloud_sql_proxy uses the http_proxy settings either set on system level or at the terminal level? 

## Additional Context
Using Mac OS 10.15.7, the network proxy settings are set automatically using a .pac file, and the terminal HTTP and HTTPS proxy environment variables (i.e. HTTP_PROXY, HTTPS_PROXY, http_proxy and https_proxy) are set. Terminal can access websites and do curl or wget using the proxy. 

The authentication works as expected after running the cloud_sql_proxy command and the following log is displayed:
```2021/04/29 21:11:11 New connection for <"instance_name>"```

However when a DB query is executed:
```2021/04/29 21:11:26 couldn't connect to "<instance_name>": dial tcp <instance_ip>: connect: connection refused```

Tracing the request, we can see on our firewall that the connection is not using the proxy and the firewall drops the connection. Egress on 3037 is allowed on our firewall, it blocks all connections that does not use the proxy.

**Comment by kurtisvg** [comment]
Traffic on 3307 isn't HTTP traffic, so it seems reasonable to me that it wouldn't attempt to route non-HTTP traffic using that env var. 

#361 added support for SOCKS proxies, and while the [docs for `Proxy.FromEnviroment`](https://pkg.go.dev/golang.org/x/net/proxy#FromEnvironment) are pretty disappointing, the source seems to indicate that the right env var might be [`ALL_PROXY`](https://github.com/golang/net/blob/aea8142032473bb41e874c31eb771c364b790fb4/proxy/proxy.go#L114).

**Comment by enocom** [comment]
@eckara Did using `ALL_PROXY` resolve your issue?

**Comment by eckara** [comment]
@kurtisvg thanks for the information. 
@enocom I could not get the `ALL_PROXY` working. Meeting with the cyber security team to see if we can bypass proxy on 3307 altogether. Thanks for the follow up.

**Comment by kurtisvg** [comment]
I think the receiving proxy may need to be SOCKS5 compatible - if your proxy is just an HTTP proxy as well, that might be causing the failure as well (hard to say without more info).

**Comment by tellmeaboutcode** [comment]
@eckara I am in a similar situation. Did you figure out a way around this?

**Comment by eckara** [comment]
@tellmeaboutcode We ended up bypassing the proxy all together on 3307.

**Comment by tellmeaboutcode** [comment]
@eckara Our hosts are much restrictive, unfortunately :-( Any external connection needs to go through the proxy and we have been using `http_proxy` but that won't work here. Anyways thanks for getting back, appreciate it.

**Comment by kurtisvg** [comment]
@tellmeaboutcode Are you using a SOCKS proxy and it's not working? Or are you specifically using an HTTP proxy?

An HTTP Proxy won't work because it's not http traffic, but a SOCKS proxy should.

**Comment by tellmeaboutcode** [comment]
@kurtisvg I am specifically using HTTP proxy by passing in `http_proxy` to the cloudsql proxy docker container as an environment variable. I am going to explore how SOCKS proxy can be used and see if that solves my problem.

**Comment by enocom** [comment]
I can confirm the setting `ALL_PROXY` pointing at a socks5 proxy does in fact work with the Cloud SQL Auth Proxy.

For example, I started a simple socks5 proxy using [go-socks5](https://github.com/armon/go-socks5) with the code from the README adding some logging statements to the library to know when a connection is made:

``` golang
package main

import "github.com/armon/go-socks5"

func main() {
        // Create a SOCKS5 server
        conf := &socks5.Config{}
        server, err := socks5.New(conf)
        if err != nil {
                panic(err)
        }

        // Create SOCKS5 proxy on localhost port 8000
        if err := server.ListenAndServe("tcp", "127.0.0.1:8000"); err != nil {
                panic(err)
        }
}
```

Next, I started the Cloud SQL Proxy with the following command (note the protocol of `ALL_PROXY`):

``` shell
ALL_PROXY=socks5://localhost:8000 cloud_sql_proxy -instances=$INSTANCE_CONNECTION_NAME=tcp:5432
```

Then, I connected with `psql`. Both the initial HTTP requests went through the proxy, as did the TCP connections from `psql`.

**Comment by tellmeaboutcode** [comment]
@enocom Thank you. Unfortunately, we do not have SOCKS proxy right now in our org. We are using squid proxy on our hosts. There is no alternative way except to use SOCKS proxy right? I have to talk to our security/infra team as well.

**Comment by kurtisvg** [comment]
Squid proxy appears to be an HTTP proxy. SOCKS isn't a specific brand of proxy, it's a protocol designed for forwarding generic network traffic. HTTP proxies can only handle HTTP traffic, while a SOCKS proxy can handle any network traffic. 

You can certain use an HTTP proxy with the Cloud SQL proxy, but only the HTTP requests will be routed through it. You either need to add an exception to your firewall for 3307, or set up a SOCKS proxy to let it through.
