### ISSUE TITLE
How can I debug notAuthorized errors?

### ISSUE THREAD

**Issue by norbert-yoimo** [GoogleCloudPlatform/cloudsql-proxy#79]
I'm trying to connect to a postgresql instance by using `psql -h 127.0.0.1`, but that fails with:

```
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

And in the cloud sql logs I see:

```
2017/04/05 08:38:23 using credential file for authentication; email=cloud-sql-proxy@myproject-157612.iam.gserviceaccount.com
2017/04/05 08:38:23 Listening on 127.0.0.1:5432 for myproject-157612:europe-west1-c:myproject
2017/04/05 08:38:23 Ready for new connections
2017/04/05 08:39:09 New connection for "myproject-157612:europe-west1-c:myproject"
2017/04/05 08:39:09 couldn't connect to "myproject-157612:europe-west1-c:myproject": ensure that the account has access to "myproject-157612:europe-west1-c:myproject" (and make sure there's no typo in that name). Error during createEphemeral for myproject-157612:europe-west1-c:myproject: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```

The service account I'm using has the CloudSQLAdmin role. I have doublechecked that I have no typos in my project name, and have inspected the credentials file that is mounted into the cloudsql pod that it contains the service account credentials that I'm expecting.

**Comment by Carrotman42** [comment]
I'm guessing that the project you listed in your original post is not actually your project ID since we don't have any databases inside the project "myproject-157612" according to our metadata. Can you send the project name and database name to cloud-sql@google.com and we can continue debugging there?

**Comment by norbert-yoimo** [comment]
Sent mail

**Comment by norbert-yoimo** [comment]
Solved, the issue was that I have assigned CloudSQLAdmin to my user, instead of CloudSQLClient.
