### ISSUE TITLE
Unable to use on windows

### ISSUE THREAD

**Issue by opensourced101** [GoogleCloudPlatform/cloudsql-proxy#8]
When ever the command is run, the following error shows up - "listen tcp 127.0.0.1:3306: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

Not able to do anything further, sure the devs would have come across this on windows. Is there a solution ?

**Comment by Carrotman42** [comment]
It's possible that there's something already listening on port 3306 on your machine, or that your firewall settings are not allowing you to access that port.

I would suggest swapping out the '3306' in the command line to a different port number, running the Proxy as administrator (start it in an administrator command prompt), or following the instructions on this SO post: http://stackoverflow.com/questions/15619921/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi

**Comment by Carrotman42** [comment]
Clearing out some old issues that appear inactive. I have since verified on my own machine that the Proxy works on Windows; please reopen if you are still seeing an issue here.
