### ISSUE TITLE
How to connect using a service account credentials file using the go library

### ISSUE THREAD

**Issue by digiexchris** [GoogleCloudPlatform/cloudsql-proxy#80]
I'm trying to make the go dialer work (from https://godoc.org/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql) from outside of GCE as well as inside kubernetes. I can't use the default service account of the Compute Engine VM, since sometimes I don't run it there. Until now I've been running the proxy on the same machine as the go routine, and then connecting using mysql to 127.0.01:3306 but I'd like to switch to the provided proxy dialer instead.

The example usage from https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/master/tests/dialers_test.go doesn't show how to pass service account credentials.

Any thoughts?

**Comment by Carrotman42** [comment]
There's an easy way (which is simple, inflexible, and potentially not generic) and a hard way (which is flexible but of course requires more code).

Easy way: Set GOOGLE_APPLICATION_CREDENTIALS to the path of the JSON file pointing to your credentials; when you call mysql.Dial some underlying code (https://godoc.org/golang.org/x/oauth2/google) will inspect this environment variable during the call to google.DefaultClient

Hard way: all of the code for doing this is contained in this repository. Unfortunately, it's spread across it pretty evenly :)

1) You must construct an http.Client which attaches the service account's authentication to requests sent to our API backend.

    This repo uses goauth.JWTConfigFromJSON [0]; see this for an example: https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/703c832fe568afe4a7ec21e09f14812eb543b72a/cmd/cloud_sql_proxy/cloud_sql_proxy.go#L207

    [0] https://godoc.org/golang.org/x/oauth2/google#JWTConfigFromJSON

2) Pass this http.Client to proxy.Init: https://godoc.org/github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/proxy#Init

3) Call mysql.Dial just like in the easy way

**Comment by digiexchris** [comment]
Thanks, that's exactly what I needed. I started with the dialer_test and fleshed it out a bit to figure it out for myself, I made a pull request in case it's useful for others too.

https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/83/
