### ISSUE TITLE
How to Programmatically check if proxy is active 

### ISSUE THREAD

**Issue by remy-actual** [GoogleCloudPlatform/cloudsql-proxy#81]
Any way on local dev to conditionally check from my application if gcloud_sql_proxy active?  
I'm on Mac OS X El Capitan, running Wordpress and deploying to GAE flex php environment.  
My use case is scripting a conditional check in wp-config.php so I can set different database connection parameters if Wordpress is using the Cloud SQL instance or local MySQL.  
But I can't find anything different  between when gcloud_sql_proxy is running and when it's not for php to check against. 
Maybe the unix socket?

**Comment by Carrotman42** [comment]
An easy way is to check if the process is still up. If it's not up anymore,
you certainly should start it again :)

If you're looking for a real healthcheck, you could periodically open a
connection to the UNIX socket and see if it: 1) accepts the connection and
2) that the server sends an initial handshake packet.

Unfortunately, that would cause extra connections to your instance, so
depending on the rate at which you want to check for health it may work
just fine.

**Comment by remy-actual** [comment]
This works:

```php
/** Check if gcloud_sql_proxy is active on default MySQL port **/
if (stristr(`lsof -i :3306`, 'cloud_sql')) {
    // returns TRUE if using Cloud SQL instance
} else {
    // returns FALSE if not, using local MySQL or none at all
}
```
