### ISSUE TITLE
Is it possible to connect to the private IP of a Cloud SQL instance in GCP Vertex AI pipeline?

### ISSUE THREAD

**Issue by rituraj17** [GoogleCloudPlatform/cloudsql-proxy#835]
## Question
I am working on a pipeline to perform data transformation of data residing on GCP cloud SQL with private IP on a different project by using the Vertex AI pipeline. I am not able to get any documents regarding connecting to Cloud SQL in it. Does anyone have any idea how to connect Cloud SQL with Private IP to the Vertex AI pipeline? Whether its possible or not?

**Comment by enocom** [comment]
I've never used Vertex AI, but from a quick scan of the docs, I see there's support for [VPC network peering](https://cloud.google.com/vertex-ai/docs/general/vpc-peering).

So, roughly (and without having tried this myself), the steps would be:

1. Configure a VPC network peering between Vertex AI and your VPC that hosts the private IP instance
2. Assuming you're running a [custom container](https://cloud.google.com/vertex-ai/docs/training/containers-overview), you could: 
- either start the proxy as a background process and connect to it, 
- or if you're using one of the languages supported by the proxy connectors (i.e., Go, Java, and Python), you could dial directly to your DB with that connector.

Hope that helps.

**Comment by rituraj17** [comment]
Hi @enocom,
Thanks for answering my question and clearing my doubts.
