### ISSUE TITLE
Connection saturation with 1.23.1 version using unix socket

### ISSUE THREAD

**Issue by faxioman** [GoogleCloudPlatform/cloudsql-proxy#842]
## Bug Description

Using a configuration like this in a k8s deployment

```
- name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command: [ "/cloud_sql_proxy",  "-dir", "/cloudsql", "--quiet", "-instances", "my-project-id:europe-west1:my-instance-id=unix:/cloudsql/socket", "-credential_file", "/tmp/account.json" ]
```

lead to a saturation of available postgres connection.
I observed this in a simple but navigated django web project (with or without using application connection pooling).

Switching to TCP solves the problem.

**Comment by faxioman** [comment]
This is a detail of the number of active connections after and before the switch from unix socket to tcp.
There was no leak with the previous proxy version. 

<img width="261" alt="Screenshot 2021-07-22 at 17 00 58" src="https://user-images.githubusercontent.com/943944/126662230-bd6b95b1-d91a-43e6-b8ef-3eeea17be6dc.png">

**Comment by enocom** [comment]
Thanks for the report @faxioman.

So to summarize:

1. Connect a web app to a Cloud SQL database using a Unix socket
2. Send traffic to that web app for some period of time
3. Observe connection leak
4. Switch to TCP listener and the leak goes away.

How long do you find it takes for this leak to manifest? Is this hours, days, longer?

**Comment by faxioman** [comment]
I see that switching to TCP mitigate the leak but in order to completely solve the leak I need to use 1.23.0 version.
I can see the leak in about 2 or 3 minute.

**Comment by enocom** [comment]
OK. Just to help me reproduce this, what are you using the manage SQL connections?

Also, as a side note, we recommend running the latest proxy version. :-)

**Comment by faxioman** [comment]
Ok but the problem was because of the use of the latest proxy version ;)

In my k8s deployment I was using gcr.io/cloudsql-docker/gce-proxy:latest instead of gcr.io/cloudsql-docker/gce-proxy:1.23.0 (shame on me :D).

My web project is Django 2.1.2 powered. I'm using the default behaviour of opening/closing a connection for every request. With 1.23.1 version, using a connection pooling (CON_MAX_AGE setting) leads to the same connection leak.

**Comment by enocom** [comment]
> Ok but the problem was because of the use of the latest proxy version ;)

Ha. OK. I see. I misread. So in other words, it seems v1.23.1 might have introduced this issue?

Let me spin up a Django app and reproduce this problem. I'll report back here with my results.

**Comment by enocom** [comment]
Here's what I did:

1. Deployed three replicas to my Kubernetes cluster of a small Go app that responds to HTTP requests with the current time from the database, connected to the Cloud SQL proxy (v1.23.1) over a Unix socket, along with a load balancer
2. Sent a steady load to my app using [hey](https://github.com/rakyll/hey) with this command: `hey -n 1000000 -c 10 -q 1 http://$MY_LOAD_BALANCER_IP` (that's 1,000,000 requests, sent by 10 works, each rate limited at 1 qps).
3. Watched the number of connections in Cloud Monitoring to my database (graph is below)

![image](https://user-images.githubusercontent.com/1175430/126682800-e100fe83-ad6e-425a-a553-b96c689d4e02.png)

From the graph, it's clear that the number of connections stays constant.

So, I suspect you're running into a connection management problem in your application code. I would double check that you're properly releasing connections after a request. I'm going to close this issue for now.

If you're still convinced that this is an issue in the proxy, please re-open this and provide a minimal reproduction (either pushing an app to GitHub, or pasting code and K8s config here). Hope this information helps.

**Comment by faxioman** [comment]
thanks @enocom. I think that is an issue in the proxy because the previous version is working fine. Anyway, I'll check again the 1.23.1 version in few days. Bye!

**Comment by enocom** [comment]
@faxioman I'll re-open this in the meantime. If you do see the same error after checking connecting handling, a minimal reproduction would be greatly appreciated.

**Comment by enocom** [comment]
Any additional insight into this @faxioman?

**Comment by enocom** [comment]
Friendly ping. If you'd be willing to share a minimal reproduction, I'd be happy to try to find any bug that might be hiding.

**Comment by faxioman** [comment]
@enocom sorry for the delay 🙏🙏🙏
I was using n1-standard-1 vm in my k8s cluster and, under load, I see that a lot of db connection where left open.
In a django web project, the db connections are opened when a request starts and closed at the request end.
There was slow requests with consequent opened db connections.
I can’t say why switching to older version of proxy mitigate the problem but after some day the problem occurred again.
After switching to n2-standard-2 (but using 3 nodes instead of the previous 6 n1-standard-1) I can’t observe any leak in db connection
Thanks for your support… and sorry for the delay.

**Comment by enocom** [comment]
Thanks for the update, @faxioman. If you see this issue pop up again, feel free to re-open with a minimal reproduction.
