### ISSUE TITLE
How to connect to Postgres Cloud SQL over private IP from Cloud Functions

### ISSUE THREAD

**Issue by Rossco8** [GoogleCloudPlatform/cloudsql-proxy#848]
## Question
My Cloud SQL instance is configured with ``--require-ssl`` and I have a Serverless VPC connector and private service access set up and working fine.   I am relatively sure that private access is working fine because I can connect over private IP from Cloud Shell by using port forwarding to bastion host and supplying the SSL certificates to psql command.   
However from CloudFunctions, I am only able to connect using a public IP.   

This does not work (from cloud functions)
``` python
    db = sqlalchemy.create_engine(
        # Equivalent URL:
        # postgresql+pg8000://<db_user>:<db_pass>@<db_host>:<db_port>/<db_name>
        sqlalchemy.engine.url.URL.create(
            drivername="postgresql+pg8000",
            username=db_user,  #This is my Clouud IAM user
            password=creds.token,  
            host=db_host,  # This is my private IP
            port=5432,  
            database="app-data"  
        ),
   **db_config
)
```
```
line 314, in __init__ raise self.error pg8000.exceptions.DatabaseError: {'S': 'FATAL', 'V': 'FATAL', 'C': '28000', 'M': 'pg_hba.conf rejects connection for host "10.8.0.2", user "data-admin-sa@project-22.iam", database "app-data", SSL off', 'F': 'auth.c', 'L': '447', 'R': 'ClientAuthentication'}
```

And using CloudSQL Proxy does not work (from Cloud Functions)
``` python
    # Connect to CloudSQL via the cloudsql proxy
    db = sqlalchemy.create_engine(
       sqlalchemy.engine.url.URL(
           drivername="postgresql+pg8000",
           username=db_user,  #This is my Clouud IAM user
           password=creds.token,
           query={
               "unix_sock": "{}/{}/.s.PGSQL.5432".format(
                   "/cloudsql",
                   db_host) # This is my private IP
           },
           database="app-data" 
        ),
        **db_config
    )
```
```
Internal error looking up Cloud SQL instance "10.2.0.3"
```
The documentation says the Cloud SQL proxy ``Works with both public and private IP endpoints`` - How can use private IP?

**Comment by enocom** [comment]
Probably an obvious question, but did you [configure your function to use the connector](https://cloud.google.com/functions/docs/networking/connecting-vpc#configuring)?

**Comment by Rossco8** [comment]
I can see how to do this now. Connecting to private IP uses the full connection name - not the private IP address. I'll close this ticket.

The [documentation](https://cloud.google.com/sql/docs/postgres/connect-functions#connecting_to) says to just connect direectly to the private IP, I suppose it actually depends on if require-ssl has been specified or not?

**Comment by enocom** [comment]
If you're connecting a private IP database from Cloud Functions and you've required SSL, you will need to use the private IP address and provide a server cert, a client key, and a client key in your connection configuration. See the [docs on configuring SSL certs](https://cloud.google.com/sql/docs/postgres/configure-ssl-instance).

As a side not, if you're not requiring SSL, you'll still connect using the Serverless VPC Access connector and the private IP address. If you ended up connecting successfully using the instance connection name, I suspect your database has public IP enabled.

Hope that helps.

**Comment by Rossco8** [comment]
Thanks for the update, however I have tested various combinations and currently my instance has no public IP (I removed it couple of days ago and this is now working fine)
```
gcloud sql instances describe mydevdb --format="value(ipAddresses)"
{'ipAddress': '10.2.0.3', 'type': 'PRIVATE'}
```
![Screen Shot 2021-07-29 at 7 14 04 am](https://user-images.githubusercontent.com/44757794/127397143-c40a5fc6-17fe-470f-8d8e-ae49ed3ad142.png)

And I can successfully connect from Cloud Functions & Cloud Run using the instance name 
```
    db = sqlalchemy.create_engine(
       sqlalchemy.engine.url.URL(
           drivername="postgresql+pg8000",
           username=db_user,  
           password=creds.token,
           query={
               "unix_sock": "{}/{}/.s.PGSQL.5432".format(
                   "/cloudsql",
                   db_host) # DB Host is devprj-22:australia-southeast1:mydevdb 
           },
           database="app-data" 
        ),
        **db_config
    )
```
I have configured the serveless VPC connector
![Screen Shot 2021-07-29 at 7 23 49 am](https://user-images.githubusercontent.com/44757794/127398086-580ce040-56cb-4bfc-8810-9dca6a0b8a09.png)
Would you expect that to not work?   
(I do have client certifactes set up & I use them to connect from my internal network. I'm assuming to use certificates from Cloud Functions I will need to mount the private cert from Secrets manager rather than include the certificate file in the function, but have not tried it yet)

**Comment by enocom** [comment]
I'm a little surprised by that -- let me do some more research to understand what's happening here.

In any case, you should be able to connect directly to the private IP, provided you're suppling certs to `sqlalchemy`. Since you're using Python, you can either just upload the certs with your code referencing them like local files, or like you suggest, you can put them in Secrets manager and fetch them at startup.

**Comment by kurtisvg** [comment]
So what's happening here is that Cloud Functions and Cloud Run are using the Cloud SQL proxy under the hood to create the unix socket for you. The Cloud SQL proxy's default behavior is to use a Public IP if it has one, or if it doesn't it'll fall back to the Private IP for an instance. However, we don't recommend folks to rely on this, because if at any point in the future you add a public IP, it'll start using that instead. 

For this reason, [our docs for Cloud Run / Cloud Functions](https://cloud.google.com/sql/docs/mysql/connect-run#private-ip) recommend connecting directly using the IP instead. 

If you are using Python, you might also be interested in the [Cloud SQL Python connector](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector). It works the same way at the proxy, but from a python run time.

**Comment by Rossco8** [comment]
thanks, that makes sense. If I have no plans on assigning a public IP is there any reason I would not just continue to use the CloudSQL proxy? I like the simplicity of not having to provide the certificates in the serverless environments.

**Comment by Rossco8** [comment]
ok, I'll have a look at the Python connector but I can see it is still in Alpha, I need stability at where I am at in my project so I might wait before switching over to it.

cheers,
