### ISSUE TITLE
Postgres IAM authentication is flaky due to OAuth2 token inconsistency

### ISSUE THREAD

**Issue by shubha-rajan** [GoogleCloudPlatform/cloudsql-proxy#852]
## Bug Description

See discussion on related Java connector issue https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/565

**Comment by enocom** [comment]
Fixed (temporarily) by https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/851.
