### ISSUE TITLE
Fail readiness health check only when all instance(s) cannot be dialed

### ISSUE THREAD

**Issue by monazhn** [GoogleCloudPlatform/cloudsql-proxy#888]
## Feature Description
This issue is tracking potential interest in having readiness fail only when **all instance dial attempts fail**, i.e. no instance(s) can be reached. (Applies to the multi-instance use case of the proxy.)

## Alternatives Considered
The current code supports readiness failing if **any** instance cannot be dialed.

## Additional Context
https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/871

Co-authored-by: Tiffany Xiang <tiffanyx@google.com>

**Comment by enocom** [comment]
It's been a few months now without any responses. I'm going to close this and re-open if a duplicate arrives.
