### ISSUE TITLE
"connection timed out" errors

### ISSUE THREAD

**Issue by cuu508** [GoogleCloudPlatform/cloudsql-proxy#90]
In my cloud_sql_proxy output I see fairly regular (every hour or so) messages like this one:

`
cloud_sql_proxy[2112]: 2017/05/05 21:38:42 Reading data from xxx:xxx had error: read tcp xxx.xxx.xxx.xxx:xxxxx->xxx.xxx.xxx.xxx:xxxx: read: connection timed out
`

These seem to match up with errors like this one in my Python code:

```
OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

I have two similar GCE VMs in same region but different availability zones. Only one of them log these errors.

Are timeouts like this one expected? Any tips on troubleshooting them or working around them?

**Comment by Carrotman42** [comment]
Sorry for the delay. This is very interesting!

Are both GCE VMs running the exact same code? Is the Cloud SQL Database in the same zone as either of those VMs, or is it in yet a third?

**Comment by cuu508** [comment]
The VMs are in us-east1-c and us-east1-d. Not sure which zone the database is in, it just says "Location: us-east1". Both VMs are set up with the same provisioning script around the same time, so should be very similar.

In my Django app I had `CONN_MAX_AGE` set to 60, meaning that every database connection is used for up to one minute and then is closed and reopened. I had a hunch that these errors happen when closing and re-opening the database connection (maybe cloud_sql_proxy needs to refresh its credentials and that part times out?). I changed CONN_MAX_AGE to None for unlimited persistent connections. I haven't seen these "connection timed out" errors since then (2+ weeks now, and about the same amount of traffic).

**Comment by Carrotman42** [comment]
Yes, if your app is closing connections after 60 seconds that can definitely cause the sort of messages from the Proxy that you posted in the original issue, but it is still a little weird that the django app was also seeing errors related to that closing.

Since the issue has gone away I will close this issue since it seems you've found a workable workaround. If that ceases to be stable please feel free to reopen the issue!

**Comment by ega-forever** [comment]
have the same problem right now. But in my case, I have one region (europe-west1-b), and timeout happens in a random manner (so it can work for instance, for 2-3 hours, then disconnect by timeout). I even can't find out the reason.
