### ISSUE TITLE
Brief summary of what is missing or incorrect

### ISSUE THREAD

**Issue by bilalahmad99** [GoogleCloudPlatform/cloudsql-proxy#903]
## Description
Mysql is also supported in Gcloud IAM database authentication. So `-enable_iam_login` flag should work with it and I have tested it does work.

## Solution
Update the [Note](https://github.com/GoogleCloudPlatform/cloudsql-proxy#-enable_iam_login) in readme to show Mysql is also supported.

**Comment by enocom** [comment]
Hi @bilalahmad99. Thanks for opening this issue. See https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/865#issuecomment-892798794 for context. In short, MySQL is only supported for manual IAM DB Authentication, not automatic. Rest assured when automatic IAM DB Authn is available, we'll make sure it's clear in the README.
