### ISSUE TITLE
Errors during Post to createEphemeral: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Carrotman42** [GoogleCloudPlatform/cloudsql-proxy#92]
We are receiving intermittent reports that the Cloud SQL Proxy is receiving errors which look similar to this:

    couldn't connect to "$INSTANCE": Post https://www.googleapis.com/sql/v1beta4/projects/$PROJECT/$NAME/createEphemeral?alt=json: stream error: stream ID 1; PROTOCOL_ERROR

If you are encountering this problem, please send the following information to cloud-sql@google.com:

   1) Cloud SQL Instance name and project name
   2) What version of the proxy you are using (pass --version to have it printed out)
   3) Restart the Cloud SQL Proxy, setting an environment variable GODEBUG=http2debug=2 (as per [Go HTTP docs](https://golang.org/pkg/net/http/)). When the PROTOCOL_ERROR occurs again, there should be extra debug logs. Please strip out secret data such as bearer tokens, etc and include this in your email

In addition, we have heard reports that updating to the newest version (1.09) fixes this problem. We'd especially like to hear from anyone running this version that is still affected.

**Comment by Carrotman42** [comment]
We have confirmed that the issues are due to a bug found in earlier versions of the Cloud SQL Proxy (we believe it's related to https://github.com/google/google-api-go-client/issues/161), triggered by a rollout being done for internal Google infrastructure.

All users should update to the latest version (1.09) to ensure that this problem does not affect you now or in the future.

**Comment by thijsterlouw** [comment]
This also affected us. It would be good to put this message on the Google Cloud Console dashboard and/or send an email out, because it took a while before we (via Googling) ended up here...

**Comment by josh123a123** [comment]
Great way to loose trust Google...

**Comment by Carrotman42** [comment]
The underlying infrastructure change which was triggering this bug has been fully rolled back. If you are still encountering this issue please reopen this issue and send an email to cloud-sql@google.com with the information from the original post.

**Comment by Carrotman42** [comment]
I apologize for any trust that was lost here; we worked fast to fix the problem and I was not engaged in any decisions about posting publicly until right before @thijsterlouw's post, at which point the rollback was mostly complete.

Please feel free to email me at cloud-sql@google.com (reference this issue in your mail so that I end up getting forwarded the message) with any specific concerns you have, I'd love to hear you out. If you'd rather converse on GitHub, please feel free to open a new issue where we can discuss what happened there.

**Comment by michaelmitchell** [comment]
We just experienced this same problem in production but of course just before I got to add GODEBUG it resolved its self. Outage was intermittent and lasted aprox 5 hours.

Cloud SQL Proxy: version 1.11; sha 61590edac4c769d295cc5f48140ebeff88ccc5bf built Fri Sep 29 22:26:22 UTC 2017

**Comment by ltearno** [comment]
Just so that if someone gets the same problem : don't forget to check your network policies. On my pod with the cloud_sql_proxy, I has a **network policy** installed, which was preventing the cloud proxy from authenticating (need to open the 443 port so it can do OAuth) and connecting to the database (on port 5432 in my context, a postgres database).
So I got those network errors on the proxy side. So to sum up : if you have this problem, first disable your network policies and see if the problem persists. Then adapt your network policies to the cloud_sql_proxy.
