### ISSUE TITLE
IPv4 addresses still need to be authorized after connecting through cloudsql-proxy

### ISSUE THREAD

**Issue by macuenca** [GoogleCloudPlatform/cloudsql-proxy#93]
We have a Python application in a GKE cluster that connects to a CloudSQL instance trough cloudsql-proxy. Our connections are effectively going through the proxy, I can see traffic from and to the cloudsqlproxy container and the logs confirm this.

The `cloudqslproxy` has access granted from the `cloudsqlproxy~%` hostname and no password.

This is how our Django app config file looks like:
```
    DATABASES = {
        'default': {
            'ENGINE'    : 'django.db.backends.mysql',
            'NAME'      : 'dbname', 
            'USER'      : 'cloudsqlproxy',
            'PASSWORD'  : '', 
            'HOST'      : '127.0.0.1',
            'PORT'      : '',
        }
    }
```

And everything works... as long as our compute engine instances hosting the container IP addresses are white listed in SQL Cloud authorized networks section. We have auto-scaling setup and our VM instances are recycled on a regular basis, causing outages because of the new IPs not being whitelisted.

The whole point of clousql-proxy is not needing to grant access from specific IP addresses and this is not working for us at the moment. We are definitely doing something wrong and any help that lead us to find what it is would be greatly appreciated.

**Comment by Carrotman42** [comment]
You're right - the point is to not have to whitelist IPs. Let's try to
figure out what's up with your system.

You say that you see traffic and logs from the Cloud SQL Proxy, which is a
good sign that it is working correctly somewhat. Is it possible that only
some of your VMs are contacting the Proxy, whereas others attempt to
directly connect to the database's IP?

Some other clarifying questions:
* Does each VM have its own Proxy binary?
* Does each VM have​ exactly the same configuration?
* How do you configure each newly provisioned VM? (You mentioned
autoscaling, so what automation sets up autoscaled VMs?)
* What is the error when you don't have the VM's IP whitelisted (and where
does that error come from)?
* For a VM that is currently working, is it possible for you to remove that
single IP from the Cloud SQL Database's allowed networks and verify that
just that VM has lost access?

**Comment by macuenca** [comment]
Ok, so this is a little embarrasing... Everything seemed to be working as expected and it was. But we had a dependency on second microservice which wasn't using cloudsql-proxy, so removing the IPs from the grant list in Cloud SQL caused it to fail.

This was hard to catch because the rogue microservice was the one handling the sessions, which only has a small fraction of the traffic the other ones have, making the connection error messages hard to spot. When you use connection pooling, all the stalled connections being closed are logged as errors and add a lot of noise to your logs.

Thank you so much Kevin for your help!
