### ISSUE TITLE
Feature: Refresh SSL cert before it expires in the background

### ISSUE THREAD

**Issue by Jille** [GoogleCloudPlatform/cloudsql-proxy#94]
We should refresh the SSL certificate in the background before it expires. This will avoid the latency spike every hour (as mentioned in #87).

**Comment by patrykmikula** [comment]
Any progress on this issue ?

**Comment by AthenaShi** [comment]
I've created an internal ticket and it will be prioritized.

**Comment by kurtisvg** [comment]
It looks like #160 addresses this.

**Comment by lychung83** [comment]
fixed by merge of https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/222
