### ISSUE TITLE
brew formula

### ISSUE THREAD

**Issue by mattes** [GoogleCloudPlatform/cloudsql-proxy#95]
Is someone working on a brew formula?

**Comment by Carrotman42** [comment]
Not sure what that is :)

**Comment by mattes** [comment]
After thinking about it more, there are some obstacles:

* cloudsql-proxy either looks at `GOOGLE_APPLICATION_CREDENTIALS` env variable
   or at the flag `-credential_file`. 
* When using/installing `gcloud`, neither the env variable is set nor is there a service account key file.

So `gcloud` and `cloudsql-proxy` are not compatible as of today, I believe. 

Ultimately, it would be really nice if the proxy would be available with:

```
gcloud sql instances proxy <instance>
```

**Comment by Carrotman42** [comment]
If you don't set the env variable or the flag, the Proxy will still get the
authentication used in gcloud if you have run `gcloud auth login`

**Comment by mattes** [comment]
word! just tried again, no idea what I was doing wrong before.

**Comment by Carrotman42** [comment]
I have zero experience with homebrew, but if you would like to submit a formula I would be very gracious!

**Comment by mattes** [comment]
I will look into this prob within the next days.

**Comment by mattes** [comment]
Priorities shifted unfortunately. I'm not actively looking into this right now.

**Comment by kurtisvg** [comment]
Closing - this issue hasn't been updated for over 6 months and appears to be abandoned.

**Comment by andrmueller** [comment]
I know this issue is outdated, but just in case anyone wonders how to install cloud_sql_proxy via brew it is possible now by using gcloud:
`gcloud components install cloud_sql_proxy`

**Comment by liam-mclaughlin** [comment]
A follow up on @andrmueller point;  The binaries are now stored in

`/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin`

**Comment by jgonera** [comment]
This seems to be installing an old version (1.13, latest is 1.17). Am I doing something wrong? I tried running `gcloud components update` but it still wants to install 1.13.

**Comment by kurtisvg** [comment]
@jgonera Unfortunately the gcloud version being outdated is a known issue - see #408

**Comment by Stoicdata** [comment]
Hello I actually might need some similar help with /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/cloud_sql_proxy -instances= server info

When i run this i get: No such file or directory
anyone know what the issue might be?

**Comment by AlexandreCassagne** [comment]
Was any work done on this?

**Comment by AlexandreCassagne** [comment]
Never mind. Just saw the last message! Good day.

**Comment by enocom** [comment]
There is an unofficial brew formula here: https://github.com/tclass/homebrew-cloud_sql_proxy.

However, it compiles from source which requires Go. It remains easiest to just download the latest version from the [Releases page](https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases).

**Comment by erdemkeren** [comment]
for me it was here:

```
/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/cloud_sql_proxy
```

**Comment by enocom** [comment]
Re-opening as this would make life easier for lots of folks. Seems worth pursuing, although I can't promise a timeline presently.

**Comment by enocom** [comment]
Likely blocked by https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1712.

**Comment by enocom** [comment]
Useful: https://docs.brew.sh/Formula-Cookbook

**Comment by snorremd** [comment]
I've created an unofficial formulae for the 2.X-version over at https://github.com/snorremd/homebrew-tap/pkgs/container/tap%2Fcloud-sql-proxy.

Note that my CI job unfortunately only builds bottles for amd64 architecture so if you are on arm (e.g. M1 or M2 Mac) you need to compile from source. But Homebrew should install go for you if you don't have it installed, so you don't need to do anything manually.

I've yet to figure out a cheapish way to build bottles for Mac arm processors as you'd need short lived access to a Mac M1 machine/server and Apple requires datacenters to rent on a 24hour basis.

**Comment by enocom** [comment]
@snorremd Nice!

As an alternative, if you'd like to contribute a formula here, we could take over the cost of running the builds. Do the builds need to be notarized? I've been waiting to pick this up until we fix #1712.

**Comment by snorremd** [comment]
Notarization is not strictly required by MacOS for binaries I believe. So it should be okay to host formula bottles without signing them.

As for the ARM Mac issue the biggest challenge now would be that you'd have to set up and maintain a self-hosted MacOS GitHub Actions runner. GitHub do have GitHub hosted Mac runners on their roadmap for this year, so perhaps it would be wise to wait for those: https://github.com/github/roadmap/issues/528

I'd be happy to help contribute something to the project, but I suppose you'd want to automate this a bit more than my current formula setup. My suggestion would be to set up a new repository, `https://github.com/GoogleCloudPlatform/homebrew-gcp` so you get a proper homebrew tap for all GoogleCloudPlatform binary projects. Users would then add the tap with `brew tap GoogleCloudPlatform/gcp` and could then install your binary with `brew install cloud-sql-proxy`.

When you mint a new release you could trigger a GitHub actions job that creates a PR for the new release on the tap repository with the new version number and hash, and then allow the tap repository to follow the normal Homebrew CI process of testing the formula, bottling, and uploading packages.

You can use this repository as a standalone tap, but users would then need to use a URL when adding the tap, and it would only contain the cloud-sql-proxy formula. Making a single tap for all cloud platform related binaries would be nicer for users I think.

**Comment by maverick1872** [comment]
Yea this would be awesome. The short term solution would be to at least provide v2 installation via `gcloud components` as currently the latest appears to be `1.27.0`.

**Comment by enocom** [comment]
This seems like an obvious thing to ship. Bumping the priority to reflect that.

Meanwhile, we're working on fixing the gcloud version to support v2, but given the breaking changes, we have to be thoughtful about doing that (and automate it which it's currently not).

**Comment by maverick1872** [comment]
@enocom as a follow-up it appears that when installing via `gcloud` the installed binary is not put into a directory that exists within my `$PATH`. After installation with `gcloud` should it be accessible or is it only accessible via `gcloud beta sql connect`?

**Comment by enocom** [comment]
@maverick1872 This has come up before. Would you mind filing an issue here with details (your OS, your gcloud version, your PATH settings)?

**Comment by jhandguy** [comment]
Hi there folks, `cloud-sql-proxy` is now part of homebrew-core ([#140782](https://github.com/Homebrew/homebrew-core/pull/140782)) and can be installed with `brew install cloud-sql-proxy`.

**Comment by enocom** [comment]
Beautiful! Thank you for this awesome contribution!

**Comment by enocom** [comment]
@jhandguy Does Homebrew Core have automation to update the version?

**Comment by enocom** [comment]
Looks like no: https://docs.brew.sh/Formula-Cookbook#updating-formulae.

But we could easily add this to our release process.
