### ISSUE TITLE
Feature: flag to set client.RefreshCfgThrottle

### ISSUE THREAD

**Issue by imtaco-lh** [GoogleCloudPlatform/cloudsql-proxy#99]
Default client.RefreshCfgThrottle is one minute, so when cloudsql failover, proxy might wait for more than one minute to connect the new master if first connection retry fail.

Is possible to add a flag to set RefreshCfgThrottle manually ?

**Comment by Carrotman42** [comment]
I think this is a good idea, although I'd like to note that there probably should be some sort of forced lower bound to help people not shoot their API quota in the foot in the case that their application does not exponentially back off.
